// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Infrastructure.DataAccess.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using Accounting.Domain.Entities;
#nullable disable

namespace Accounting.Infrastructure.DataAccess;

public partial class AccountingDbContext : DbContext
{
    public AccountingDbContext(DbContextOptions<AccountingDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AccountCategory> AccountCategories { get; set; }

    public virtual DbSet<AccountGroup> AccountGroups { get; set; }

    public virtual DbSet<AccountSet> AccountSets { get; set; }

    public virtual DbSet<AccountSetItem> AccountSetItems { get; set; }

    public virtual DbSet<BalanceRelatedAccountDetail> BalanceRelatedAccountDetails { get; set; }

    public virtual DbSet<BankTemplate> BankTemplates { get; set; }

    public virtual DbSet<ClosingPattern> ClosingPatterns { get; set; }

    public virtual DbSet<ClosingPatternSlaveCompany> ClosingPatternSlaveCompanies { get; set; }

    public virtual DbSet<ClosingPatternTemporaryAccount> ClosingPatternTemporaryAccounts { get; set; }

    public virtual DbSet<Contradiction> Contradictions { get; set; }

    public virtual DbSet<ContradictionItem> ContradictionItems { get; set; }

    public virtual DbSet<DataImport> DataImports { get; set; }

    public virtual DbSet<FloatAccountType> FloatAccountTypes { get; set; }

    public virtual DbSet<Ledger> Ledgers { get; set; }

    public virtual DbSet<LedgerPeriod> LedgerPeriods { get; set; }

    public virtual DbSet<LedgerPeriodCompany> LedgerPeriodCompanies { get; set; }

    public virtual DbSet<LedgerPeriodCompanySetting> LedgerPeriodCompanySettings { get; set; }

    public virtual DbSet<ManualFloatAccount> ManualFloatAccounts { get; set; }

    public virtual DbSet<MasterAccount> MasterAccounts { get; set; }

    public virtual DbSet<Period> Periods { get; set; }

    public virtual DbSet<ResourceAndExpenditure> ResourceAndExpenditures { get; set; }

    public virtual DbSet<Setting> Settings { get; set; }

    public virtual DbSet<SlaveAccount> SlaveAccounts { get; set; }

    public virtual DbSet<SlaveAccountCompany> SlaveAccountCompanies { get; set; }

    public virtual DbSet<SlaveAccountStandardDescription> SlaveAccountStandardDescriptions { get; set; }

    public virtual DbSet<TrashVoucher> TrashVouchers { get; set; }

    public virtual DbSet<TrashVoucherItem> TrashVoucherItems { get; set; }

    public virtual DbSet<TrashVoucherItemAttach> TrashVoucherItemAttaches { get; set; }

    public virtual DbSet<TtmsBuy> TtmsBuys { get; set; }

    public virtual DbSet<TtmsContractorInfo> TtmsContractorInfos { get; set; }

    public virtual DbSet<TtmsEmployerInfo> TtmsEmployerInfos { get; set; }

    public virtual DbSet<TtmsExportation> TtmsExportations { get; set; }

    public virtual DbSet<TtmsImportation> TtmsImportations { get; set; }

    public virtual DbSet<TtmsLeaseAgreement> TtmsLeaseAgreements { get; set; }

    public virtual DbSet<TtmsPreSell> TtmsPreSells { get; set; }

    public virtual DbSet<TtmsProductType> TtmsProductTypes { get; set; }

    public virtual DbSet<TtmsSell> TtmsSells { get; set; }

    public virtual DbSet<TtmsWage> TtmsWages { get; set; }

    public virtual DbSet<Voucher> Vouchers { get; set; }

    public virtual DbSet<VoucherItem> VoucherItems { get; set; }

    public virtual DbSet<VoucherItemAttach> VoucherItemAttaches { get; set; }

    public virtual DbSet<VoucherItemLog> VoucherItemLogs { get; set; }

    public virtual DbSet<VoucherItemStandardDescription> VoucherItemStandardDescriptions { get; set; }

    public virtual DbSet<VoucherLog> VoucherLogs { get; set; }

    public virtual DbSet<VoucherType> VoucherTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Persian_100_CI_AI");

        modelBuilder.ApplyConfiguration(new Configurations.AccountCategoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AccountGroupConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AccountSetConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AccountSetItemConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BalanceRelatedAccountDetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BankTemplateConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ClosingPatternConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ClosingPatternSlaveCompanyConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ClosingPatternTemporaryAccountConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ContradictionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ContradictionItemConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DataImportConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FloatAccountTypeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LedgerConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LedgerPeriodConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LedgerPeriodCompanyConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LedgerPeriodCompanySettingConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ManualFloatAccountConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.MasterAccountConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PeriodConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ResourceAndExpenditureConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SettingConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SlaveAccountConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SlaveAccountCompanyConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SlaveAccountStandardDescriptionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TrashVoucherConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TrashVoucherItemConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TrashVoucherItemAttachConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TtmsBuyConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TtmsContractorInfoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TtmsEmployerInfoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TtmsExportationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TtmsImportationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TtmsLeaseAgreementConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TtmsPreSellConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TtmsProductTypeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TtmsSellConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TtmsWageConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VoucherConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VoucherItemConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VoucherItemAttachConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VoucherItemLogConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VoucherItemStandardDescriptionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VoucherLogConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VoucherTypeConfiguration());
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
