// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace General.Domain.Entities;

public partial class Bank
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual BankStatementPattern BankStatementPattern { get; set; }

    public virtual ICollection<PersonBankAccount> PersonBankAccounts { get; set; } = new List<PersonBankAccount>();
}