// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace General.Domain.Entities;

public partial class EducationalDegree
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string TaxEducationalDegree { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CreatorId { get; set; }

    public virtual User Creator { get; set; }

    public virtual ICollection<PersonEducationalDegree> PersonEducationalDegrees { get; set; } = new List<PersonEducationalDegree>();
}