// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace General.Domain.Entities;

public partial class FileEntity
{
    public int Id { get; set; }

    public long? ObjectId { get; set; }

    public DateTime CreatedAt { get; set; }

    public int EntityTypeId { get; set; }

    public int FileId { get; set; }

    public virtual EntityType EntityType { get; set; }

    public virtual File File { get; set; }
}