// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace General.Domain.Entities;

public partial class File
{
    public int Id { get; set; }

    public string Guid { get; set; }

    public string File1 { get; set; }

    public long Filesize { get; set; }

    public string Name { get; set; }

    public string Sha1 { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<FileEntity> FileEntities { get; set; } = new List<FileEntity>();
}