// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace General.Domain.Entities;

public partial class PersonMobile
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Mobile { get; set; }

    public bool IsDefault { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int PersonId { get; set; }

    public virtual Person Person { get; set; }
}