// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace General.Domain.Entities;

public partial class PersonAddress
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Address { get; set; }

    public string PostalCode { get; set; }

    public bool IsDefault { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int CityId { get; set; }

    public int CountryId { get; set; }

    public int PersonId { get; set; }

    public int ProvinceId { get; set; }

    public virtual City City { get; set; }

    public virtual Country Country { get; set; }

    public virtual Person Person { get; set; }

    public virtual Province Province { get; set; }
}