// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace General.Domain.Entities;

public partial class User
{
    public int Id { get; set; }

    public string Password { get; set; }

    public string Username { get; set; }

    public string UsernameEncrypted { get; set; }

    public string Signature { get; set; }

    public bool IsSuperuser { get; set; }

    public bool IsStaff { get; set; }

    public bool IsReportViewer { get; set; }

    public bool IsActive { get; set; }

    public string AuthSendType { get; set; }

    public string ColorPallet { get; set; }

    public string FontFamily { get; set; }

    public double FontSize { get; set; }

    public bool NewTab { get; set; }

    public DateTime? LastLogin { get; set; }

    public string AccessToken { get; set; }

    public string RefreshToken { get; set; }

    public TimeOnly? AccessStartTime { get; set; }

    public TimeOnly? AccessEndTime { get; set; }

    public DateTime? ExpireDate { get; set; }

    public string AllowedIps { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public int LanguageId { get; set; }

    public int PersonId { get; set; }

    public virtual ICollection<Area> Areas { get; set; } = new List<Area>();

    [InverseProperty("Admin")]
    public virtual ICollection<CompanyAdmin> CompanyAdminAdmins { get; set; } = new List<CompanyAdmin>();

    [InverseProperty("Creator")]
    public virtual ICollection<CompanyAdmin> CompanyAdminCreators { get; set; } = new List<CompanyAdmin>();

    public virtual ICollection<EducationalDegree> EducationalDegrees { get; set; } = new List<EducationalDegree>();

    public virtual ICollection<EmploymentContractDescription> EmploymentContractDescriptions { get; set; } = new List<EmploymentContractDescription>();

    public virtual ICollection<EmploymentContractTitle> EmploymentContractTitles { get; set; } = new List<EmploymentContractTitle>();

    public virtual ICollection<ErrorLog> ErrorLogs { get; set; } = new List<ErrorLog>();

    public virtual ICollection<ForeignLanguage> ForeignLanguages { get; set; } = new List<ForeignLanguage>();

    public virtual ICollection<HousingStatus> HousingStatuses { get; set; } = new List<HousingStatus>();

    public virtual ICollection<JobPosition> JobPositions { get; set; } = new List<JobPosition>();

    public virtual ICollection<JobRank> JobRanks { get; set; } = new List<JobRank>();

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();

    public virtual Language Language { get; set; }

    public virtual ICollection<Log> Logs { get; set; } = new List<Log>();

    public virtual ICollection<MeasurementUnit> MeasurementUnits { get; set; } = new List<MeasurementUnit>();

    public virtual ICollection<MilitaryServiceStatus> MilitaryServiceStatuses { get; set; } = new List<MilitaryServiceStatus>();

    public virtual ICollection<MissionType> MissionTypes { get; set; } = new List<MissionType>();

    [InverseProperty("User2")]
    public virtual ICollection<Notification> NotificationUser2s { get; set; } = new List<Notification>();

    [InverseProperty("User")]
    public virtual ICollection<Notification> NotificationUsers { get; set; } = new List<Notification>();

    public virtual Person Person { get; set; }

    public virtual ICollection<PersonEducationalDegree> PersonEducationalDegrees { get; set; } = new List<PersonEducationalDegree>();

    public virtual ICollection<PersonRelative> PersonRelatives { get; set; } = new List<PersonRelative>();

    public virtual ICollection<Religion> Religions { get; set; } = new List<Religion>();

    public virtual ICollection<SelectLog> SelectLogs { get; set; } = new List<SelectLog>();

    public virtual ICollection<UserConfig> UserConfigs { get; set; } = new List<UserConfig>();

    public virtual ICollection<WorkDepartment> WorkDepartments { get; set; } = new List<WorkDepartment>();

    public virtual ICollection<WorkOperation> WorkOperations { get; set; } = new List<WorkOperation>();

    public virtual ICollection<Workplace> Workplaces { get; set; } = new List<Workplace>();
}