// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace General.Domain.Entities;

public partial class UserConfig
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Data { get; set; }

    public int ModuleId { get; set; }

    public int UserId { get; set; }

    public virtual Module Module { get; set; }

    public virtual User User { get; set; }
}