# .gitlab-ci.yml
workflow:
  rules:
    - if: '$CI_DISABLED == "true"'
      when: never
    - when: always

stages:
  - build
  - publish
 # - migrations
  - deploy

variables:
  SOLUTION_FILE: "NGErp.sln"
  API_PROJECT:   "Src/API/API/NGErp.API.csproj"
  MIGRATIONS_PROJECT: "Src/BaseModule/Base.Infrastructure/NGErp.Base.Infrastructure.csproj"
  PUBLISH_DIR:   "${CI_PROJECT_DIR}/publish"
  MIGRATIONS_BUNDLE: "${CI_PROJECT_DIR}/efbundle"
  DEPLOY_TARGET: "/home/emaco/www/dev-ngerp/backend-dotnet/"
  SERVICE_NAME:  "ngerp-dotnet.service"
  NUGET_SOURCE_RUNFLARE: "https://mirror-nuget.runflare.com/"
  NUGET_SOURCE_LIARA: "https://package-mirror.liara.ir/repository/nuget/index.json"

cache:
  key: "dotnet-${CI_COMMIT_REF_SLUG}"
  paths:
    - ~/.nuget/packages    

build:
  stage: build
  tags:
    - dotnet
    - ubuntu
    - deploy
  script:
    - dotnet restore "$SOLUTION_FILE" --source "$NUGET_SOURCE_RUNFLARE" --source "$NUGET_SOURCE_LIARA"
    - dotnet build   "$SOLUTION_FILE" --configuration Release --no-restore
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success

#create-migration-bundle:
#  stage: migrations
#  tags: [dotnet, ubuntu, deploy]
#  script:
#    - export NUGET_PACKAGES=/opt/nuget-packages
#    - dotnet ef migrations bundle
#        --project "$MIGRATIONS_PROJECT"
#        --startup-project "$API_PROJECT"
#        --configuration Release
#        --self-contained
#        --runtime linux-x64
#        --output "$MIGRATIONS_BUNDLE"
#        --verbose
#        --force
#        --context MainDbContext
#       --suppress-warnings
# artifacts:
#    paths:
#     - "$MIGRATIONS_BUNDLE"
#    expire_in: 7 days
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "main"'
#      when: on_success
#    - when: never

publish:
  stage: publish
  tags:
    - dotnet
    - ubuntu
    - deploy
  script:
    - dotnet publish "$API_PROJECT" --configuration Release --output "$PUBLISH_DIR" --source "$NUGET_SOURCE_RUNFLARE" --source "$NUGET_SOURCE_LIARA"
  artifacts:
    paths:
      - "$PUBLISH_DIR"
    expire_in: 7 days
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success

deploy:
  stage: deploy
  tags:
    - dotnet
    - ubuntu
    - deploy
  script:
#    chmod +x "$MIGRATIONS_BUNDLE"
#    - "$MIGRATIONS_BUNDLE" --connection "${DB_CONNECTION_STRING}" --verbose
    - sudo /usr/local/bin/deploy-ngerp.sh "$PUBLISH_DIR"
    - echo "Deployment done."
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
