// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse.Infrastructure.DataAccess;

#nullable disable

namespace Warehouse.Infrastructure.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    partial class WarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            //modelBuilder.Entity("Warehouse.Domain.Entities.Warehouse", b =>
            //    {
            //        b.Property<int>("Id")
            //            .ValueGeneratedOnAdd()
            //            .HasColumnType("int")
            //            .HasColumnName("Id");

            //        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            //        b.Property<string>("TypeCode")
            //            .IsRequired()
                     
            //            .HasColumnType("int")
            //            .HasColumnName("TypeCode");

            //        b.Property<string>("TypeName")
            //           .IsRequired()
            //           .HasMaxLength(100)
            //           .HasColumnType("nvarchar(100)")
            //           .HasColumnName("TypeName");

            //        b.HasKey("Id");

            //        b.ToTable("warehousetypes", "warehouse");
            //    });
#pragma warning restore 612, 618
        }
    }
}
