// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class AccountGroup
{
    public int Id { get; set; }

    public string Name { get; set; }

    public short Code { get; set; }

    public int CategoryId { get; set; }

    public virtual AccountCategory Category { get; set; }

    public virtual ICollection<SlaveAccount> SlaveAccounts { get; set; } = new List<SlaveAccount>();
}