// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class AccountSet
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int CompanyId { get; set; }

    public int LedgerId { get; set; }

    public virtual ICollection<AccountSetItem> AccountSetItems { get; set; } = new List<AccountSetItem>();

    public virtual Ledger Ledger { get; set; }
}