// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class AccountSetItem
{
    public int Id { get; set; }

    public int AccountSetId { get; set; }

    public int? MasterId { get; set; }

    public int? SlaveId { get; set; }

    public virtual AccountSet AccountSet { get; set; }

    public virtual MasterAccount Master { get; set; }

    public virtual SlaveAccount Slave { get; set; }
}