// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class ClosingPatternSlaveCompany
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public int? DefaultCashierPeriodId { get; set; }

    public int? DefaultCompanyUnitId { get; set; }

    public int? DefaultCurrencyId { get; set; }

    public int? DefaultPersonId { get; set; }

    public int? DefaultPettyCashierPeriodId { get; set; }

    public int? DefaultProjectId { get; set; }

    public int? DefaultResourceAndExpenditureId { get; set; }

    public int? DefaultStoreId { get; set; }

    public int LedgerId { get; set; }

    public int PeriodId { get; set; }

    public int SlaveCompanyId { get; set; }

    public virtual ResourceAndExpenditure DefaultResourceAndExpenditure { get; set; }

    public virtual Ledger Ledger { get; set; }

    public virtual Period Period { get; set; }

    public virtual SlaveAccountCompany SlaveCompany { get; set; }
}