// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class Contradiction
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public int BankAccountId { get; set; }

    public int CompanyId { get; set; }

    public int CreatorId { get; set; }

    public int DataImportId { get; set; }

    public int LedgerId { get; set; }

    public int PeriodId { get; set; }

    public virtual ICollection<ContradictionItem> ContradictionItems { get; set; } = new List<ContradictionItem>();

    public virtual DataImport DataImport { get; set; }

    public virtual Ledger Ledger { get; set; }

    public virtual Period Period { get; set; }
}