// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class FloatAccountType
{
    public int Id { get; set; }

    public bool IsStatic { get; set; }

    public string NameFa { get; set; }

    public string NameEn { get; set; }

    public short? VoucherItemFloatLevel { get; set; }

    public string Extra1Title { get; set; }

    public string Extra1Title2 { get; set; }

    public string Extra1Type { get; set; }

    public bool? Extra1Required { get; set; }

    public string Extra2Title { get; set; }

    public string Extra2Title2 { get; set; }

    public string Extra2Type { get; set; }

    public bool? Extra2Required { get; set; }

    public string Extra3Title { get; set; }

    public string Extra3Title2 { get; set; }

    public string Extra3Type { get; set; }

    public bool? Extra3Required { get; set; }

    public int? ParentId { get; set; }

    public virtual ICollection<FloatAccountType> InverseParent { get; set; } = new List<FloatAccountType>();

    public virtual ICollection<ManualFloatAccount> ManualFloatAccounts { get; set; } = new List<ManualFloatAccount>();

    public virtual FloatAccountType Parent { get; set; }

    public virtual ICollection<SlaveAccountCompany> SlaveAccountCompanyFloatType1s { get; set; } = new List<SlaveAccountCompany>();

    public virtual ICollection<SlaveAccountCompany> SlaveAccountCompanyFloatType2s { get; set; } = new List<SlaveAccountCompany>();

    public virtual ICollection<SlaveAccountCompany> SlaveAccountCompanyFloatType3s { get; set; } = new List<SlaveAccountCompany>();

    public virtual ICollection<SlaveAccountCompany> SlaveAccountCompanyFloatType4s { get; set; } = new List<SlaveAccountCompany>();

    public virtual ICollection<SlaveAccountCompany> SlaveAccountCompanyFloatType5s { get; set; } = new List<SlaveAccountCompany>();

    public virtual ICollection<SlaveAccountCompany> SlaveAccountCompanyFloatType6s { get; set; } = new List<SlaveAccountCompany>();

    public virtual ICollection<SlaveAccountCompany> SlaveAccountCompanyFloatType7s { get; set; } = new List<SlaveAccountCompany>();

    public virtual ICollection<SlaveAccountCompany> SlaveAccountCompanyFloatType8s { get; set; } = new List<SlaveAccountCompany>();
}