// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class LedgerPeriodCompany
{
    public int Id { get; set; }

    public string AuthorizedUsers { get; set; }

    public int CompanyId { get; set; }

    public int LedgerId { get; set; }

    public int? LedgerPeriodId { get; set; }

    public int PeriodId { get; set; }

    public virtual Ledger Ledger { get; set; }

    public virtual LedgerPeriod LedgerPeriod { get; set; }

    public virtual LedgerPeriodCompanySetting LedgerPeriodCompanySetting { get; set; }

    public virtual Period Period { get; set; }
}