// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class LedgerPeriod
{
    public int Id { get; set; }

    public int LedgerId { get; set; }

    public int PeriodId { get; set; }

    public virtual Ledger Ledger { get; set; }

    public virtual ICollection<LedgerPeriodCompany> LedgerPeriodCompanies { get; set; } = new List<LedgerPeriodCompany>();

    public virtual Period Period { get; set; }
}