// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class LedgerPeriodCompanySetting
{
    public int Id { get; set; }

    public string AuthorizedUsers { get; set; }

    public bool IsClosed { get; set; }

    public bool S1 { get; set; }

    public bool S2 { get; set; }

    public bool S3 { get; set; }

    public bool S4 { get; set; }

    public bool S5 { get; set; }

    public bool S6 { get; set; }

    public bool S7 { get; set; }

    public bool S8 { get; set; }

    public bool S9 { get; set; }

    public bool S10 { get; set; }

    public bool S11 { get; set; }

    public bool S12 { get; set; }

    public bool S13 { get; set; }

    public short? S14 { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int CompanyId { get; set; }

    public int LedgerId { get; set; }

    public int LedgerPeriodCompanyId { get; set; }

    public int PeriodId { get; set; }

    public virtual Ledger Ledger { get; set; }

    public virtual LedgerPeriodCompany LedgerPeriodCompany { get; set; }

    public virtual Period Period { get; set; }
}