// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class ManualFloatAccount
{
    public int Id { get; set; }

    public int Code { get; set; }

    public string Title { get; set; }

    public string Title2 { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string AuthorizedUsers { get; set; }

    public int CompanyId { get; set; }

    public int FloatAccountTypeId { get; set; }

    public int? ParentId { get; set; }

    public virtual ICollection<BalanceRelatedAccountDetail> BalanceRelatedAccountDetailManualFloat1s { get; set; } = new List<BalanceRelatedAccountDetail>();

    public virtual ICollection<BalanceRelatedAccountDetail> BalanceRelatedAccountDetailManualFloat2s { get; set; } = new List<BalanceRelatedAccountDetail>();

    public virtual ICollection<BalanceRelatedAccountDetail> BalanceRelatedAccountDetailManualFloat3s { get; set; } = new List<BalanceRelatedAccountDetail>();

    public virtual ICollection<BalanceRelatedAccountDetail> BalanceRelatedAccountDetailManualFloat4s { get; set; } = new List<BalanceRelatedAccountDetail>();

    public virtual ICollection<BalanceRelatedAccountDetail> BalanceRelatedAccountDetailManualFloat5s { get; set; } = new List<BalanceRelatedAccountDetail>();

    public virtual ICollection<BalanceRelatedAccountDetail> BalanceRelatedAccountDetailManualFloat6s { get; set; } = new List<BalanceRelatedAccountDetail>();

    public virtual ICollection<BalanceRelatedAccountDetail> BalanceRelatedAccountDetailManualFloat7s { get; set; } = new List<BalanceRelatedAccountDetail>();

    public virtual ICollection<BalanceRelatedAccountDetail> BalanceRelatedAccountDetailManualFloat8s { get; set; } = new List<BalanceRelatedAccountDetail>();

    public virtual FloatAccountType FloatAccountType { get; set; }

    public virtual ICollection<ManualFloatAccount> InverseParent { get; set; } = new List<ManualFloatAccount>();

    public virtual ManualFloatAccount Parent { get; set; }

    public virtual ICollection<TrashVoucherItem> TrashVoucherItemManualFloat1s { get; set; } = new List<TrashVoucherItem>();

    public virtual ICollection<TrashVoucherItem> TrashVoucherItemManualFloat2s { get; set; } = new List<TrashVoucherItem>();

    public virtual ICollection<TrashVoucherItem> TrashVoucherItemManualFloat3s { get; set; } = new List<TrashVoucherItem>();

    public virtual ICollection<TrashVoucherItem> TrashVoucherItemManualFloat4s { get; set; } = new List<TrashVoucherItem>();

    public virtual ICollection<TrashVoucherItem> TrashVoucherItemManualFloat5s { get; set; } = new List<TrashVoucherItem>();

    public virtual ICollection<TrashVoucherItem> TrashVoucherItemManualFloat6s { get; set; } = new List<TrashVoucherItem>();

    public virtual ICollection<TrashVoucherItem> TrashVoucherItemManualFloat7s { get; set; } = new List<TrashVoucherItem>();

    public virtual ICollection<TrashVoucherItem> TrashVoucherItemManualFloat8s { get; set; } = new List<TrashVoucherItem>();

    public virtual ICollection<VoucherItemLog> VoucherItemLogManualFloat1s { get; set; } = new List<VoucherItemLog>();

    public virtual ICollection<VoucherItemLog> VoucherItemLogManualFloat2s { get; set; } = new List<VoucherItemLog>();

    public virtual ICollection<VoucherItemLog> VoucherItemLogManualFloat3s { get; set; } = new List<VoucherItemLog>();

    public virtual ICollection<VoucherItemLog> VoucherItemLogManualFloat4s { get; set; } = new List<VoucherItemLog>();

    public virtual ICollection<VoucherItemLog> VoucherItemLogManualFloat5s { get; set; } = new List<VoucherItemLog>();

    public virtual ICollection<VoucherItemLog> VoucherItemLogManualFloat6s { get; set; } = new List<VoucherItemLog>();

    public virtual ICollection<VoucherItemLog> VoucherItemLogManualFloat7s { get; set; } = new List<VoucherItemLog>();

    public virtual ICollection<VoucherItemLog> VoucherItemLogManualFloat8s { get; set; } = new List<VoucherItemLog>();

    public virtual ICollection<VoucherItem> VoucherItemManualFloat1s { get; set; } = new List<VoucherItem>();

    public virtual ICollection<VoucherItem> VoucherItemManualFloat2s { get; set; } = new List<VoucherItem>();

    public virtual ICollection<VoucherItem> VoucherItemManualFloat3s { get; set; } = new List<VoucherItem>();

    public virtual ICollection<VoucherItem> VoucherItemManualFloat4s { get; set; } = new List<VoucherItem>();

    public virtual ICollection<VoucherItem> VoucherItemManualFloat5s { get; set; } = new List<VoucherItem>();

    public virtual ICollection<VoucherItem> VoucherItemManualFloat6s { get; set; } = new List<VoucherItem>();

    public virtual ICollection<VoucherItem> VoucherItemManualFloat7s { get; set; } = new List<VoucherItem>();

    public virtual ICollection<VoucherItem> VoucherItemManualFloat8s { get; set; } = new List<VoucherItem>();
}