// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class MasterAccount
{
    public int Id { get; set; }

    public int Code { get; set; }

    public string Title { get; set; }

    public string Title2 { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string AuthorizedUsers { get; set; }

    public int LedgerId { get; set; }

    public virtual ICollection<AccountSetItem> AccountSetItems { get; set; } = new List<AccountSetItem>();

    public virtual ICollection<BalanceRelatedAccountDetail> BalanceRelatedAccountDetails { get; set; } = new List<BalanceRelatedAccountDetail>();

    public virtual Ledger Ledger { get; set; }

    public virtual ICollection<SlaveAccountCompany> SlaveAccountCompanies { get; set; } = new List<SlaveAccountCompany>();

    public virtual ICollection<SlaveAccount> SlaveAccounts { get; set; } = new List<SlaveAccount>();

    public virtual ICollection<TrashVoucherItem> TrashVoucherItems { get; set; } = new List<TrashVoucherItem>();

    public virtual ICollection<VoucherItemLog> VoucherItemLogs { get; set; } = new List<VoucherItemLog>();

    public virtual ICollection<VoucherItem> VoucherItems { get; set; } = new List<VoucherItem>();
}