// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class Period
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? CompanyId { get; set; }

    public int? PreviousPeriodId { get; set; }

    public virtual ICollection<BalanceRelatedAccountDetail> BalanceRelatedAccountDetails { get; set; } = new List<BalanceRelatedAccountDetail>();

    public virtual ICollection<ClosingPatternSlaveCompany> ClosingPatternSlaveCompanies { get; set; } = new List<ClosingPatternSlaveCompany>();

    public virtual ICollection<ClosingPatternTemporaryAccount> ClosingPatternTemporaryAccounts { get; set; } = new List<ClosingPatternTemporaryAccount>();

    public virtual ICollection<ClosingPattern> ClosingPatterns { get; set; } = new List<ClosingPattern>();

    public virtual ICollection<Contradiction> Contradictions { get; set; } = new List<Contradiction>();

    public virtual ICollection<DataImport> DataImports { get; set; } = new List<DataImport>();

    public virtual ICollection<Period> InversePreviousPeriod { get; set; } = new List<Period>();

    public virtual ICollection<LedgerPeriodCompany> LedgerPeriodCompanies { get; set; } = new List<LedgerPeriodCompany>();

    public virtual ICollection<LedgerPeriodCompanySetting> LedgerPeriodCompanySettings { get; set; } = new List<LedgerPeriodCompanySetting>();

    public virtual ICollection<LedgerPeriod> LedgerPeriods { get; set; } = new List<LedgerPeriod>();

    public virtual Period PreviousPeriod { get; set; }

    public virtual ICollection<TrashVoucherItem> TrashVoucherItems { get; set; } = new List<TrashVoucherItem>();

    public virtual ICollection<TrashVoucher> TrashVouchers { get; set; } = new List<TrashVoucher>();

    public virtual ICollection<TtmsBuy> TtmsBuys { get; set; } = new List<TtmsBuy>();

    public virtual ICollection<TtmsContractorInfo> TtmsContractorInfos { get; set; } = new List<TtmsContractorInfo>();

    public virtual ICollection<TtmsEmployerInfo> TtmsEmployerInfos { get; set; } = new List<TtmsEmployerInfo>();

    public virtual ICollection<TtmsExportation> TtmsExportations { get; set; } = new List<TtmsExportation>();

    public virtual ICollection<TtmsImportation> TtmsImportations { get; set; } = new List<TtmsImportation>();

    public virtual ICollection<TtmsLeaseAgreement> TtmsLeaseAgreements { get; set; } = new List<TtmsLeaseAgreement>();

    public virtual ICollection<TtmsPreSell> TtmsPreSells { get; set; } = new List<TtmsPreSell>();

    public virtual ICollection<TtmsSell> TtmsSells { get; set; } = new List<TtmsSell>();

    public virtual ICollection<TtmsWage> TtmsWages { get; set; } = new List<TtmsWage>();

    public virtual ICollection<VoucherItemLog> VoucherItemLogs { get; set; } = new List<VoucherItemLog>();

    public virtual ICollection<VoucherItem> VoucherItems { get; set; } = new List<VoucherItem>();

    public virtual ICollection<VoucherLog> VoucherLogs { get; set; } = new List<VoucherLog>();

    public virtual ICollection<Voucher> Vouchers { get; set; } = new List<Voucher>();
}