// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class ResourceAndExpenditure
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Code { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string AuthorizedUsers { get; set; }

    public int CompanyId { get; set; }

    public virtual ICollection<BalanceRelatedAccountDetail> BalanceRelatedAccountDetails { get; set; } = new List<BalanceRelatedAccountDetail>();

    public virtual ICollection<ClosingPatternSlaveCompany> ClosingPatternSlaveCompanies { get; set; } = new List<ClosingPatternSlaveCompany>();

    public virtual ICollection<ClosingPatternTemporaryAccount> ClosingPatternTemporaryAccounts { get; set; } = new List<ClosingPatternTemporaryAccount>();

    public virtual ICollection<ClosingPattern> ClosingPatterns { get; set; } = new List<ClosingPattern>();

    public virtual ICollection<TrashVoucherItem> TrashVoucherItems { get; set; } = new List<TrashVoucherItem>();

    public virtual ICollection<VoucherItemLog> VoucherItemLogs { get; set; } = new List<VoucherItemLog>();

    public virtual ICollection<VoucherItem> VoucherItems { get; set; } = new List<VoucherItem>();
}