// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class Setting
{
    public int Id { get; set; }

    public bool S1 { get; set; }

    public int DomainId { get; set; }
}