// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class SlaveAccountCompany
{
    public int Id { get; set; }

    public bool NeedTtms { get; set; }

    public short? DealType { get; set; }

    public bool HasAbsoluteDealType { get; set; }

    public bool IsActive { get; set; }

    public double? Budget { get; set; }

    public string FloatTypes { get; set; }

    public string FloatTypeSet { get; set; }

    public bool DueDate { get; set; }

    public string Tag1 { get; set; }

    public string Tag2 { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string AuthorizedUsers { get; set; }

    public int CompanyId { get; set; }

    public int? FloatType1Id { get; set; }

    public int? FloatType2Id { get; set; }

    public int? FloatType3Id { get; set; }

    public int? FloatType4Id { get; set; }

    public int? FloatType5Id { get; set; }

    public int? FloatType6Id { get; set; }

    public int? FloatType7Id { get; set; }

    public int? FloatType8Id { get; set; }

    public int LedgerId { get; set; }

    public int MasterId { get; set; }

    public int SlaveId { get; set; }

    public virtual ICollection<ClosingPatternSlaveCompany> ClosingPatternSlaveCompanies { get; set; } = new List<ClosingPatternSlaveCompany>();

    public virtual FloatAccountType FloatType1 { get; set; }

    public virtual FloatAccountType FloatType2 { get; set; }

    public virtual FloatAccountType FloatType3 { get; set; }

    public virtual FloatAccountType FloatType4 { get; set; }

    public virtual FloatAccountType FloatType5 { get; set; }

    public virtual FloatAccountType FloatType6 { get; set; }

    public virtual FloatAccountType FloatType7 { get; set; }

    public virtual FloatAccountType FloatType8 { get; set; }

    public virtual Ledger Ledger { get; set; }

    public virtual MasterAccount Master { get; set; }

    public virtual SlaveAccount Slave { get; set; }

    public virtual ICollection<TrashVoucherItem> TrashVoucherItems { get; set; } = new List<TrashVoucherItem>();

    public virtual ICollection<VoucherItemLog> VoucherItemLogs { get; set; } = new List<VoucherItemLog>();

    public virtual ICollection<VoucherItem> VoucherItems { get; set; } = new List<VoucherItem>();
}