// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class SlaveAccount
{
    public int Id { get; set; }

    public string Type { get; set; }

    public string Nature { get; set; }

    public string ClosingType { get; set; }

    public int SlaveCode { get; set; }

    public int Code { get; set; }

    public short Level { get; set; }

    public bool LastLevel { get; set; }

    public int? DetailedAccount1 { get; set; }

    public int? DetailedAccount2 { get; set; }

    public string Title { get; set; }

    public string Title2 { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int CategoryId { get; set; }

    public int? FromCompanyId { get; set; }

    public int GroupId { get; set; }

    public int LedgerId { get; set; }

    public int MasterId { get; set; }

    public int? ParentId { get; set; }

    public virtual ICollection<AccountSetItem> AccountSetItems { get; set; } = new List<AccountSetItem>();

    public virtual ICollection<BalanceRelatedAccountDetail> BalanceRelatedAccountDetails { get; set; } = new List<BalanceRelatedAccountDetail>();

    public virtual AccountCategory Category { get; set; }

    public virtual AccountGroup Group { get; set; }

    public virtual ICollection<SlaveAccount> InverseParent { get; set; } = new List<SlaveAccount>();

    public virtual Ledger Ledger { get; set; }

    public virtual MasterAccount Master { get; set; }

    public virtual SlaveAccount Parent { get; set; }

    public virtual ICollection<SlaveAccountCompany> SlaveAccountCompanies { get; set; } = new List<SlaveAccountCompany>();

    public virtual ICollection<SlaveAccountStandardDescription> SlaveAccountStandardDescriptions { get; set; } = new List<SlaveAccountStandardDescription>();

    public virtual ICollection<TrashVoucherItem> TrashVoucherItems { get; set; } = new List<TrashVoucherItem>();

    public virtual ICollection<VoucherItemLog> VoucherItemLogs { get; set; } = new List<VoucherItemLog>();

    public virtual ICollection<VoucherItem> VoucherItems { get; set; } = new List<VoucherItem>();
}