// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class TrashVoucherItemAttach
{
    public int Id { get; set; }

    public string File { get; set; }

    public DateOnly CreatedAt { get; set; }

    public int TrashVoucherId { get; set; }

    public int TrashVoucherItemId { get; set; }

    public virtual TrashVoucher TrashVoucher { get; set; }

    public virtual TrashVoucherItem TrashVoucherItem { get; set; }
}