// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class TtmsBuy
{
    public int Id { get; set; }

    public bool Sarjam { get; set; }

    public bool IsHagholamalKari { get; set; }

    public string KalaKhadamatName { get; set; }

    public decimal? KalaCode { get; set; }

    public bool BargashtType { get; set; }

    public string Price { get; set; }

    public string MaliatArzeshAfzoodeh { get; set; }

    public string AvarezArzeshAfzoodeh { get; set; }

    public string SayerAvarez { get; set; }

    public string TakhfifPrice { get; set; }

    public string MaliatMaksoore { get; set; }

    public string ArzPrice { get; set; }

    public string ArzMaliatArzeshAfzoodeh { get; set; }

    public string ArzAvarezArzeshAfzoodeh { get; set; }

    public string ArzSayerAvarez { get; set; }

    public string ArzTakhfifPrice { get; set; }

    public string ArzMaliatMaksoore { get; set; }

    public decimal? ArzBarabariPrice { get; set; }

    public decimal? ArzBarabariTakhfifPrice { get; set; }

    public decimal? ArzBarabariMaliatArzeshAfzoodeh { get; set; }

    public decimal? ArzBarabariAvarezArzeshAfzoodeh { get; set; }

    public decimal? ArzBarabariSayerAvarez { get; set; }

    public decimal? ArzBarabariMaliatMaksoore { get; set; }

    public string MoadelRialiPrice { get; set; }

    public string MoadelRialiTakhfifPrice { get; set; }

    public string MoadelRialiMaliatArzeshAfzoodeh { get; set; }

    public string MoadelRialiAvarezArzeshAfzoodeh { get; set; }

    public string MoadelRialiSayerAvarez { get; set; }

    public string MoadelRialiMaliatMaksoore { get; set; }

    public string FactorNo { get; set; }

    public string FactorDate { get; set; }

    public short? DealCurrency { get; set; }

    public int? ArzTypeId { get; set; }

    public int CompanyId { get; set; }

    public int? ForoshandeId { get; set; }

    public int? ForoshandeAddressId { get; set; }

    public int? ForoshandePhoneId { get; set; }

    public int? KalaTypeId { get; set; }

    public int LedgerId { get; set; }

    public int PeriodId { get; set; }

    public int VoucherId { get; set; }

    public int VoucherItemId { get; set; }

    public virtual TtmsProductType KalaType { get; set; }

    public virtual Ledger Ledger { get; set; }

    public virtual Period Period { get; set; }

    public virtual Voucher Voucher { get; set; }

    public virtual VoucherItem VoucherItem { get; set; }
}