// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class TtmsImportation
{
    public int Id { get; set; }

    public short? KharidType { get; set; }

    public bool BargashtAzSaderat { get; set; }

    public short? HcForoushandeType1Code { get; set; }

    public decimal? KalaCode { get; set; }

    public string KalaKhadamatName { get; set; }

    public string Price { get; set; }

    public string PriceParvane { get; set; }

    public string MaliatArzeshAfzoodeh { get; set; }

    public string AvarezArzeshAfzoodeh { get; set; }

    public string SayerAvarez { get; set; }

    public string TakhfifPrice { get; set; }

    public string MaliatMaksoore { get; set; }

    public string ArzPrice { get; set; }

    public string ArzPriceParvane { get; set; }

    public string ArzMaliatArzeshAfzoodeh { get; set; }

    public string ArzAvarezArzeshAfzoodeh { get; set; }

    public string ArzSayerAvarez { get; set; }

    public string ArzTakhfifPrice { get; set; }

    public string ArzMaliatMaksoore { get; set; }

    public decimal? ArzBarabariPrice { get; set; }

    public decimal? ArzBarabariPriceParvane { get; set; }

    public decimal? ArzBarabariTakhfifPrice { get; set; }

    public decimal? ArzBarabariMaliatArzeshAfzoodeh { get; set; }

    public decimal? ArzBarabariAvarezArzeshAfzoodeh { get; set; }

    public decimal? ArzBarabariSayerAvarez { get; set; }

    public decimal? ArzBarabariMaliatMaksoore { get; set; }

    public string MoadelRialiPrice { get; set; }

    public string MoadelRialiPriceParvane { get; set; }

    public string MoadelRialiTakhfifPrice { get; set; }

    public string MoadelRialiMaliatArzeshAfzoodeh { get; set; }

    public string MoadelRialiAvarezArzeshAfzoodeh { get; set; }

    public string MoadelRialiSayerAvarez { get; set; }

    public string MoadelRialiMaliatMaksoore { get; set; }

    public int? KotajNo { get; set; }

    public string KotajDate { get; set; }

    public string LcNo { get; set; }

    public string LcDate { get; set; }

    public int? GomrokArzyabi { get; set; }

    public int? GomrokVorud { get; set; }

    public string FactorNo { get; set; }

    public string FactorDate { get; set; }

    public string Tozih { get; set; }

    public short? DealCurrency { get; set; }

    public int? ArzTypeId { get; set; }

    public int CompanyId { get; set; }

    public int? ForoshandeId { get; set; }

    public int? ForoshandeAddressId { get; set; }

    public int? ForoshandeCountryId { get; set; }

    public string KalaTypeId { get; set; }

    public int LedgerId { get; set; }

    public int PeriodId { get; set; }

    public int VoucherId { get; set; }

    public int VoucherItemId { get; set; }

    public virtual TtmsProductType KalaType { get; set; }

    public virtual Ledger Ledger { get; set; }

    public virtual Period Period { get; set; }

    public virtual Voucher Voucher { get; set; }

    public virtual VoucherItem VoucherItem { get; set; }
}