// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class TtmsProductType
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Code { get; set; }

    public virtual ICollection<TtmsBuy> TtmsBuys { get; set; } = new List<TtmsBuy>();

    public virtual ICollection<TtmsExportation> TtmsExportations { get; set; } = new List<TtmsExportation>();

    public virtual ICollection<TtmsImportation> TtmsImportations { get; set; } = new List<TtmsImportation>();

    public virtual ICollection<TtmsSell> TtmsSells { get; set; } = new List<TtmsSell>();

    public virtual ICollection<TtmsWage> TtmsWages { get; set; } = new List<TtmsWage>();
}