// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class TtmsWage
{
    public int Id { get; set; }

    public short? ReportType { get; set; }

    public short? DaryaftAz { get; set; }

    public bool Sarjam { get; set; }

    public bool BargashtType { get; set; }

    public short? SType1Code { get; set; }

    public short? KType1Code { get; set; }

    public string HNerkh { get; set; }

    public string HPrice { get; set; }

    public string HTakhfifPrice { get; set; }

    public string HMaliatArzeshAfzoodeh { get; set; }

    public string HAvarezArzeshAfzoodeh { get; set; }

    public string HSayerAvarez { get; set; }

    public string HArzPrice { get; set; }

    public string HArzTakhfifPrice { get; set; }

    public string HArzMaliatArzeshAfzoodeh { get; set; }

    public string HArzAvarezArzeshAfzoodeh { get; set; }

    public string HArzSayerAvarez { get; set; }

    public decimal? HArzBarabariPrice { get; set; }

    public decimal? HArzBarabariTakhfifPrice { get; set; }

    public decimal? HArzBarabariMaliatArzeshAfzoodeh { get; set; }

    public decimal? HArzBarabariAvarezArzeshAfzoodeh { get; set; }

    public decimal? HArzBarabariSayerAvarez { get; set; }

    public string HMoadelRialiPrice { get; set; }

    public string HMoadelRialiTakhfifPrice { get; set; }

    public string HMoadelRialiMaliatArzeshAfzoodeh { get; set; }

    public string HMoadelRialiAvarezArzeshAfzoodeh { get; set; }

    public string HMoadelRialiSayerAvarez { get; set; }

    public string HFactorNo { get; set; }

    public string HFactorDate { get; set; }

    public string KalaKhadamatName { get; set; }

    public decimal? KalaCode { get; set; }

    public string Price { get; set; }

    public string TakhfifPrice { get; set; }

    public string MaliatArzeshAfzoodeh { get; set; }

    public string AvarezArzeshAfzoodeh { get; set; }

    public string SayerAvarez { get; set; }

    public string ArzPrice { get; set; }

    public string ArzTakhfifPrice { get; set; }

    public string ArzMaliatArzeshAfzoodeh { get; set; }

    public string ArzAvarezArzeshAfzoodeh { get; set; }

    public string ArzSayerAvarez { get; set; }

    public decimal? ArzBarabariPrice { get; set; }

    public decimal? ArzBarabariTakhfifPrice { get; set; }

    public decimal? ArzBarabariMaliatArzeshAfzoodeh { get; set; }

    public decimal? ArzBarabariAvarezArzeshAfzoodeh { get; set; }

    public decimal? ArzBarabariSayerAvarez { get; set; }

    public string MoadelRialiPrice { get; set; }

    public string MoadelRialiTakhfifPrice { get; set; }

    public string MoadelRialiMaliatArzeshAfzoodeh { get; set; }

    public string MoadelRialiAvarezArzeshAfzoodeh { get; set; }

    public string MoadelRialiSayerAvarez { get; set; }

    public string FactorNo { get; set; }

    public string FactorDate { get; set; }

    public short? DealCurrency { get; set; }

    public int? ArzTypeId { get; set; }

    public int CompanyId { get; set; }

    public int? HArzTypeId { get; set; }

    public int? KalaTypeId { get; set; }

    public int? KharidarId { get; set; }

    public int? KharidarAddressId { get; set; }

    public int? KharidarPhoneId { get; set; }

    public int LedgerId { get; set; }

    public int PeriodId { get; set; }

    public int? SellerId { get; set; }

    public int? SellerAddressId { get; set; }

    public int? SellerPhoneId { get; set; }

    public int VoucherId { get; set; }

    public int VoucherItemId { get; set; }

    public virtual TtmsProductType KalaType { get; set; }

    public virtual Ledger Ledger { get; set; }

    public virtual Period Period { get; set; }

    public virtual Voucher Voucher { get; set; }

    public virtual VoucherItem VoucherItem { get; set; }
}