// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class TtmsPreSell
{
    public int Id { get; set; }

    public short? TarafeGharardadType { get; set; }

    public short? GharardadTypeCode { get; set; }

    public short? KarbariType { get; set; }

    public string Tozih { get; set; }

    public string MelkAddress { get; set; }

    public string PelakSabti { get; set; }

    public bool BargashtType { get; set; }

    public string PardakhtDate { get; set; }

    public string TozihatPardakht { get; set; }

    public string Price { get; set; }

    public string ArzPrice { get; set; }

    public string ArzBarabariPrice { get; set; }

    public string MoadelRialiPrice { get; set; }

    public short? DealCurrency { get; set; }

    public int? ArzTypeId { get; set; }

    public int CompanyId { get; set; }

    public int? GharardadId { get; set; }

    public int LedgerId { get; set; }

    public int? MelkCityId { get; set; }

    public int? MelkStateId { get; set; }

    public int PeriodId { get; set; }

    public int? TAddressId { get; set; }

    public int? TPhoneId { get; set; }

    public int? TarafeGharardadId { get; set; }

    public int VoucherId { get; set; }

    public int VoucherItemId { get; set; }

    public virtual Ledger Ledger { get; set; }

    public virtual Period Period { get; set; }

    public virtual Voucher Voucher { get; set; }

    public virtual VoucherItem VoucherItem { get; set; }
}