// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class TtmsEmployerInfo
{
    public int Id { get; set; }

    public short? ReportType { get; set; }

    public bool BargashtType { get; set; }

    public string TotalPrice { get; set; }

    public string SuratVaziatNumber { get; set; }

    public string SuratVaziatDate { get; set; }

    public string DaryaftDate { get; set; }

    public string Nakhales { get; set; }

    public string KhalesPrice { get; set; }

    public string MaliatMaksooreh { get; set; }

    public string MaliatArzeshAfzoodeh { get; set; }

    public string AvarezArzeshAfzoodeh { get; set; }

    public string SayerAvarez { get; set; }

    public string ArzTotalPrice { get; set; }

    public string ArzNakhales { get; set; }

    public string ArzKhales { get; set; }

    public string ArzMaliatMaksooreh { get; set; }

    public string ArzMaliatArzeshAfzoodeh { get; set; }

    public string ArzAvarezArzeshAfzoodeh { get; set; }

    public string ArzSayerAvarez { get; set; }

    public decimal? ArzBarabariNakhales { get; set; }

    public decimal? ArzBarabariKhales { get; set; }

    public decimal? ArzBarabariMaliatMaksooreh { get; set; }

    public decimal? ArzBarabariMaliatArzeshAfzoodeh { get; set; }

    public decimal? ArzBarabariAvarezArzeshAfzoodeh { get; set; }

    public decimal? ArzBarabariSayerAvarez { get; set; }

    public short? GharardadActivityTypeCode { get; set; }

    public string MoadelRialiNakhales { get; set; }

    public string MoadelRialiMaksooreh { get; set; }

    public string MoadelRialiKhales { get; set; }

    public string MoadelRialiMaliatArzeshAfzoodeh { get; set; }

    public string MoadelRialiAvarezArzeshAfzoodeh { get; set; }

    public string MoadelRialiSayerAvarez { get; set; }

    public short? DealCurrency { get; set; }

    public int? ArzTypeId { get; set; }

    public int CompanyId { get; set; }

    public int? GharardadId { get; set; }

    public int? KarfarmaId { get; set; }

    public int? KarfarmaAddressId { get; set; }

    public int? KarfarmaPhoneId { get; set; }

    public int LedgerId { get; set; }

    public int PeriodId { get; set; }

    public int VoucherId { get; set; }

    public int VoucherItemId { get; set; }

    public virtual Ledger Ledger { get; set; }

    public virtual Period Period { get; set; }

    public virtual Voucher Voucher { get; set; }

    public virtual VoucherItem VoucherItem { get; set; }
}