// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class VoucherLog
{
    public int Id { get; set; }

    public int? VoucherIdInitial { get; set; }

    public string Typ { get; set; }

    public string Reason { get; set; }

    public long? Serial { get; set; }

    public long? Number { get; set; }

    public long? OldNumber { get; set; }

    public DateOnly? Date { get; set; }

    public DateOnly? OldDate { get; set; }

    public string Status { get; set; }

    public string OldStatus { get; set; }

    public string Description { get; set; }

    public string OldDescription { get; set; }

    public string Data { get; set; }

    public string Attaches { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? BranchId { get; set; }

    public int CompanyId { get; set; }

    public int LedgerId { get; set; }

    public int ModifierId { get; set; }

    public int? OldBranchId { get; set; }

    public int? OldVoucherTypeId { get; set; }

    public int PeriodId { get; set; }

    public int? VoucherId { get; set; }

    public int? VoucherTypeId { get; set; }

    public virtual Ledger Ledger { get; set; }

    public virtual VoucherType OldVoucherType { get; set; }

    public virtual Period Period { get; set; }

    public virtual Voucher Voucher { get; set; }

    public virtual ICollection<VoucherItemLog> VoucherItemLogs { get; set; } = new List<VoucherItemLog>();

    public virtual VoucherType VoucherType { get; set; }
}