// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class VoucherType
{
    public int Id { get; set; }

    public bool IsStatic { get; set; }

    public string NameFa { get; set; }

    public string NameEn { get; set; }

    public string Description { get; set; }

    public virtual ICollection<TrashVoucher> TrashVouchers { get; set; } = new List<TrashVoucher>();

    public virtual ICollection<VoucherLog> VoucherLogOldVoucherTypes { get; set; } = new List<VoucherLog>();

    public virtual ICollection<VoucherLog> VoucherLogVoucherTypes { get; set; } = new List<VoucherLog>();

    public virtual ICollection<Voucher> Vouchers { get; set; } = new List<Voucher>();
}