// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting.Domain.Entities;

public partial class VoucherItemAttach
{
    public int Id { get; set; }

    public string File { get; set; }

    public DateOnly CreatedAt { get; set; }

    public int VoucherId { get; set; }

    public int VoucherItemId { get; set; }

    public virtual Voucher Voucher { get; set; }

    public virtual VoucherItem VoucherItem { get; set; }
}