// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse.Infrastructure.DataAccess;

#nullable disable

namespace Warehouse.Infrastructure.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20250917072548_CreateProductHierarchy")]
    partial class CreateProductHierarchy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Domain.Entities.ProductCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FifthLevelCode")
                        .HasColumnType("int");

                    b.Property<string>("FifthLevelName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("FifthNextLevel")
                        .HasColumnType("bit");

                    b.Property<int>("FirstLevelCode")
                        .HasColumnType("int");

                    b.Property<string>("FirstLevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FourthLevelCode")
                        .HasColumnType("int");

                    b.Property<string>("FourthLevelName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("FourthNextLevel")
                        .HasColumnType("bit");

                    b.Property<int>("SecondLevelCode")
                        .HasColumnType("int");

                    b.Property<string>("SecondLevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SeventhLevelCode")
                        .HasColumnType("int");

                    b.Property<string>("SeventhLevelName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("SeventhNextLevel")
                        .HasColumnType("bit");

                    b.Property<int?>("SixthLevelCode")
                        .HasColumnType("int");

                    b.Property<string>("SixthLevelName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("SixthNextLevel")
                        .HasColumnType("bit");

                    b.Property<int?>("ThirdLevelCode")
                        .HasColumnType("int");

                    b.Property<string>("ThirdLevelName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("ThirdNextLevel")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ProductCodes", "Warehouse");
                });

            modelBuilder.Entity("Warehouse.Domain.Entities.ProductHierarchy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("FifthLevelSize")
                        .HasColumnType("tinyint");

                    b.Property<string>("FifthLevelType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte>("FirstLevelSize")
                        .HasColumnType("tinyint");

                    b.Property<string>("FirstLevelType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte?>("FourthLevelSize")
                        .HasColumnType("tinyint");

                    b.Property<string>("FourthLevelType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte>("SecondLevelSize")
                        .HasColumnType("tinyint");

                    b.Property<string>("SecondLevelType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte?>("SixthLevelSize")
                        .HasColumnType("tinyint");

                    b.Property<string>("SixthLevelType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte?>("ThirdLevelSize")
                        .HasColumnType("tinyint");

                    b.Property<string>("ThirdLevelType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("ProductHierarchies", "Warehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
