// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class BankStatementPatternConfiguration : IEntityTypeConfiguration<BankStatementPattern>
    {
        public void Configure(EntityTypeBuilder<BankStatementPattern> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__bank_sta__3213E83F9F2ED696");

            entity.ToTable("bank_statement_patterns", "general");

            entity.HasIndex(e => e.BankId, "UQ__bank_sta__4076F70269DE7D7F").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.BankId).HasColumnName("bank_id");
            entity.Property(e => e.ColumnChequeDate)
                .IsRequired()
                .HasMaxLength(1)
                .HasColumnName("column_cheque_date");
            entity.Property(e => e.ColumnChequeNo)
                .IsRequired()
                .HasMaxLength(1)
                .HasColumnName("column_cheque_no");
            entity.Property(e => e.ColumnCredit)
                .IsRequired()
                .HasMaxLength(1)
                .HasColumnName("column_credit");
            entity.Property(e => e.ColumnDebit)
                .IsRequired()
                .HasMaxLength(1)
                .HasColumnName("column_debit");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.FirstRowNo).HasColumnName("first_row_no");
            entity.Property(e => e.IgnoreLatestRows).HasColumnName("ignore_latest_rows");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.Bank).WithOne(p => p.BankStatementPattern)
                .HasForeignKey<BankStatementPattern>(d => d.BankId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("bank_statement_patterns_bank_id_85d1bd4e_fk_banks_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BankStatementPattern> entity);
    }
}
