// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class BankAccountTypeConfiguration : IEntityTypeConfiguration<BankAccountType>
    {
        public void Configure(EntityTypeBuilder<BankAccountType> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__bank_acc__3213E83F1A2A955F");

            entity.ToTable("bank_account_types", "general");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.HasChequeBook).HasColumnName("has_cheque_book");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BankAccountType> entity);
    }
}
