// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class CityConfiguration : IEntityTypeConfiguration<City>
    {
        public void Configure(EntityTypeBuilder<City> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__cities__3213E83F6830DF8F");

            entity.ToTable("cities", "general");

            entity.HasIndex(e => e.Code, "UQ__cities__357D4CF991D1106C").IsUnique();

            entity.HasIndex(e => e.Code2, "cities_code2_fc22c31a_uniq")
                .IsUnique()
                .HasFilter("([code2] IS NOT NULL)");

            entity.HasIndex(e => e.Code3, "cities_code3_cfe7131c_uniq")
                .IsUnique()
                .HasFilter("([code3] IS NOT NULL)");

            entity.HasIndex(e => e.ProvinceId, "cities_province_id_799ae9a0");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.Code2).HasColumnName("code2");
            entity.Property(e => e.Code3).HasColumnName("code3");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.ProvinceId).HasColumnName("province_id");

            entity.HasOne(d => d.Province).WithMany(p => p.Cities)
                .HasForeignKey(d => d.ProvinceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("cities_province_id_799ae9a0_fk_provinces_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<City> entity);
    }
}
