// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class CompanyModuleConfiguration : IEntityTypeConfiguration<CompanyModule>
    {
        public void Configure(EntityTypeBuilder<CompanyModule> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__company___3213E83F5A305B17");

            entity.ToTable("company_modules", "general");

            entity.HasIndex(e => e.CompanyId, "company_modules_company_id_98c248b4");

            entity.HasIndex(e => new { e.CompanyId, e.ModuleId }, "company_modules_company_id_module_id_2dc7a72c_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [module_id] IS NOT NULL)");

            entity.HasIndex(e => e.ModuleId, "company_modules_module_id_85bfd47f");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");

            entity.HasOne(d => d.Company).WithMany(p => p.CompanyModules)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("company_modules_company_id_98c248b4_fk_companies_id");

            entity.HasOne(d => d.Module).WithMany(p => p.CompanyModules)
                .HasForeignKey(d => d.ModuleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("company_modules_module_id_85bfd47f_fk_modules_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CompanyModule> entity);
    }
}
