// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__countrie__3213E83FA8F8A627");

            entity.ToTable("countries", "general");

            entity.HasIndex(e => e.Code, "UQ__countrie__357D4CF992BD5944").IsUnique();

            entity.HasIndex(e => e.Name, "UQ__countrie__72E12F1B07ACC871").IsUnique();

            entity.HasIndex(e => e.CurrencyId, "countries_currency_id_3d87434c");

            entity.HasIndex(e => e.TaxCode, "countries_tax_code_99e2105c_uniq")
                .IsUnique()
                .HasFilter("([tax_code] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.CurrencyId).HasColumnName("currency_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.TaxCode).HasColumnName("tax_code");

            entity.HasOne(d => d.Currency).WithMany(p => p.Countries)
                .HasForeignKey(d => d.CurrencyId)
                .HasConstraintName("countries_currency_id_3d87434c_fk_currencies_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Country> entity);
    }
}
