// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class DomainConfiguration : IEntityTypeConfiguration<General.Domain.Entities.Domain>
    {
        public void Configure(EntityTypeBuilder<General.Domain.Entities.Domain> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__domains__3213E83FF0E52661");

            entity.ToTable("domains", "general");

            entity.HasIndex(e => e.Hostname, "UQ__domains__DA92E433B526F86E").IsUnique();

            entity.HasIndex(e => e.LanguageId, "domains_language_id_a7140b25");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ApiKey)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("api_key");
            entity.Property(e => e.AuthMethod)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("auth_method");
            entity.Property(e => e.AuthSendType)
                .HasMaxLength(12)
                .HasColumnName("auth_send_type");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.Holding)
                .HasMaxLength(100)
                .HasColumnName("holding");
            entity.Property(e => e.Hostname)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("hostname");
            entity.Property(e => e.LanguageId).HasColumnName("language_id");
            entity.Property(e => e.PasswordLevel)
                .IsRequired()
                .HasMaxLength(7)
                .HasColumnName("password_level");
            entity.Property(e => e.TemplateName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("template_name");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.Language).WithMany(p => p.Domains)
                .HasForeignKey(d => d.LanguageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("domains_language_id_a7140b25_fk_languages_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<General.Domain.Entities.Domain> entity);
    }
}
