// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class EmploymentContractDescriptionConfiguration : IEntityTypeConfiguration<EmploymentContractDescription>
    {
        public void Configure(EntityTypeBuilder<EmploymentContractDescription> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__employme__3213E83FDDA602DA");

            entity.ToTable("employment_contract_Descriptions", "general");

            entity.HasIndex(e => e.CreatorId, "employment_contract_Descriptions_creator_id_2fcb5dd9");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("name");

            entity.HasOne(d => d.Creator).WithMany(p => p.EmploymentContractDescriptions)
                .HasForeignKey(d => d.CreatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("employment_contract_Descriptions_creator_id_2fcb5dd9_fk_users_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmploymentContractDescription> entity);
    }
}
