// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class EntityTypeCommandConfiguration : IEntityTypeConfiguration<EntityTypeCommand>
    {
        public void Configure(EntityTypeBuilder<EntityTypeCommand> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__entity_t__3213E83FCFCBD04F");

            entity.ToTable("entity_type_commands", "general");

            entity.HasIndex(e => e.EntityTypeId, "entity_type_commands_entity_type_id_c94a0ef5");

            entity.HasIndex(e => new { e.EntityTypeId, e.Key }, "entity_type_commands_entity_type_id_key_0d06ffe6_uniq")
                .IsUnique()
                .HasFilter("([entity_type_id] IS NOT NULL AND [key] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.EntityTypeId).HasColumnName("entity_type_id");
            entity.Property(e => e.Key)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("key");
            entity.Property(e => e.NameEn)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name_en");
            entity.Property(e => e.NameFa)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name_fa");
            entity.Property(e => e.Ordering).HasColumnName("ordering");
            entity.Property(e => e.Permissible).HasColumnName("permissible");

            entity.HasOne(d => d.EntityType).WithMany(p => p.EntityTypeCommands)
                .HasForeignKey(d => d.EntityTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("entity_type_commands_entity_type_id_c94a0ef5_fk_entity_types_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EntityTypeCommand> entity);
    }
}
