// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class EntityTypeConfiguration : IEntityTypeConfiguration<EntityType>
    {
        public void Configure(EntityTypeBuilder<EntityType> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__entity_t__3213E83F53BACB44");

            entity.ToTable("entity_types", "general");

            entity.HasIndex(e => e.ContentTypeId, "entity_types_content_type_id_b7d4130b");

            entity.HasIndex(e => e.ModuleId, "entity_types_module_id_55d1da29");

            entity.HasIndex(e => new { e.ModuleId, e.Key }, "entity_types_module_id_key_8a42bbcf_uniq")
                .IsUnique()
                .HasFilter("([module_id] IS NOT NULL AND [key] IS NOT NULL)");

            entity.HasIndex(e => new { e.ModuleId, e.NameEn }, "entity_types_module_id_name_en_2858063b_uniq")
                .IsUnique()
                .HasFilter("([module_id] IS NOT NULL AND [name_en] IS NOT NULL)");

            entity.HasIndex(e => new { e.ModuleId, e.NameFa }, "entity_types_module_id_name_fa_060eefd9_uniq")
                .IsUnique()
                .HasFilter("([module_id] IS NOT NULL AND [name_fa] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ContentTypeId).HasColumnName("content_type_id");
            entity.Property(e => e.Creatable).HasColumnName("creatable");
            entity.Property(e => e.Deletable).HasColumnName("deletable");
            entity.Property(e => e.Editable).HasColumnName("editable");
            entity.Property(e => e.Exportable).HasColumnName("exportable");
            entity.Property(e => e.HasConstraint).HasColumnName("has_constraint");
            entity.Property(e => e.HasRestriction).HasColumnName("has_restriction");
            entity.Property(e => e.IfNotCreator).HasColumnName("if_not_creator");
            entity.Property(e => e.Importable).HasColumnName("importable");
            entity.Property(e => e.Key)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("key");
            entity.Property(e => e.Loggable).HasColumnName("loggable");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.NameEn)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name_en");
            entity.Property(e => e.NameFa)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name_fa");
            entity.Property(e => e.Permissible).HasColumnName("permissible");
            entity.Property(e => e.Printable).HasColumnName("printable");
            entity.Property(e => e.Readable).HasColumnName("readable");

            entity.HasOne(d => d.Module).WithMany(p => p.EntityTypes)
                .HasForeignKey(d => d.ModuleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("entity_types_module_id_55d1da29_fk_modules_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EntityType> entity);
    }
}
