// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class EntityTypeConstraintConfiguration : IEntityTypeConfiguration<EntityTypeConstraint>
    {
        public void Configure(EntityTypeBuilder<EntityTypeConstraint> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__entity_t__3213E83FF883D863");

            entity.ToTable("entity_type_constraints", "general");

            entity.HasIndex(e => e.EntityTypeId, "entity_type_constraints_entity_type_id_a7b4c730");

            entity.HasIndex(e => new { e.EntityTypeId, e.FieldName }, "entity_type_constraints_entity_type_id_field_name_b4ec14c6_uniq")
                .IsUnique()
                .HasFilter("([entity_type_id] IS NOT NULL AND [field_name] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Creatable).HasColumnName("creatable");
            entity.Property(e => e.Editable).HasColumnName("editable");
            entity.Property(e => e.EntityTypeId).HasColumnName("entity_type_id");
            entity.Property(e => e.Exportable).HasColumnName("exportable");
            entity.Property(e => e.FieldName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("field_name");
            entity.Property(e => e.Importable).HasColumnName("importable");
            entity.Property(e => e.NameEn)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name_en");
            entity.Property(e => e.NameFa)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name_fa");
            entity.Property(e => e.Ordering).HasColumnName("ordering");
            entity.Property(e => e.Printable).HasColumnName("printable");
            entity.Property(e => e.Readable).HasColumnName("readable");

            entity.HasOne(d => d.EntityType).WithMany(p => p.EntityTypeConstraints)
                .HasForeignKey(d => d.EntityTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("entity_type_constraints_entity_type_id_a7b4c730_fk_entity_types_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EntityTypeConstraint> entity);
    }
}
