// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class ErrorLogConfiguration : IEntityTypeConfiguration<ErrorLog>
    {
        public void Configure(EntityTypeBuilder<ErrorLog> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__error_lo__3213E83F9EC25649");

            entity.ToTable("error_logs", "general");

            entity.HasIndex(e => e.UserId, "error_logs_user_id_ac744206");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.CurlCommand).HasColumnName("curl_command");
            entity.Property(e => e.ErrorMessage)
                .IsRequired()
                .HasColumnName("error_message");
            entity.Property(e => e.Extra).HasColumnName("extra");
            entity.Property(e => e.Method)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("method");
            entity.Property(e => e.Path)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("path");
            entity.Property(e => e.StatusCode).HasColumnName("status_code");
            entity.Property(e => e.Timestamp).HasColumnName("timestamp");
            entity.Property(e => e.Traceback).HasColumnName("traceback");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.ErrorLogs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("error_logs_user_id_ac744206_fk_users_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ErrorLog> entity);
    }
}
