// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class FileConfiguration : IEntityTypeConfiguration<General.Domain.Entities.File>
    {
        public void Configure(EntityTypeBuilder<General.Domain.Entities.File> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__files__3213E83F6974DD91");

            entity.ToTable("files", "general");

            entity.HasIndex(e => e.Sha1, "UQ__files__2FC437B2639CC3A2").IsUnique();

            entity.HasIndex(e => e.Guid, "UQ__files__497F6CB5C8798DFD").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.File1)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("file");
            entity.Property(e => e.Filesize).HasColumnName("filesize");
            entity.Property(e => e.Guid)
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnName("guid");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.Sha1)
                .IsRequired()
                .HasMaxLength(42)
                .HasColumnName("sha1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<General.Domain.Entities.File> entity);
    }
}
