// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class JobPositionConfiguration : IEntityTypeConfiguration<JobPosition>
    {
        public void Configure(EntityTypeBuilder<JobPosition> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__job_posi__3213E83FC70FA7E0");

            entity.ToTable("job_positions", "general");

            entity.HasIndex(e => e.Name, "UQ__job_posi__72E12F1B0D466C43").IsUnique();

            entity.HasIndex(e => e.CreatorId, "job_positions_creator_id_361c185c");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnName("name");

            entity.HasOne(d => d.Creator).WithMany(p => p.JobPositions)
                .HasForeignKey(d => d.CreatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("job_positions_creator_id_361c185c_fk_users_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<JobPosition> entity);
    }
}
