// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class LanguageConfiguration : IEntityTypeConfiguration<Language>
    {
        public void Configure(EntityTypeBuilder<Language> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__language__3213E83F82D76FFA");

            entity.ToTable("languages", "general");

            entity.HasIndex(e => e.Code, "UQ__language__357D4CF9757EF7F8").IsUnique();

            entity.HasIndex(e => e.Name, "UQ__language__72E12F1BD0EA1B2E").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(2)
                .HasColumnName("code");
            entity.Property(e => e.Direction)
                .IsRequired()
                .HasMaxLength(3)
                .HasColumnName("direction");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Language> entity);
    }
}
