// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class LogConfiguration : IEntityTypeConfiguration<Log>
    {
        public void Configure(EntityTypeBuilder<Log> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__logs__3213E83FB734E2C5");

            entity.ToTable("logs", "general");

            entity.HasIndex(e => e.CompanyId, "logs_company_id_ed2c29a1");

            entity.HasIndex(e => e.EntityTypeId, "logs_entity_type_id_87a8fbba");

            entity.HasIndex(e => e.ModuleId, "logs_module_id_c6447665");

            entity.HasIndex(e => e.PeriodId, "logs_period_id_ea07e698");

            entity.HasIndex(e => e.UserId, "logs_user_id_237f5f83");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(6)
                .HasColumnName("action");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.Data).HasColumnName("data");
            entity.Property(e => e.EntityTypeId).HasColumnName("entity_type_id");
            entity.Property(e => e.Ip)
                .IsRequired()
                .HasMaxLength(39)
                .HasColumnName("ip");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.ObjectId).HasColumnName("object_id");
            entity.Property(e => e.ObjectRepr)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("object_repr");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Company).WithMany(p => p.Logs)
                .HasForeignKey(d => d.CompanyId)
                .HasConstraintName("logs_company_id_ed2c29a1_fk_companies_id");

            entity.HasOne(d => d.EntityType).WithMany(p => p.Logs)
                .HasForeignKey(d => d.EntityTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("logs_entity_type_id_87a8fbba_fk_entity_types_id");

            entity.HasOne(d => d.Module).WithMany(p => p.Logs)
                .HasForeignKey(d => d.ModuleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("logs_module_id_c6447665_fk_modules_id");

            entity.HasOne(d => d.User).WithMany(p => p.Logs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("logs_user_id_237f5f83_fk_users_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Log> entity);
    }
}
