// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class MilitaryServiceStatusConfiguration : IEntityTypeConfiguration<MilitaryServiceStatus>
    {
        public void Configure(EntityTypeBuilder<MilitaryServiceStatus> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__military__3213E83F50066676");

            entity.ToTable("military_service_statuses", "general");

            entity.HasIndex(e => e.Name, "UQ__military__72E12F1B10BA3724").IsUnique();

            entity.HasIndex(e => e.CreatorId, "military_service_statuses_creator_id_2264fea4");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");

            entity.HasOne(d => d.Creator).WithMany(p => p.MilitaryServiceStatuses)
                .HasForeignKey(d => d.CreatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("military_service_statuses_creator_id_2264fea4_fk_users_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MilitaryServiceStatus> entity);
    }
}
