// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class MissionTypeConfiguration : IEntityTypeConfiguration<MissionType>
    {
        public void Configure(EntityTypeBuilder<MissionType> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__mission___3213E83FFEB65382");

            entity.ToTable("mission_types", "general");

            entity.HasIndex(e => e.Name, "UQ__mission___72E12F1BF6C8C347").IsUnique();

            entity.HasIndex(e => e.CreatorId, "mission_types_creator_id_17915c73");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.FixedAmount)
                .HasColumnType("numeric(18, 2)")
                .HasColumnName("fixed_amount");
            entity.Property(e => e.Formula)
                .HasMaxLength(300)
                .HasColumnName("formula");
            entity.Property(e => e.HasFormula).HasColumnName("has_formula");
            entity.Property(e => e.IsDefault).HasColumnName("is_default");
            entity.Property(e => e.IsHourly).HasColumnName("is_hourly");
            entity.Property(e => e.Multiplier)
                .HasColumnType("numeric(5, 2)")
                .HasColumnName("multiplier");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ParametricCustomFormula)
                .HasMaxLength(300)
                .HasColumnName("parametric_custom_formula");

            entity.HasOne(d => d.Creator).WithMany(p => p.MissionTypes)
                .HasForeignKey(d => d.CreatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("mission_types_creator_id_17915c73_fk_users_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MissionType> entity);
    }
}
