// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class PersonAddressConfiguration : IEntityTypeConfiguration<PersonAddress>
    {
        public void Configure(EntityTypeBuilder<PersonAddress> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__person_a__3213E83FE16C68D2");

            entity.ToTable("person_addresses", "general");

            entity.HasIndex(e => e.CityId, "person_addresses_city_id_bda2a750");

            entity.HasIndex(e => e.CountryId, "person_addresses_country_id_1fb41b6e");

            entity.HasIndex(e => new { e.PersonId, e.CityId, e.Address }, "person_addresses_person_id_city_id_address_74e8c5b2_uniq")
                .IsUnique()
                .HasFilter("([person_id] IS NOT NULL AND [city_id] IS NOT NULL AND [address] IS NOT NULL)");

            entity.HasIndex(e => e.PersonId, "person_addresses_person_id_d67d7fc6");

            entity.HasIndex(e => e.ProvinceId, "person_addresses_province_id_6ed2a37d");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnName("address");
            entity.Property(e => e.CityId).HasColumnName("city_id");
            entity.Property(e => e.CountryId).HasColumnName("country_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.IsDefault).HasColumnName("is_default");
            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.PostalCode)
                .HasMaxLength(10)
                .HasColumnName("postal_code");
            entity.Property(e => e.ProvinceId).HasColumnName("province_id");
            entity.Property(e => e.Title)
                .HasMaxLength(50)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.City).WithMany(p => p.PersonAddresses)
                .HasForeignKey(d => d.CityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_addresses_city_id_bda2a750_fk_cities_id");

            entity.HasOne(d => d.Country).WithMany(p => p.PersonAddresses)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_addresses_country_id_1fb41b6e_fk_countries_id");

            entity.HasOne(d => d.Person).WithMany(p => p.PersonAddresses)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_addresses_person_id_d67d7fc6_fk_persons_id");

            entity.HasOne(d => d.Province).WithMany(p => p.PersonAddresses)
                .HasForeignKey(d => d.ProvinceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_addresses_province_id_6ed2a37d_fk_provinces_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonAddress> entity);
    }
}
