// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class PersonConfiguration : IEntityTypeConfiguration<Person>
    {
        public void Configure(EntityTypeBuilder<Person> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__persons__3213E83FA537E099");

            entity.ToTable("persons", "general");

            entity.HasIndex(e => e.Code, "UQ__persons__357D4CF9A4AE2BBE").IsUnique();

            entity.HasIndex(e => e.BirthCityId, "persons_birth_city_id_9fea3d98");

            entity.HasIndex(e => e.CitizenCode, "persons_citizen_code_430dc102_uniq")
                .IsUnique()
                .HasFilter("([citizen_code] IS NOT NULL)");

            entity.HasIndex(e => e.CitizenNationalityId, "persons_citizen_nationality_id_ecc47f36");

            entity.HasIndex(e => e.HousingStatusId, "persons_housing_status_id_c8e37e67");

            entity.HasIndex(e => e.LegalRegisterNo, "persons_legal_register_no_22c0875c_uniq")
                .IsUnique()
                .HasFilter("([legal_register_no] IS NOT NULL)");

            entity.HasIndex(e => e.MilitaryServiceStatusId, "persons_military_service_status_id_31e57348");

            entity.HasIndex(e => e.NaturalNationalCode, "persons_natural_national_code_49221b45");

            entity.HasIndex(e => e.PassportNumber, "persons_passport_number_dff3f3fd_uniq")
                .IsUnique()
                .HasFilter("([passport_number] IS NOT NULL)");

            entity.HasIndex(e => e.ReligionId, "persons_religion_id_bf81e08d");

            entity.HasIndex(e => e.Typ, "persons_typ_611e3c8e");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AuthorizedUsers)
                .HasMaxLength(1000)
                .HasColumnName("authorized_users");
            entity.Property(e => e.BirthCityId).HasColumnName("birth_city_id");
            entity.Property(e => e.CitizenCode)
                .HasMaxLength(13)
                .HasColumnName("citizen_code");
            entity.Property(e => e.CitizenNationalityId).HasColumnName("citizen_nationality_id");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.EconomicCode)
                .HasMaxLength(14)
                .HasColumnName("economic_code");
            entity.Property(e => e.EconomicCodeOld)
                .HasMaxLength(14)
                .HasColumnName("economic_code_old");
            entity.Property(e => e.FileNumber)
                .HasMaxLength(50)
                .HasColumnName("file_number");
            entity.Property(e => e.HousingStatusId).HasColumnName("housing_status_id");
            entity.Property(e => e.IdIssuanceDate).HasColumnName("id_issuance_date");
            entity.Property(e => e.IdIssuancePlace)
                .HasMaxLength(50)
                .HasColumnName("id_issuance_place");
            entity.Property(e => e.IdNumber)
                .HasMaxLength(10)
                .HasColumnName("id_number");
            entity.Property(e => e.IsGovernmental).HasColumnName("is_governmental");
            entity.Property(e => e.IsInternalCitizenship).HasColumnName("is_internal_citizenship");
            entity.Property(e => e.LegalEstablishmentDate).HasColumnName("legal_establishment_date");
            entity.Property(e => e.LegalManagerFamily)
                .HasMaxLength(100)
                .HasColumnName("legal_manager_family");
            entity.Property(e => e.LegalManagerName)
                .HasMaxLength(50)
                .HasColumnName("legal_manager_name");
            entity.Property(e => e.LegalNationalCode)
                .HasMaxLength(11)
                .HasColumnName("legal_national_code");
            entity.Property(e => e.LegalRegisterNo)
                .HasMaxLength(50)
                .HasColumnName("legal_register_no");
            entity.Property(e => e.MaritalStatus)
                .HasMaxLength(6)
                .HasColumnName("marital_status");
            entity.Property(e => e.MarriageDate).HasColumnName("marriage_date");
            entity.Property(e => e.MilitaryServiceStatusId).HasColumnName("military_service_status_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.NaturalBirthDate).HasColumnName("natural_birth_date");
            entity.Property(e => e.NaturalFamily)
                .HasMaxLength(100)
                .HasColumnName("natural_family");
            entity.Property(e => e.NaturalFatherName)
                .HasMaxLength(50)
                .HasColumnName("natural_father_name");
            entity.Property(e => e.NaturalNationalCode)
                .HasMaxLength(10)
                .HasColumnName("natural_national_code");
            entity.Property(e => e.NaturalSex)
                .HasMaxLength(1)
                .HasColumnName("natural_sex");
            entity.Property(e => e.PassportNumber)
                .HasMaxLength(10)
                .HasColumnName("passport_number");
            entity.Property(e => e.PersonnelNumber)
                .HasMaxLength(50)
                .HasColumnName("personnel_number");
            entity.Property(e => e.Photo)
                .HasMaxLength(100)
                .HasColumnName("photo");
            entity.Property(e => e.ReligionId).HasColumnName("religion_id");
            entity.Property(e => e.ServiceDays).HasColumnName("service_days");
            entity.Property(e => e.ServiceMonths).HasColumnName("service_months");
            entity.Property(e => e.ServiceYears).HasColumnName("service_years");
            entity.Property(e => e.TtmsBuyerType).HasColumnName("ttms_buyer_type");
            entity.Property(e => e.TtmsSellerType).HasColumnName("ttms_seller_type");
            entity.Property(e => e.Typ)
                .IsRequired()
                .HasMaxLength(17)
                .HasColumnName("typ");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.BirthCity).WithMany(p => p.People)
                .HasForeignKey(d => d.BirthCityId)
                .HasConstraintName("persons_birth_city_id_9fea3d98_fk_cities_id");

            entity.HasOne(d => d.CitizenNationality).WithMany(p => p.People)
                .HasForeignKey(d => d.CitizenNationalityId)
                .HasConstraintName("persons_citizen_nationality_id_ecc47f36_fk_countries_id");

            entity.HasOne(d => d.HousingStatus).WithMany(p => p.People)
                .HasForeignKey(d => d.HousingStatusId)
                .HasConstraintName("persons_housing_status_id_c8e37e67_fk_housing_statuses_id");

            entity.HasOne(d => d.MilitaryServiceStatus).WithMany(p => p.People)
                .HasForeignKey(d => d.MilitaryServiceStatusId)
                .HasConstraintName("persons_military_service_status_id_31e57348_fk_military_service_statuses_id");

            entity.HasOne(d => d.Religion).WithMany(p => p.People)
                .HasForeignKey(d => d.ReligionId)
                .HasConstraintName("persons_religion_id_bf81e08d_fk_religions_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Person> entity);
    }
}
