// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class PersonFaxisConfiguration : IEntityTypeConfiguration<PersonFaxis>
    {
        public void Configure(EntityTypeBuilder<PersonFaxis> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__person_f__3213E83F6572A638");

            entity.ToTable("person_faxes", "general");

            entity.HasIndex(e => e.PersonId, "person_faxes_person_id_aeabbb62");

            entity.HasIndex(e => new { e.PersonId, e.Code, e.Fax }, "person_faxes_person_id_code_fax_2b464685_uniq")
                .IsUnique()
                .HasFilter("([person_id] IS NOT NULL AND [code] IS NOT NULL AND [fax] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Code)
                .HasMaxLength(8)
                .HasColumnName("code");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.Fax)
                .IsRequired()
                .HasMaxLength(12)
                .HasColumnName("fax");
            entity.Property(e => e.IsDefault).HasColumnName("is_default");
            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.Title)
                .HasMaxLength(50)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.Person).WithMany(p => p.PersonFaxes)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_faxes_person_id_aeabbb62_fk_persons_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonFaxis> entity);
    }
}
