// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class PersonWebsiteConfiguration : IEntityTypeConfiguration<PersonWebsite>
    {
        public void Configure(EntityTypeBuilder<PersonWebsite> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__person_w__3213E83F354F2664");

            entity.ToTable("person_websites", "general");

            entity.HasIndex(e => e.PersonId, "person_websites_person_id_2bf2e8a6");

            entity.HasIndex(e => new { e.PersonId, e.Website }, "person_websites_person_id_website_c64285de_uniq")
                .IsUnique()
                .HasFilter("([person_id] IS NOT NULL AND [website] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.IsDefault).HasColumnName("is_default");
            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.Title)
                .HasMaxLength(50)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");
            entity.Property(e => e.Website)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("website");

            entity.HasOne(d => d.Person).WithMany(p => p.PersonWebsites)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("person_websites_person_id_2bf2e8a6_fk_persons_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonWebsite> entity);
    }
}
