// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class ProvinceConfiguration : IEntityTypeConfiguration<Province>
    {
        public void Configure(EntityTypeBuilder<Province> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__province__3213E83FC4AE030D");

            entity.ToTable("provinces", "general");

            entity.HasIndex(e => e.CountryId, "provinces_country_id_8ee0b7b3");

            entity.HasIndex(e => new { e.CountryId, e.Code }, "provinces_country_id_code_8b417d3f_uniq")
                .IsUnique()
                .HasFilter("([country_id] IS NOT NULL AND [code] IS NOT NULL)");

            entity.HasIndex(e => new { e.CountryId, e.Name }, "provinces_country_id_name_9930a650_uniq")
                .IsUnique()
                .HasFilter("([country_id] IS NOT NULL AND [name] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.CountryId).HasColumnName("country_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");

            entity.HasOne(d => d.Country).WithMany(p => p.Provinces)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("provinces_country_id_8ee0b7b3_fk_countries_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Province> entity);
    }
}
