// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class SelectLogConfiguration : IEntityTypeConfiguration<SelectLog>
    {
        public void Configure(EntityTypeBuilder<SelectLog> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__select_l__3213E83F9F91C3A2");

            entity.ToTable("select_logs", "general");

            entity.HasIndex(e => e.CompanyId, "select_logs_company_id_36cbe9f3");

            entity.HasIndex(e => e.EntityTypeId, "select_logs_entity_type_id_1ff059a2");

            entity.HasIndex(e => e.ModuleId, "select_logs_module_id_94ef8091");

            entity.HasIndex(e => e.UserId, "select_logs_user_id_e7ccfdfc");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Command)
                .HasMaxLength(100)
                .HasColumnName("command");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.EntityTypeId).HasColumnName("entity_type_id");
            entity.Property(e => e.FiltersUsed).HasColumnName("filters_used");
            entity.Property(e => e.Ip)
                .IsRequired()
                .HasMaxLength(39)
                .HasColumnName("ip");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Company).WithMany(p => p.SelectLogs)
                .HasForeignKey(d => d.CompanyId)
                .HasConstraintName("select_logs_company_id_36cbe9f3_fk_companies_id");

            entity.HasOne(d => d.EntityType).WithMany(p => p.SelectLogs)
                .HasForeignKey(d => d.EntityTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("select_logs_entity_type_id_1ff059a2_fk_entity_types_id");

            entity.HasOne(d => d.Module).WithMany(p => p.SelectLogs)
                .HasForeignKey(d => d.ModuleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("select_logs_module_id_94ef8091_fk_modules_id");

            entity.HasOne(d => d.User).WithMany(p => p.SelectLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("select_logs_user_id_e7ccfdfc_fk_users_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SelectLog> entity);
    }
}
