// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__users__3213E83FA39B6DD7");

            entity.ToTable("users", "general");

            entity.HasIndex(e => e.PersonId, "UQ__users__543848DE030F1F1D").IsUnique();

            entity.HasIndex(e => e.Username, "UQ__users__F3DBC57279382736").IsUnique();

            entity.HasIndex(e => e.LanguageId, "users_language_id_9c707b57");

            entity.HasIndex(e => e.UsernameEncrypted, "users_username_encrypted_508d3951_uniq")
                .IsUnique()
                .HasFilter("([username_encrypted] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccessToken).HasColumnName("access_token");
            entity.Property(e => e.AuthSendType)
                .HasMaxLength(12)
                .HasColumnName("auth_send_type");
            entity.Property(e => e.ColorPallet)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("color_pallet");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.FontFamily)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("font_family");
            entity.Property(e => e.FontSize).HasColumnName("font_size");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.IsReportViewer).HasColumnName("is_report_viewer");
            entity.Property(e => e.IsStaff).HasColumnName("is_staff");
            entity.Property(e => e.IsSuperuser).HasColumnName("is_superuser");
            entity.Property(e => e.LanguageId).HasColumnName("language_id");
            entity.Property(e => e.LastLogin).HasColumnName("last_login");
            entity.Property(e => e.NewTab).HasColumnName("new_tab");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnName("password");
            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.RefreshToken).HasColumnName("refresh_token");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("username");
            entity.Property(e => e.UsernameEncrypted)
                .HasMaxLength(150)
                .HasColumnName("username_encrypted");

            entity.HasOne(d => d.Language).WithMany(p => p.Users)
                .HasForeignKey(d => d.LanguageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("users_language_id_9c707b57_fk_languages_id");

            entity.HasOne(d => d.Person).WithOne(p => p.User)
                .HasForeignKey<User>(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("users_person_id_5146b3bd_fk_persons_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<User> entity);
    }
}
