// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class UserConfigConfiguration : IEntityTypeConfiguration<UserConfig>
    {
        public void Configure(EntityTypeBuilder<UserConfig> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__user_con__3213E83F1E698839");

            entity.ToTable("user_configs", "general");

            entity.HasIndex(e => e.ModuleId, "user_configs_module_id_015d8e4f");

            entity.HasIndex(e => e.UserId, "user_configs_user_id_c0e78255");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Data).HasColumnName("data");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(4000)
                .HasColumnName("name");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Module).WithMany(p => p.UserConfigs)
                .HasForeignKey(d => d.ModuleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("user_configs_module_id_015d8e4f_fk_modules_id");

            entity.HasOne(d => d.User).WithMany(p => p.UserConfigs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("user_configs_user_id_c0e78255_fk_users_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserConfig> entity);
    }
}
