// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class WorkDepartmentConfiguration : IEntityTypeConfiguration<WorkDepartment>
    {
        public void Configure(EntityTypeBuilder<WorkDepartment> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__work_dep__3213E83F5C9B5BA8");

            entity.ToTable("work_departments", "general");

            entity.HasIndex(e => e.Name, "UQ__work_dep__72E12F1B9A5F7AEA").IsUnique();

            entity.HasIndex(e => e.CreatorId, "work_departments_creator_id_7fdcedc2");

            entity.HasIndex(e => e.WorkPlaceId, "work_departments_work_place_id_182cba09");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.WorkPlaceId).HasColumnName("work_place_id");

            entity.HasOne(d => d.Creator).WithMany(p => p.WorkDepartments)
                .HasForeignKey(d => d.CreatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("work_departments_creator_id_7fdcedc2_fk_users_id");

            entity.HasOne(d => d.WorkPlace).WithMany(p => p.WorkDepartments)
                .HasForeignKey(d => d.WorkPlaceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("work_departments_work_place_id_182cba09_fk_workplaces_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkDepartment> entity);
    }
}
