// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using General.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace General.Infrastructure.DataAccess.Configurations
{
    public partial class WorkplaceConfiguration : IEntityTypeConfiguration<Workplace>
    {
        public void Configure(EntityTypeBuilder<Workplace> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__workplac__3213E83FA78C10C5");

            entity.ToTable("workplaces", "general");

            entity.HasIndex(e => e.Name, "UQ__workplac__72E12F1B6E1EA09C").IsUnique();

            entity.HasIndex(e => e.CreatorId, "workplaces_creator_id_0cc80a6d");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");

            entity.HasOne(d => d.Creator).WithMany(p => p.Workplaces)
                .HasForeignKey(d => d.CreatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("workplaces_creator_id_0cc80a6d_fk_users_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Workplace> entity);
    }
}
