// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.Intrastructure.DataAccess;

#nullable disable

namespace Shared.Infrastructure.Migrations
{
    [DbContext(typeof(SharedDbContext))]
    partial class SharedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Persian_100_CI_AI")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Domain.Entities.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("account_number");

                    b.Property<DateOnly?>("AccountOpeningDate")
                        .HasColumnType("date")
                        .HasColumnName("account_opening_date");

                    b.Property<string>("AccountOwner")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("account_owner");

                    b.Property<string>("AccountType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("account_type");

                    b.Property<string>("AuthorizedUsers")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("authorized_users");

                    b.Property<int>("BankBranchId")
                        .HasColumnType("int")
                        .HasColumnName("bank_branch_id");

                    b.Property<int>("BankId")
                        .HasColumnType("int")
                        .HasColumnName("bank_id");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("card_number");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currency_id");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("Iban")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("iban");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("national_code");

                    b.Property<string>("Signatory1")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("signatory_1");

                    b.Property<string>("Signatory2")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("signatory_2");

                    b.Property<string>("Signatory3")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("signatory_3");

                    b.Property<string>("Signatory4")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("signatory_4");

                    b.Property<string>("Signatory5")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("signatory_5");

                    b.Property<DateOnly?>("SignatureExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("signature_expiry_date");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__bank_acc__3213E83F744A2E6C");

                    b.HasIndex(new[] { "BankBranchId" }, "bank_accounts_bank_branch_id_f4462cb3");

                    b.HasIndex(new[] { "BankId" }, "bank_accounts_bank_id_76519d0e");

                    b.HasIndex(new[] { "CompanyId" }, "bank_accounts_company_id_a0fdfe1f");

                    b.HasIndex(new[] { "CompanyId", "BankId", "AccountNumber" }, "bank_accounts_company_id_bank_id_account_number_dde4bd1e_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [bank_id] IS NOT NULL AND [account_number] IS NOT NULL)");

                    b.HasIndex(new[] { "CompanyId", "BankId", "CardNumber" }, "bank_accounts_company_id_bank_id_card_number_fbf237d1_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [bank_id] IS NOT NULL AND [card_number] IS NOT NULL)");

                    b.HasIndex(new[] { "CompanyId", "BankId", "Iban" }, "bank_accounts_company_id_bank_id_iban_077a9abd_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [bank_id] IS NOT NULL AND [iban] IS NOT NULL)");

                    b.HasIndex(new[] { "CurrencyId" }, "bank_accounts_currency_id_932d5611");

                    b.HasIndex(new[] { "TypeId" }, "bank_accounts_type_id_50bc1431");

                    b.ToTable("bank_accounts", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.BankBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("AuthorizedUsers")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("authorized_users");

                    b.Property<int>("BankId")
                        .HasColumnType("int")
                        .HasColumnName("bank_id");

                    b.Property<int?>("BranchNumber")
                        .HasColumnType("int")
                        .HasColumnName("branch_number");

                    b.Property<int>("Code")
                        .HasColumnType("int")
                        .HasColumnName("code");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__bank_bra__3213E83F7C6E8FEC");

                    b.HasIndex(new[] { "BankId" }, "bank_branches_bank_id_5eff2bac");

                    b.HasIndex(new[] { "CompanyId" }, "bank_branches_company_id_4a52d712");

                    b.HasIndex(new[] { "CompanyId", "BankId", "BranchNumber" }, "bank_branches_company_id_bank_id_branch_number_f4f0441e_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [bank_id] IS NOT NULL AND [branch_number] IS NOT NULL)");

                    b.HasIndex(new[] { "CompanyId", "BankId", "Name" }, "bank_branches_company_id_bank_id_name_e96f3efa_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [bank_id] IS NOT NULL AND [name] IS NOT NULL)");

                    b.HasIndex(new[] { "CompanyId", "Code" }, "bank_branches_company_id_code_edffeec5_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [code] IS NOT NULL)");

                    b.ToTable("bank_branches", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorizedUsers")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("authorized_users");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("bit")
                        .HasColumnName("is_static");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Name2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__branches__3213E83F59453D0A");

                    b.HasIndex(new[] { "CompanyId" }, "branches_company_id_c17fd5ca");

                    b.HasIndex(new[] { "CompanyId", "Code" }, "branches_company_id_code_2a76aa26_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [code] IS NOT NULL)");

                    b.HasIndex(new[] { "CompanyId", "Name" }, "branches_company_id_name_0b77f2d0_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [name] IS NOT NULL)");

                    b.ToTable("branches", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Cashier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorizedUsers")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("authorized_users");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int")
                        .HasColumnName("creator_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("PK__cashiers__3213E83FE910213E");

                    b.HasIndex(new[] { "CompanyId" }, "cashiers_company_id_e24f4c24");

                    b.HasIndex(new[] { "CompanyId", "PersonId" }, "cashiers_company_id_person_id_f0a0aa02_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [person_id] IS NOT NULL)");

                    b.HasIndex(new[] { "CreatorId" }, "cashiers_creator_id_cd8bd2ff");

                    b.HasIndex(new[] { "PersonId" }, "cashiers_person_id_2b0579d0");

                    b.ToTable("cashiers", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CompanySetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("CompanyProductLevel")
                        .HasColumnType("int")
                        .HasColumnName("company_product_level");

                    b.Property<int>("CompanyUnitLevel")
                        .HasColumnType("int")
                        .HasColumnName("company_unit_level");

                    b.Property<int>("CostCenterLevel")
                        .HasColumnType("int")
                        .HasColumnName("cost_center_level");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__company___3213E83F44690446");

                    b.HasIndex(new[] { "CompanyId" }, "UQ__company___3E2672341BAB4B8B")
                        .IsUnique();

                    b.ToTable("company_settings", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CompanyUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorizedUsers")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("authorized_users");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasColumnName("code");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("LastLevel")
                        .HasColumnType("bit")
                        .HasColumnName("last_level");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__company___3213E83FE6702795");

                    b.HasIndex(new[] { "CompanyId" }, "company_units_company_id_0a433407");

                    b.HasIndex(new[] { "CompanyId", "Code" }, "company_units_company_id_code_af9699c4_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [code] IS NOT NULL)");

                    b.HasIndex(new[] { "CompanyId", "Name", "ParentId" }, "company_units_company_id_name_parent_id_131855b6_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [name] IS NOT NULL AND [parent_id] IS NOT NULL)");

                    b.HasIndex(new[] { "ParentId" }, "company_units_parent_id_c41b621a");

                    b.ToTable("company_units", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorizedUsers")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("authorized_users");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasColumnName("code");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("LastLevel")
                        .HasColumnType("bit")
                        .HasColumnName("last_level");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__cost_cen__3213E83FF8026CF8");

                    b.HasIndex(new[] { "CompanyId" }, "cost_centers_company_id_5390b4ec");

                    b.HasIndex(new[] { "CompanyId", "Code" }, "cost_centers_company_id_code_153ce7ab_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [code] IS NOT NULL)");

                    b.HasIndex(new[] { "CompanyId", "Name", "ParentId" }, "cost_centers_company_id_name_parent_id_44518991_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [name] IS NOT NULL AND [parent_id] IS NOT NULL)");

                    b.HasIndex(new[] { "ParentId" }, "cost_centers_parent_id_eba90f6c");

                    b.ToTable("cost_centers", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Foo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("PK__foos__3213E83F373F6C6C");

                    b.HasIndex(new[] { "CompanyId" }, "foos_company_id_1a5e3040");

                    b.HasIndex(new[] { "ProductId" }, "foos_product_id_64577d3d");

                    b.ToTable("foos", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.PersonCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("PK__person_c__3213E83FDD636BD2");

                    b.HasIndex(new[] { "CompanyId" }, "person_companies_company_id_8d893c9c");

                    b.HasIndex(new[] { "PersonId" }, "person_companies_person_id_01c9a592");

                    b.HasIndex(new[] { "PersonId", "CompanyId" }, "person_companies_person_id_company_id_7ccc3e32_uniq")
                        .IsUnique()
                        .HasFilter("([person_id] IS NOT NULL AND [company_id] IS NOT NULL)");

                    b.ToTable("person_companies", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.PersonGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.Property<int>("PersonGroupId")
                        .HasColumnType("int")
                        .HasColumnName("person_group_id");

                    b.HasKey("Id")
                        .HasName("PK__person_g__3213E83F33F883A4");

                    b.HasIndex(new[] { "CompanyId" }, "person_group_members_company_id_730c5fff");

                    b.HasIndex(new[] { "CompanyId", "PersonGroupId", "MemberId" }, "person_group_members_company_id_person_group_id_member_id_b5c20e26_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [person_group_id] IS NOT NULL AND [member_id] IS NOT NULL)");

                    b.HasIndex(new[] { "MemberId" }, "person_group_members_member_id_fb0c85d9");

                    b.HasIndex(new[] { "PersonGroupId" }, "person_group_members_person_group_id_34698b20");

                    b.ToTable("person_group_members", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.PettyCashier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorizedUsers")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("authorized_users");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int")
                        .HasColumnName("creator_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("PK__petty_ca__3213E83F7F5C9154");

                    b.HasIndex(new[] { "CompanyId" }, "petty_cashiers_company_id_adaef187");

                    b.HasIndex(new[] { "CompanyId", "PersonId" }, "petty_cashiers_company_id_person_id_d434ff7c_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [person_id] IS NOT NULL)");

                    b.HasIndex(new[] { "CreatorId" }, "petty_cashiers_creator_id_d570b446");

                    b.HasIndex(new[] { "PersonId" }, "petty_cashiers_person_id_5a0c025f");

                    b.ToTable("petty_cashiers", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int")
                        .HasColumnName("creator_id");

                    b.Property<int?>("FirstMeasurementId")
                        .HasColumnType("int")
                        .HasColumnName("first_measurement_id");

                    b.Property<int?>("ForthMeasurementId")
                        .HasColumnType("int")
                        .HasColumnName("forth_measurement_id");

                    b.Property<short?>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int?>("SecondMeasurementId")
                        .HasColumnType("int")
                        .HasColumnName("second_measurement_id");

                    b.Property<int?>("ThirdMeasurementId")
                        .HasColumnType("int")
                        .HasColumnName("third_measurement_id");

                    b.HasKey("Id")
                        .HasName("PK__products__3213E83FA586B203");

                    b.HasIndex(new[] { "CompanyId" }, "products_company_id_85cab11e");

                    b.HasIndex(new[] { "CreatorId" }, "products_creator_id_f217ad7d");

                    b.HasIndex(new[] { "FirstMeasurementId" }, "products_first_measurement_id_c9eb56e6");

                    b.HasIndex(new[] { "ForthMeasurementId" }, "products_forth_measurement_id_2571e159");

                    b.HasIndex(new[] { "ParentId" }, "products_parent_id_6d11d0e1");

                    b.HasIndex(new[] { "SecondMeasurementId" }, "products_second_measurement_id_9e456e28");

                    b.HasIndex(new[] { "ThirdMeasurementId" }, "products_third_measurement_id_40c75e99");

                    b.ToTable("products", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("PK__Purchase__3213E83F5BE5247E");

                    b.HasIndex(new[] { "CompanyId" }, "Purchases_company_id_a3e8b6cd");

                    b.HasIndex(new[] { "ProductId" }, "Purchases_product_id_d1413dc0");

                    b.ToTable("Purchases", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.ReportTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int")
                        .HasColumnName("creator_id");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("ReportKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("report_key");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("template");

                    b.HasKey("Id")
                        .HasName("PK__report_t__3213E83F97AEB692");

                    b.HasIndex(new[] { "CompanyId" }, "report_templates_company_id_d546fa98");

                    b.HasIndex(new[] { "CompanyId", "ReportKey", "Name" }, "report_templates_company_id_report_key_name_f3282f81_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [report_key] IS NOT NULL AND [name] IS NOT NULL)");

                    b.HasIndex(new[] { "CreatorId" }, "report_templates_creator_id_1650956e");

                    b.HasIndex(new[] { "ModuleId" }, "report_templates_module_id_e5a4ce8d");

                    b.ToTable("report_templates", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Restriction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int")
                        .HasColumnName("entity_type_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__restrict__3213E83F37293154");

                    b.HasIndex(new[] { "CompanyId" }, "restrictions_company_id_e24e8bce");

                    b.HasIndex(new[] { "CompanyId", "EntityTypeId", "UserId" }, "restrictions_company_id_entity_type_id_user_id_2296a366_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [entity_type_id] IS NOT NULL AND [user_id] IS NOT NULL)");

                    b.HasIndex(new[] { "EntityTypeId" }, "restrictions_entity_type_id_5861bb50");

                    b.HasIndex(new[] { "UserId" }, "restrictions_user_id_1ef45563");

                    b.ToTable("restrictions", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorizedUsers")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("authorized_users");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("bit")
                        .HasColumnName("is_static");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__roles__3213E83FF1D516A7");

                    b.HasIndex(new[] { "CompanyId" }, "roles_company_id_f4c539e9");

                    b.HasIndex(new[] { "CompanyId", "Name" }, "roles_company_id_name_35c99075_uniq")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [name] IS NOT NULL)");

                    b.ToTable("roles", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.RoleMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorizedUsers")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("authorized_users");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("PK__role_mem__3213E83FA3102DA6");

                    b.HasIndex(new[] { "CompanyId" }, "role_members_company_id_c28413ce");

                    b.HasIndex(new[] { "MemberId" }, "role_members_member_id_0a61f922");

                    b.HasIndex(new[] { "RoleId" }, "role_members_role_id_3742ecb7");

                    b.HasIndex(new[] { "RoleId", "MemberId" }, "role_members_role_id_member_id_22328589_uniq")
                        .IsUnique()
                        .HasFilter("([role_id] IS NOT NULL AND [member_id] IS NOT NULL)");

                    b.ToTable("role_members", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Create")
                        .HasColumnType("bit")
                        .HasColumnName("create");

                    b.Property<bool>("Delete")
                        .HasColumnType("bit")
                        .HasColumnName("delete");

                    b.Property<bool>("Edit")
                        .HasColumnType("bit")
                        .HasColumnName("edit");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int")
                        .HasColumnName("entity_type_id");

                    b.Property<bool>("Exp")
                        .HasColumnType("bit")
                        .HasColumnName("exp");

                    b.Property<bool>("IfNotCreator")
                        .HasColumnType("bit")
                        .HasColumnName("if_not_creator");

                    b.Property<bool>("Imp")
                        .HasColumnType("bit")
                        .HasColumnName("imp");

                    b.Property<bool>("Log")
                        .HasColumnType("bit")
                        .HasColumnName("log");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<bool>("Print")
                        .HasColumnType("bit")
                        .HasColumnName("print");

                    b.Property<bool>("Read")
                        .HasColumnType("bit")
                        .HasColumnName("read");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("PK__role_per__3213E83FADCE6844");

                    b.HasIndex(new[] { "EntityTypeId" }, "role_permissions_entity_type_id_74eb6fa5");

                    b.HasIndex(new[] { "ModuleId" }, "role_permissions_module_id_f6701517");

                    b.HasIndex(new[] { "RoleId" }, "role_permissions_role_id_216516f2");

                    b.HasIndex(new[] { "RoleId", "EntityTypeId" }, "role_permissions_role_id_entity_type_id_285eba22_uniq")
                        .IsUnique()
                        .HasFilter("([role_id] IS NOT NULL AND [entity_type_id] IS NOT NULL)");

                    b.ToTable("role_permissions", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.RolePermissionCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("command_key");

                    b.Property<int>("EntityTypeCommandId")
                        .HasColumnType("int")
                        .HasColumnName("entity_type_command_id");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int")
                        .HasColumnName("entity_type_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("RolePermissionId")
                        .HasColumnType("int")
                        .HasColumnName("role_permission_id");

                    b.Property<bool>("Value")
                        .HasColumnType("bit")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("PK__role_per__3213E83F6F6DDE28");

                    b.HasIndex(new[] { "EntityTypeCommandId" }, "role_permission_commands_entity_type_command_id_9e625b38");

                    b.HasIndex(new[] { "EntityTypeId" }, "role_permission_commands_entity_type_id_a3513f52");

                    b.HasIndex(new[] { "RoleId" }, "role_permission_commands_role_id_5d1758cb");

                    b.HasIndex(new[] { "RolePermissionId" }, "role_permission_commands_role_permission_id_40a8626f");

                    b.HasIndex(new[] { "RolePermissionId", "EntityTypeCommandId" }, "role_permission_commands_role_permission_id_entity_type_command_id_9f7be0a3_uniq")
                        .IsUnique()
                        .HasFilter("([role_permission_id] IS NOT NULL AND [entity_type_command_id] IS NOT NULL)");

                    b.ToTable("role_permission_commands", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.RolePermissionConstraint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Create")
                        .HasColumnType("bit")
                        .HasColumnName("create");

                    b.Property<bool>("Edit")
                        .HasColumnType("bit")
                        .HasColumnName("edit");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int")
                        .HasColumnName("entity_type_id");

                    b.Property<bool>("Exp")
                        .HasColumnType("bit")
                        .HasColumnName("exp");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("field_name");

                    b.Property<bool>("Imp")
                        .HasColumnType("bit")
                        .HasColumnName("imp");

                    b.Property<bool>("Print")
                        .HasColumnType("bit")
                        .HasColumnName("print");

                    b.Property<bool>("Read")
                        .HasColumnType("bit")
                        .HasColumnName("read");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("RolePermissionId")
                        .HasColumnType("int")
                        .HasColumnName("role_permission_id");

                    b.HasKey("Id")
                        .HasName("PK__role_per__3213E83F595C377F");

                    b.HasIndex(new[] { "EntityTypeId" }, "role_permission_constraints_entity_type_id_183e495f");

                    b.HasIndex(new[] { "RoleId" }, "role_permission_constraints_role_id_3ad70fc8");

                    b.HasIndex(new[] { "RolePermissionId" }, "role_permission_constraints_role_permission_id_678eb8f6");

                    b.HasIndex(new[] { "RolePermissionId", "FieldName" }, "role_permission_constraints_role_permission_id_field_name_6671fb32_uniq")
                        .IsUnique()
                        .HasFilter("([role_permission_id] IS NOT NULL AND [field_name] IS NOT NULL)");

                    b.ToTable("role_permission_constraints", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("PK__sales__3213E83FDEDC98F0");

                    b.HasIndex(new[] { "CompanyId" }, "sales_company_id_1480331f");

                    b.HasIndex(new[] { "ProductId" }, "sales_product_id_a179a813");

                    b.ToTable("sales", "shared");
                });

            modelBuilder.Entity("Shared.Domain.Entities.BankAccount", b =>
                {
                    b.HasOne("Shared.Domain.Entities.BankBranch", "BankBranch")
                        .WithMany("BankAccounts")
                        .HasForeignKey("BankBranchId")
                        .IsRequired()
                        .HasConstraintName("bank_accounts_bank_branch_id_f4462cb3_fk_bank_branches_id");

                    b.Navigation("BankBranch");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CompanyUnit", b =>
                {
                    b.HasOne("Shared.Domain.Entities.CompanyUnit", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("company_units_parent_id_c41b621a_fk_company_units_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CostCenter", b =>
                {
                    b.HasOne("Shared.Domain.Entities.CostCenter", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("cost_centers_parent_id_eba90f6c_fk_cost_centers_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Foo", b =>
                {
                    b.HasOne("Shared.Domain.Entities.Product", "Product")
                        .WithMany("Foos")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("foos_product_id_64577d3d_fk_products_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Product", b =>
                {
                    b.HasOne("Shared.Domain.Entities.Product", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("products_parent_id_6d11d0e1_fk_products_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("Shared.Domain.Entities.Product", "Product")
                        .WithMany("Purchases")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("Purchases_product_id_d1413dc0_fk_products_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shared.Domain.Entities.RoleMember", b =>
                {
                    b.HasOne("Shared.Domain.Entities.Role", "Role")
                        .WithMany("RoleMembers")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("role_members_role_id_3742ecb7_fk_roles_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Shared.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Shared.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("role_permissions_role_id_216516f2_fk_roles_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Shared.Domain.Entities.RolePermissionCommand", b =>
                {
                    b.HasOne("Shared.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissionCommands")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("role_permission_commands_role_id_5d1758cb_fk_roles_id");

                    b.HasOne("Shared.Domain.Entities.RolePermission", "RolePermission")
                        .WithMany("RolePermissionCommands")
                        .HasForeignKey("RolePermissionId")
                        .IsRequired()
                        .HasConstraintName("role_permission_commands_role_permission_id_40a8626f_fk_role_permissions_id");

                    b.Navigation("Role");

                    b.Navigation("RolePermission");
                });

            modelBuilder.Entity("Shared.Domain.Entities.RolePermissionConstraint", b =>
                {
                    b.HasOne("Shared.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissionConstraints")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("role_permission_constraints_role_id_3ad70fc8_fk_roles_id");

                    b.HasOne("Shared.Domain.Entities.RolePermission", "RolePermission")
                        .WithMany("RolePermissionConstraints")
                        .HasForeignKey("RolePermissionId")
                        .IsRequired()
                        .HasConstraintName("role_permission_constraints_role_permission_id_678eb8f6_fk_role_permissions_id");

                    b.Navigation("Role");

                    b.Navigation("RolePermission");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Sale", b =>
                {
                    b.HasOne("Shared.Domain.Entities.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("sales_product_id_a179a813_fk_products_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shared.Domain.Entities.BankBranch", b =>
                {
                    b.Navigation("BankAccounts");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CompanyUnit", b =>
                {
                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CostCenter", b =>
                {
                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Product", b =>
                {
                    b.Navigation("Foos");

                    b.Navigation("InverseParent");

                    b.Navigation("Purchases");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleMembers");

                    b.Navigation("RolePermissionCommands");

                    b.Navigation("RolePermissionConstraints");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Shared.Domain.Entities.RolePermission", b =>
                {
                    b.Navigation("RolePermissionCommands");

                    b.Navigation("RolePermissionConstraints");
                });
#pragma warning restore 612, 618
        }
    }
}
