// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Domain.Entities;

public partial class BankAccount
{
    public int Id { get; set; }

    public string Iban { get; set; }

    public string AccountNumber { get; set; }

    public string CardNumber { get; set; }

    public string Description { get; set; }

    public string AccountOwner { get; set; }

    public string AccountType { get; set; }

    public DateOnly? AccountOpeningDate { get; set; }

    public DateOnly? SignatureExpiryDate { get; set; }

    public string NationalCode { get; set; }

    public string Signatory1 { get; set; }

    public string Signatory2 { get; set; }

    public string Signatory3 { get; set; }

    public string Signatory4 { get; set; }

    public string Signatory5 { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string AuthorizedUsers { get; set; }

    public int BankId { get; set; }

    public int BankBranchId { get; set; }

    public int CompanyId { get; set; }

    public int? CurrencyId { get; set; }

    public int TypeId { get; set; }

    public virtual BankBranch BankBranch { get; set; }
}