// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Domain.Entities;

public partial class Branch
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Name2 { get; set; }

    public bool IsStatic { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string AuthorizedUsers { get; set; }

    public int CompanyId { get; set; }
}