// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Domain.Entities;

public partial class Cashier
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public string AuthorizedUsers { get; set; }

    public int CompanyId { get; set; }

    public int CreatorId { get; set; }

    public int PersonId { get; set; }
}