// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Domain.Entities;

public partial class CompanySetting
{
    public int Id { get; set; }

    public int CostCenterLevel { get; set; }

    public int CompanyUnitLevel { get; set; }

    public int CompanyProductLevel { get; set; }

    public DateTime UpdatedAt { get; set; }

    public int CompanyId { get; set; }
}