// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Domain.Entities;

public partial class PersonGroupMember
{
    public int Id { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CompanyId { get; set; }

    public int MemberId { get; set; }

    public int PersonGroupId { get; set; }
}