// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Domain.Entities;

public partial class Product
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public short? Level { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CompanyId { get; set; }

    public int CreatorId { get; set; }

    public int? FirstMeasurementId { get; set; }

    public int? ForthMeasurementId { get; set; }

    public int? ParentId { get; set; }

    public int? SecondMeasurementId { get; set; }

    public int? ThirdMeasurementId { get; set; }

    public virtual ICollection<Foo> Foos { get; set; } = new List<Foo>();

    public virtual ICollection<Product> InverseParent { get; set; } = new List<Product>();

    public virtual Product Parent { get; set; }

    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}