// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Domain.Entities;

public partial class Purchase
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public decimal Amount { get; set; }

    public int Count { get; set; }

    public string Text { get; set; }

    public int CompanyId { get; set; }

    public int ProductId { get; set; }

    public virtual Product Product { get; set; }
}