// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Domain.Entities;

public partial class ReportTemplate
{
    public int Id { get; set; }

    public string ReportKey { get; set; }

    public string Name { get; set; }

    public string Template { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CompanyId { get; set; }

    public int CreatorId { get; set; }

    public int ModuleId { get; set; }
}