// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Domain.Entities;

public partial class RolePermission
{
    public int Id { get; set; }

    public bool Read { get; set; }

    public bool Create { get; set; }

    public bool Edit { get; set; }

    public bool Delete { get; set; }

    public bool Log { get; set; }

    public bool Print { get; set; }

    public bool Imp { get; set; }

    public bool Exp { get; set; }

    public bool IfNotCreator { get; set; }

    public int EntityTypeId { get; set; }

    public int ModuleId { get; set; }

    public int RoleId { get; set; }

    public virtual Role Role { get; set; }

    public virtual ICollection<RolePermissionCommand> RolePermissionCommands { get; set; } = new List<RolePermissionCommand>();

    public virtual ICollection<RolePermissionConstraint> RolePermissionConstraints { get; set; } = new List<RolePermissionConstraint>();
}