// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared.Domain.Entities;

public partial class RoleMember
{
    public int Id { get; set; }

    public string AuthorizedUsers { get; set; }

    public int CompanyId { get; set; }

    public int MemberId { get; set; }

    public int RoleId { get; set; }

    public virtual Role Role { get; set; }
}