// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGErp.General.Domain.Entities;

public partial class BankStatementPattern
{
    public int Id { get; set; }

    public string ColumnChequeNo { get; set; }

    public string ColumnChequeDate { get; set; }

    public string ColumnDebit { get; set; }

    public string ColumnCredit { get; set; }

    public short FirstRowNo { get; set; }

    public short IgnoreLatestRows { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int BankId { get; set; }

    public virtual Bank Bank { get; set; }
}