// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace General.Domain.Entities;

public partial class City
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Code { get; set; }

    public int? Code2 { get; set; }

    public int? Code3 { get; set; }

    public int ProvinceId { get; set; }

    public virtual ICollection<Person> People { get; set; } = new List<Person>();

    public virtual ICollection<PersonAddress> PersonAddresses { get; set; } = new List<PersonAddress>();

    public virtual ICollection<PersonRelative> PersonRelatives { get; set; } = new List<PersonRelative>();

    public virtual Province Province { get; set; }
}