// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace General.Domain.Entities;

[Table("companies", Schema = "general")]
public partial class Company
{    
    public int Id { get; set; }

    public string Name { get; set; }

    public string Name2 { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; }
    
    [Column("domain_id")]
    public int DomainId { get; set; }

    public virtual ICollection<CompanyAdmin> CompanyAdmins { get; set; } = new List<CompanyAdmin>();

    public virtual ICollection<CompanyModule> CompanyModules { get; set; } = new List<CompanyModule>();

    public virtual Domain Domain { get; set; }

    public virtual ICollection<Log> Logs { get; set; } = new List<Log>();

    public virtual ICollection<SelectLog> SelectLogs { get; set; } = new List<SelectLog>();
}