// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGErp.General.Domain.Entities;

public partial class Country
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Code { get; set; }

    public int? TaxCode { get; set; }

    public int? CurrencyId { get; set; }

    public virtual Currency Currency { get; set; }

    public virtual ICollection<Person> People { get; set; } = new List<Person>();

    public virtual ICollection<PersonAddress> PersonAddresses { get; set; } = new List<PersonAddress>();

    public virtual ICollection<Province> Provinces { get; set; } = new List<Province>();
}