// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGErp.General.Domain.Entities;

public partial class EntityTypeDependency
{
    public int Id { get; set; }

    public bool Read { get; set; }

    public bool Create { get; set; }

    public bool Edit { get; set; }

    public bool Delete { get; set; }

    public bool Log { get; set; }

    public bool Print { get; set; }

    public bool Imp { get; set; }

    public bool Exp { get; set; }

    public bool IfNotCreator { get; set; }

    public int EntityTypeId { get; set; }

    public int RequiredEntityTypeId { get; set; }

    public virtual EntityType EntityType { get; set; }

    public virtual EntityType RequiredEntityType { get; set; }
}