// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NGErp.General.Domain.Entities;

public partial class EntityType
{
    public int Id { get; set; }

    public string Key { get; set; }

    public string NameFa { get; set; }

    public string NameEn { get; set; }

    public bool Readable { get; set; }

    public bool Creatable { get; set; }

    public bool Editable { get; set; }

    public bool Deletable { get; set; }

    public bool Loggable { get; set; }

    public bool Printable { get; set; }

    public bool Importable { get; set; }

    public bool Exportable { get; set; }

    public bool IfNotCreator { get; set; }

    public bool HasRestriction { get; set; }

    public bool Permissible { get; set; }

    public bool HasConstraint { get; set; }

    public short? Ordering { get; set; }

    public int? ContentTypeId { get; set; }

    public int ModuleId { get; set; }

    public virtual ICollection<EntityTypeCommand> EntityTypeCommands { get; set; } = new List<EntityTypeCommand>();

    public virtual ICollection<EntityTypeConstraint> EntityTypeConstraints { get; set; } = new List<EntityTypeConstraint>();

    [InverseProperty("EntityType")]
    public virtual ICollection<EntityTypeDependency> EntityTypeDependencyEntityTypes { get; set; } = new List<EntityTypeDependency>();

    [InverseProperty("RequiredEntityType")]
    public virtual ICollection<EntityTypeDependency> EntityTypeDependencyRequiredEntityTypes { get; set; } = new List<EntityTypeDependency>();

    public virtual ICollection<Log> Logs { get; set; } = new List<Log>();

    public virtual ICollection<MenuItem> MenuItems { get; set; } = new List<MenuItem>();

    public virtual Module Module { get; set; }

    public virtual ICollection<SelectLog> SelectLogs { get; set; } = new List<SelectLog>();
}