// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGErp.General.Domain.Entities;

public partial class EntityTypeConstraint
{
    public int Id { get; set; }

    public string FieldName { get; set; }

    public string NameFa { get; set; }

    public string NameEn { get; set; }

    public bool Readable { get; set; }

    public bool Creatable { get; set; }

    public bool Editable { get; set; }

    public bool Printable { get; set; }

    public bool Importable { get; set; }

    public bool Exportable { get; set; }

    public short? Ordering { get; set; }

    public int EntityTypeId { get; set; }

    public virtual EntityType EntityType { get; set; }
}