// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGErp.General.Domain.Entities;

public partial class ForeignLanguage
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CreatorId { get; set; }

    public virtual User Creator { get; set; }
}