// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGErp.General.Domain.Entities;

public partial class Language
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public string Direction { get; set; }

    public virtual ICollection<Domain> Domains { get; set; } = new List<Domain>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}