// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace General.Domain.Entities;

public partial class MenuItem
{
    public int Id { get; set; }

    public short Order { get; set; }

    public string NameFa { get; set; }

    public string NameEn { get; set; }

    public string Link { get; set; }

    public string ShortKey { get; set; }

    public bool NewTab { get; set; }

    public string StandardPage { get; set; }

    public string Meta { get; set; }

    public int? EntityTypeId { get; set; }

    public int? EntityTypeCommandId { get; set; }

    public int ModuleId { get; set; }

    public int? ParentId { get; set; }

    public virtual EntityType EntityType { get; set; }

    public virtual EntityTypeCommand EntityTypeCommand { get; set; }

    public virtual ICollection<MenuItem> InverseParent { get; set; } = new List<MenuItem>();

    public virtual Module Module { get; set; }

    public virtual MenuItem Parent { get; set; }
}