// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGErp.General.Domain.Entities;

public partial class MissionType
{
    public int Id { get; set; }

    public int Code { get; set; }

    public string Name { get; set; }

    public bool HasFormula { get; set; }

    public string Formula { get; set; }

    public decimal? Multiplier { get; set; }

    public decimal? FixedAmount { get; set; }

    public string ParametricCustomFormula { get; set; }

    public bool IsDefault { get; set; }

    public bool IsHourly { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CreatorId { get; set; }

    public virtual User Creator { get; set; }
}