// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGErp.General.Domain.Entities;

public partial class PersonBankAccount
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int? BankBranchCode { get; set; }

    public string BankBranchName { get; set; }

    public string Iban { get; set; }

    public string AccountNumber { get; set; }

    public string CardNumber { get; set; }

    public bool IsDefault { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int BankId { get; set; }

    public int PersonId { get; set; }

    public virtual Bank Bank { get; set; }

    public virtual Person Person { get; set; }
}