// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NGErp.General.Domain.Entities;

public partial class PersonEducationalDegree
{
    public int Id { get; set; }

    public string StudyField { get; set; }

    public string EducationalInstitution { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public decimal? Gpa { get; set; }

    public bool IsDefault { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CreatorId { get; set; }

    public int EducationalDegreeId { get; set; }

    public int PersonId { get; set; }

    public virtual User Creator { get; set; }

    public virtual EducationalDegree EducationalDegree { get; set; }

    public virtual Person Person { get; set; }
}