// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace General.Domain.Entities;

public partial class SelectLog
{
    public int Id { get; set; }

    public string FiltersUsed { get; set; }

    public string Command { get; set; }

    public string Ip { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CompanyId { get; set; }

    public int EntityTypeId { get; set; }

    public int ModuleId { get; set; }

    public int UserId { get; set; }

    public virtual Company Company { get; set; }

    public virtual EntityType EntityType { get; set; }

    public virtual Module Module { get; set; }

    public virtual User User { get; set; }
}