// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class BankBranchConfiguration : IEntityTypeConfiguration<BankBranch>
    {
        public void Configure(EntityTypeBuilder<BankBranch> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__bank_bra__3213E83F897FA9C3");

            entity.ToTable("bank_branches", "shared");

            entity.HasIndex(e => e.BankId, "bank_branches_bank_id_5eff2bac");

            entity.HasIndex(e => e.CompanyId, "bank_branches_company_id_4a52d712");

            entity.HasIndex(e => new { e.CompanyId, e.BankId, e.BranchNumber }, "bank_branches_company_id_bank_id_branch_number_f4f0441e_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [bank_id] IS NOT NULL AND [branch_number] IS NOT NULL)");

            entity.HasIndex(e => new { e.CompanyId, e.BankId, e.Name }, "bank_branches_company_id_bank_id_name_e96f3efa_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [bank_id] IS NOT NULL AND [name] IS NOT NULL)");

            entity.HasIndex(e => new { e.CompanyId, e.Code }, "bank_branches_company_id_code_edffeec5_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [code] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(200)
                .HasColumnName("address");
            entity.Property(e => e.AuthorizedUsers)
                .HasMaxLength(1000)
                .HasColumnName("authorized_users");
            entity.Property(e => e.BankId).HasColumnName("bank_id");
            entity.Property(e => e.BranchNumber).HasColumnName("branch_number");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Phone)
                .HasMaxLength(100)
                .HasColumnName("phone");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BankBranch> entity);
    }
}
