// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class BankAccountConfiguration : IEntityTypeConfiguration<BankAccount>
    {
        public void Configure(EntityTypeBuilder<BankAccount> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__bank_acc__3213E83F744A2E6C");

            entity.ToTable("bank_accounts", "shared");

            entity.HasIndex(e => e.BankBranchId, "bank_accounts_bank_branch_id_f4462cb3");

            entity.HasIndex(e => e.BankId, "bank_accounts_bank_id_76519d0e");

            entity.HasIndex(e => e.CompanyId, "bank_accounts_company_id_a0fdfe1f");

            entity.HasIndex(e => new { e.CompanyId, e.BankId, e.AccountNumber }, "bank_accounts_company_id_bank_id_account_number_dde4bd1e_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [bank_id] IS NOT NULL AND [account_number] IS NOT NULL)");

            entity.HasIndex(e => new { e.CompanyId, e.BankId, e.CardNumber }, "bank_accounts_company_id_bank_id_card_number_fbf237d1_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [bank_id] IS NOT NULL AND [card_number] IS NOT NULL)");

            entity.HasIndex(e => new { e.CompanyId, e.BankId, e.Iban }, "bank_accounts_company_id_bank_id_iban_077a9abd_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [bank_id] IS NOT NULL AND [iban] IS NOT NULL)");

            entity.HasIndex(e => e.CurrencyId, "bank_accounts_currency_id_932d5611");

            entity.HasIndex(e => e.TypeId, "bank_accounts_type_id_50bc1431");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccountNumber)
                .HasMaxLength(24)
                .HasColumnName("account_number");
            entity.Property(e => e.AccountOpeningDate).HasColumnName("account_opening_date");
            entity.Property(e => e.AccountOwner)
                .HasMaxLength(150)
                .HasColumnName("account_owner");
            entity.Property(e => e.AccountType)
                .HasMaxLength(10)
                .HasColumnName("account_type");
            entity.Property(e => e.AuthorizedUsers)
                .HasMaxLength(1000)
                .HasColumnName("authorized_users");
            entity.Property(e => e.BankBranchId).HasColumnName("bank_branch_id");
            entity.Property(e => e.BankId).HasColumnName("bank_id");
            entity.Property(e => e.CardNumber)
                .HasMaxLength(16)
                .HasColumnName("card_number");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CurrencyId).HasColumnName("currency_id");
            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .HasColumnName("description");
            entity.Property(e => e.Iban)
                .HasMaxLength(26)
                .HasColumnName("iban");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.NationalCode)
                .HasMaxLength(11)
                .HasColumnName("national_code");
            entity.Property(e => e.Signatory1)
                .HasMaxLength(150)
                .HasColumnName("signatory_1");
            entity.Property(e => e.Signatory2)
                .HasMaxLength(150)
                .HasColumnName("signatory_2");
            entity.Property(e => e.Signatory3)
                .HasMaxLength(150)
                .HasColumnName("signatory_3");
            entity.Property(e => e.Signatory4)
                .HasMaxLength(150)
                .HasColumnName("signatory_4");
            entity.Property(e => e.Signatory5)
                .HasMaxLength(150)
                .HasColumnName("signatory_5");
            entity.Property(e => e.SignatureExpiryDate).HasColumnName("signature_expiry_date");
            entity.Property(e => e.TypeId).HasColumnName("type_id");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.BankBranch).WithMany(p => p.BankAccounts)
                .HasForeignKey(d => d.BankBranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("bank_accounts_bank_branch_id_f4462cb3_fk_bank_branches_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BankAccount> entity);
    }
}
