// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class CashierConfiguration : IEntityTypeConfiguration<Cashier>
    {
        public void Configure(EntityTypeBuilder<Cashier> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__cashiers__3213E83FE910213E");

            entity.ToTable("cashiers", "shared");

            entity.HasIndex(e => e.CompanyId, "cashiers_company_id_e24f4c24");

            entity.HasIndex(e => new { e.CompanyId, e.PersonId }, "cashiers_company_id_person_id_f0a0aa02_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [person_id] IS NOT NULL)");

            entity.HasIndex(e => e.CreatorId, "cashiers_creator_id_cd8bd2ff");

            entity.HasIndex(e => e.PersonId, "cashiers_person_id_2b0579d0");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AuthorizedUsers)
                .HasMaxLength(1000)
                .HasColumnName("authorized_users");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.PersonId).HasColumnName("person_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Cashier> entity);
    }
}
