// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class CompanySettingConfiguration : IEntityTypeConfiguration<CompanySetting>
    {
        public void Configure(EntityTypeBuilder<CompanySetting> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__company___3213E83F58F5955D");

            entity.ToTable("company_settings", "shared");

            entity.HasIndex(e => e.CompanyId, "UQ__company___3E2672348C06AA9B").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CompanyProductLevel).HasColumnName("company_product_level");
            entity.Property(e => e.CompanyUnitLevel).HasColumnName("company_unit_level");
            entity.Property(e => e.CostCenterLevel).HasColumnName("cost_center_level");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CompanySetting> entity);
    }
}
