// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class CompanyUnitConfiguration : IEntityTypeConfiguration<CompanyUnit>
    {
        public void Configure(EntityTypeBuilder<CompanyUnit> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__company___3213E83F1DB44160");

            entity.ToTable("company_units", "shared");

            entity.HasIndex(e => e.CompanyId, "company_units_company_id_0a433407");

            entity.HasIndex(e => new { e.CompanyId, e.Code }, "company_units_company_id_code_af9699c4_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [code] IS NOT NULL)");

            entity.HasIndex(e => new { e.CompanyId, e.Name, e.ParentId }, "company_units_company_id_name_parent_id_131855b6_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [name] IS NOT NULL AND [parent_id] IS NOT NULL)");

            entity.HasIndex(e => e.ParentId, "company_units_parent_id_c41b621a");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AuthorizedUsers)
                .HasMaxLength(1000)
                .HasColumnName("authorized_users");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(21)
                .HasColumnName("code");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.LastLevel).HasColumnName("last_level");
            entity.Property(e => e.Level).HasColumnName("level");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ParentId).HasColumnName("parent_id");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("company_units_parent_id_c41b621a_fk_company_units_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CompanyUnit> entity);
    }
}
