// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class CostCenterConfiguration : IEntityTypeConfiguration<CostCenter>
    {
        public void Configure(EntityTypeBuilder<CostCenter> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__cost_cen__3213E83FF8026CF8");

            entity.ToTable("cost_centers", "shared");

            entity.HasIndex(e => e.CompanyId, "cost_centers_company_id_5390b4ec");

            entity.HasIndex(e => new { e.CompanyId, e.Code }, "cost_centers_company_id_code_153ce7ab_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [code] IS NOT NULL)");

            entity.HasIndex(e => new { e.CompanyId, e.Name, e.ParentId }, "cost_centers_company_id_name_parent_id_44518991_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [name] IS NOT NULL AND [parent_id] IS NOT NULL)");

            entity.HasIndex(e => e.ParentId, "cost_centers_parent_id_eba90f6c");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AuthorizedUsers)
                .HasMaxLength(1000)
                .HasColumnName("authorized_users");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(18)
                .HasColumnName("code");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.LastLevel).HasColumnName("last_level");
            entity.Property(e => e.Level).HasColumnName("level");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ParentId).HasColumnName("parent_id");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("cost_centers_parent_id_eba90f6c_fk_cost_centers_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CostCenter> entity);
    }
}
