// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class FooConfiguration : IEntityTypeConfiguration<Foo>
    {
        public void Configure(EntityTypeBuilder<Foo> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__foos__3213E83F373F6C6C");

            entity.ToTable("foos", "shared");

            entity.HasIndex(e => e.CompanyId, "foos_company_id_1a5e3040");

            entity.HasIndex(e => e.ProductId, "foos_product_id_64577d3d");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Amount)
                .HasColumnType("numeric(10, 2)")
                .HasColumnName("amount");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("code");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.Count).HasColumnName("count");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.Text).HasColumnName("text");

            entity.HasOne(d => d.Product).WithMany(p => p.Foos)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("foos_product_id_64577d3d_fk_products_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Foo> entity);
    }
}
