// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class PersonGroupMemberConfiguration : IEntityTypeConfiguration<PersonGroupMember>
    {
        public void Configure(EntityTypeBuilder<PersonGroupMember> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__person_g__3213E83FDFED9134");

            entity.ToTable("person_group_members", "shared");

            entity.HasIndex(e => e.CompanyId, "person_group_members_company_id_730c5fff");

            entity.HasIndex(e => new { e.CompanyId, e.PersonGroupId, e.MemberId }, "person_group_members_company_id_person_group_id_member_id_b5c20e26_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [person_group_id] IS NOT NULL AND [member_id] IS NOT NULL)");

            entity.HasIndex(e => e.MemberId, "person_group_members_member_id_fb0c85d9");

            entity.HasIndex(e => e.PersonGroupId, "person_group_members_person_group_id_34698b20");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.MemberId).HasColumnName("member_id");
            entity.Property(e => e.PersonGroupId).HasColumnName("person_group_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonGroupMember> entity);
    }
}
