// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class PersonCompanyConfiguration : IEntityTypeConfiguration<PersonCompany>
    {
        public void Configure(EntityTypeBuilder<PersonCompany> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__person_c__3213E83F638FAE93");

            entity.ToTable("person_companies", "shared");

            entity.HasIndex(e => e.CompanyId, "person_companies_company_id_8d893c9c");

            entity.HasIndex(e => e.PersonId, "person_companies_person_id_01c9a592");

            entity.HasIndex(e => new { e.PersonId, e.CompanyId }, "person_companies_person_id_company_id_7ccc3e32_uniq")
                .IsUnique()
                .HasFilter("([person_id] IS NOT NULL AND [company_id] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.PersonId).HasColumnName("person_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonCompany> entity);
    }
}
