// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class PettyCashierConfiguration : IEntityTypeConfiguration<PettyCashier>
    {
        public void Configure(EntityTypeBuilder<PettyCashier> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__petty_ca__3213E83F7F5C9154");

            entity.ToTable("petty_cashiers", "shared");

            entity.HasIndex(e => e.CompanyId, "petty_cashiers_company_id_adaef187");

            entity.HasIndex(e => new { e.CompanyId, e.PersonId }, "petty_cashiers_company_id_person_id_d434ff7c_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [person_id] IS NOT NULL)");

            entity.HasIndex(e => e.CreatorId, "petty_cashiers_creator_id_d570b446");

            entity.HasIndex(e => e.PersonId, "petty_cashiers_person_id_5a0c025f");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AuthorizedUsers)
                .HasMaxLength(1000)
                .HasColumnName("authorized_users");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.PersonId).HasColumnName("person_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PettyCashier> entity);
    }
}
