// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class ReportTemplateConfiguration : IEntityTypeConfiguration<ReportTemplate>
    {
        public void Configure(EntityTypeBuilder<ReportTemplate> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__report_t__3213E83F0D6D3A08");

            entity.ToTable("report_templates", "shared");

            entity.HasIndex(e => e.CompanyId, "report_templates_company_id_d546fa98");

            entity.HasIndex(e => new { e.CompanyId, e.ReportKey, e.Name }, "report_templates_company_id_report_key_name_f3282f81_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [report_key] IS NOT NULL AND [name] IS NOT NULL)");

            entity.HasIndex(e => e.CreatorId, "report_templates_creator_id_1650956e");

            entity.HasIndex(e => e.ModuleId, "report_templates_module_id_e5a4ce8d");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.ReportKey)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("report_key");
            entity.Property(e => e.Template)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("template");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ReportTemplate> entity);
    }
}
