// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class RoleMemberConfiguration : IEntityTypeConfiguration<RoleMember>
    {
        public void Configure(EntityTypeBuilder<RoleMember> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__role_mem__3213E83FA3102DA6");

            entity.ToTable("role_members", "shared");

            entity.HasIndex(e => e.CompanyId, "role_members_company_id_c28413ce");

            entity.HasIndex(e => e.MemberId, "role_members_member_id_0a61f922");

            entity.HasIndex(e => e.RoleId, "role_members_role_id_3742ecb7");

            entity.HasIndex(e => new { e.RoleId, e.MemberId }, "role_members_role_id_member_id_22328589_uniq")
                .IsUnique()
                .HasFilter("([role_id] IS NOT NULL AND [member_id] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AuthorizedUsers)
                .HasMaxLength(1000)
                .HasColumnName("authorized_users");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.MemberId).HasColumnName("member_id");
            entity.Property(e => e.RoleId).HasColumnName("role_id");

            entity.HasOne(d => d.Role).WithMany(p => p.RoleMembers)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("role_members_role_id_3742ecb7_fk_roles_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RoleMember> entity);
    }
}
