// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class RolePermissionConfiguration : IEntityTypeConfiguration<RolePermission>
    {
        public void Configure(EntityTypeBuilder<RolePermission> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__role_per__3213E83FADCE6844");

            entity.ToTable("role_permissions", "shared");

            entity.HasIndex(e => e.EntityTypeId, "role_permissions_entity_type_id_74eb6fa5");

            entity.HasIndex(e => e.ModuleId, "role_permissions_module_id_f6701517");

            entity.HasIndex(e => e.RoleId, "role_permissions_role_id_216516f2");

            entity.HasIndex(e => new { e.RoleId, e.EntityTypeId }, "role_permissions_role_id_entity_type_id_285eba22_uniq")
                .IsUnique()
                .HasFilter("([role_id] IS NOT NULL AND [entity_type_id] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Create).HasColumnName("create");
            entity.Property(e => e.Delete).HasColumnName("delete");
            entity.Property(e => e.Edit).HasColumnName("edit");
            entity.Property(e => e.EntityTypeId).HasColumnName("entity_type_id");
            entity.Property(e => e.Exp).HasColumnName("exp");
            entity.Property(e => e.IfNotCreator).HasColumnName("if_not_creator");
            entity.Property(e => e.Imp).HasColumnName("imp");
            entity.Property(e => e.Log).HasColumnName("log");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.Print).HasColumnName("print");
            entity.Property(e => e.Read).HasColumnName("read");
            entity.Property(e => e.RoleId).HasColumnName("role_id");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePermissions)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("role_permissions_role_id_216516f2_fk_roles_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RolePermission> entity);
    }
}
