// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Shared.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Shared.Infrastructure.DataAccess.Configurations
{
    public partial class RolePermissionCommandConfiguration : IEntityTypeConfiguration<RolePermissionCommand>
    {
        public void Configure(EntityTypeBuilder<RolePermissionCommand> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__role_per__3213E83F15286D44");

            entity.ToTable("role_permission_commands", "shared");

            entity.HasIndex(e => e.EntityTypeCommandId, "role_permission_commands_entity_type_command_id_9e625b38");

            entity.HasIndex(e => e.EntityTypeId, "role_permission_commands_entity_type_id_a3513f52");

            entity.HasIndex(e => e.RoleId, "role_permission_commands_role_id_5d1758cb");

            entity.HasIndex(e => e.RolePermissionId, "role_permission_commands_role_permission_id_40a8626f");

            entity.HasIndex(e => new { e.RolePermissionId, e.EntityTypeCommandId }, "role_permission_commands_role_permission_id_entity_type_command_id_9f7be0a3_uniq")
                .IsUnique()
                .HasFilter("([role_permission_id] IS NOT NULL AND [entity_type_command_id] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CommandKey)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("command_key");
            entity.Property(e => e.EntityTypeCommandId).HasColumnName("entity_type_command_id");
            entity.Property(e => e.EntityTypeId).HasColumnName("entity_type_id");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.RolePermissionId).HasColumnName("role_permission_id");
            entity.Property(e => e.Value).HasColumnName("value");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePermissionCommands)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("role_permission_commands_role_id_5d1758cb_fk_roles_id");

            entity.HasOne(d => d.RolePermission).WithMany(p => p.RolePermissionCommands)
                .HasForeignKey(d => d.RolePermissionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("role_permission_commands_role_permission_id_40a8626f_fk_role_permissions_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RolePermissionCommand> entity);
    }
}
