// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class AccountSetItemConfiguration : IEntityTypeConfiguration<AccountSetItem>
    {
        public void Configure(EntityTypeBuilder<AccountSetItem> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__account___3213E83FA949F926");

            entity.ToTable("account_set_items", "accounting");

            entity.HasIndex(e => e.AccountSetId, "account_set_items_account_set_id_c6a49338");

            entity.HasIndex(e => new { e.AccountSetId, e.MasterId, e.SlaveId }, "account_set_items_account_set_id_master_id_slave_id_c5ba8c71_uniq")
                .IsUnique()
                .HasFilter("([account_set_id] IS NOT NULL AND [master_id] IS NOT NULL AND [slave_id] IS NOT NULL)");

            entity.HasIndex(e => e.MasterId, "account_set_items_master_id_e12671e4");

            entity.HasIndex(e => e.SlaveId, "account_set_items_slave_id_a5287d0f");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccountSetId).HasColumnName("account_set_id");
            entity.Property(e => e.MasterId).HasColumnName("master_id");
            entity.Property(e => e.SlaveId).HasColumnName("slave_id");

            entity.HasOne(d => d.AccountSet).WithMany(p => p.AccountSetItems)
                .HasForeignKey(d => d.AccountSetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("account_set_items_account_set_id_c6a49338_fk_account_sets_id");

            entity.HasOne(d => d.Master).WithMany(p => p.AccountSetItems)
                .HasForeignKey(d => d.MasterId)
                .HasConstraintName("account_set_items_master_id_e12671e4_fk_master_accounts_id");

            entity.HasOne(d => d.Slave).WithMany(p => p.AccountSetItems)
                .HasForeignKey(d => d.SlaveId)
                .HasConstraintName("account_set_items_slave_id_a5287d0f_fk_slave_accounts_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AccountSetItem> entity);
    }
}
