// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class BalanceRelatedAccountDetailConfiguration : IEntityTypeConfiguration<BalanceRelatedAccountDetail>
    {
        public void Configure(EntityTypeBuilder<BalanceRelatedAccountDetail> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__balance___3213E83F58334CF7");

            entity.ToTable("balance_related_account_details", "accounting");

            entity.HasIndex(e => e.BankBranchForPayableDocId, "balance_related_account_details_bank_branch_for_payable_doc_id_f62750bd");

            entity.HasIndex(e => e.BankBranchForReceivableDocId, "balance_related_account_details_bank_branch_for_receivable_doc_id_3f00ae31");

            entity.HasIndex(e => e.BankForPayableDocId, "balance_related_account_details_bank_for_payable_doc_id_a61b2771");

            entity.HasIndex(e => e.BankForReceivableDocId, "balance_related_account_details_bank_for_receivable_doc_id_6d949455");

            entity.HasIndex(e => e.BankOperationBankBranchId, "balance_related_account_details_bank_operation_bank_branch_id_b2e2213b");

            entity.HasIndex(e => e.BankOperationTypeId, "balance_related_account_details_bank_operation_type_id_12f7966f");

            entity.HasIndex(e => e.BranchId, "balance_related_account_details_branch_id_c4524e9e");

            entity.HasIndex(e => e.CompanyId, "balance_related_account_details_company_id_f90e854f");

            entity.HasIndex(e => e.CompanyUnitId, "balance_related_account_details_company_unit_id_a4a8a95f");

            entity.HasIndex(e => e.CostCenterId, "balance_related_account_details_cost_center_id_1cebfa10");

            entity.HasIndex(e => e.CurrencyId, "balance_related_account_details_currency_id_a94bd7cd");

            entity.HasIndex(e => e.LedgerId, "balance_related_account_details_ledger_id_1fcf3bc8");

            entity.HasIndex(e => e.ManualFloat1Id, "balance_related_account_details_manual_float_1_id_3cf4e319");

            entity.HasIndex(e => e.ManualFloat2Id, "balance_related_account_details_manual_float_2_id_79cca910");

            entity.HasIndex(e => e.ManualFloat3Id, "balance_related_account_details_manual_float_3_id_c7afe8b7");

            entity.HasIndex(e => e.ManualFloat4Id, "balance_related_account_details_manual_float_4_id_bba5925c");

            entity.HasIndex(e => e.ManualFloat5Id, "balance_related_account_details_manual_float_5_id_2f0ad7f7");

            entity.HasIndex(e => e.ManualFloat6Id, "balance_related_account_details_manual_float_6_id_eeaf3bf1");

            entity.HasIndex(e => e.ManualFloat7Id, "balance_related_account_details_manual_float_7_id_c140028e");

            entity.HasIndex(e => e.ManualFloat8Id, "balance_related_account_details_manual_float_8_id_68b0bdc0");

            entity.HasIndex(e => e.MasterId, "balance_related_account_details_master_id_f76438d4");

            entity.HasIndex(e => e.PeriodId, "balance_related_account_details_period_id_2b2d6794");

            entity.HasIndex(e => e.PersonId, "balance_related_account_details_person_id_e1e5844f");

            entity.HasIndex(e => e.ProjectContractId, "balance_related_account_details_project_contract_id_926e56be");

            entity.HasIndex(e => e.ProjectContractTypeId, "balance_related_account_details_project_contract_type_id_4819f840");

            entity.HasIndex(e => e.ProjectId, "balance_related_account_details_project_id_6072d815");

            entity.HasIndex(e => e.ResourceAndExpenditureId, "balance_related_account_details_resource_and_expenditure_id_78f2b804");

            entity.HasIndex(e => e.SlaveId, "balance_related_account_details_slave_id_8bf18f14");

            entity.HasIndex(e => e.StoreId, "balance_related_account_details_store_id_9f40ae42");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.BankBranchForPayableDocId).HasColumnName("bank_branch_for_payable_doc_id");
            entity.Property(e => e.BankBranchForReceivableDocId).HasColumnName("bank_branch_for_receivable_doc_id");
            entity.Property(e => e.BankForPayableDocId).HasColumnName("bank_for_payable_doc_id");
            entity.Property(e => e.BankForReceivableDocId).HasColumnName("bank_for_receivable_doc_id");
            entity.Property(e => e.BankOperationBankBranchId).HasColumnName("bank_operation_bank_branch_id");
            entity.Property(e => e.BankOperationCheckNo)
                .HasMaxLength(30)
                .HasColumnName("bank_operation_check_no");
            entity.Property(e => e.BankOperationDate).HasColumnName("bank_operation_date");
            entity.Property(e => e.BankOperationReceipt).HasColumnName("bank_operation_receipt");
            entity.Property(e => e.BankOperationTypeId).HasColumnName("bank_operation_type_id");
            entity.Property(e => e.BranchId).HasColumnName("branch_id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CompanyUnitCode).HasColumnName("company_unit_code");
            entity.Property(e => e.CompanyUnitId).HasColumnName("company_unit_id");
            entity.Property(e => e.CostCenterCode).HasColumnName("cost_center_code");
            entity.Property(e => e.CostCenterId).HasColumnName("cost_center_id");
            entity.Property(e => e.Credit).HasColumnName("credit");
            entity.Property(e => e.CurrencyAmount)
                .HasColumnType("numeric(24, 8)")
                .HasColumnName("currency_amount");
            entity.Property(e => e.CurrencyExchangeRate)
                .HasColumnType("numeric(20, 4)")
                .HasColumnName("currency_exchange_rate");
            entity.Property(e => e.CurrencyId).HasColumnName("currency_id");
            entity.Property(e => e.DealType).HasColumnName("deal_type");
            entity.Property(e => e.Debit).HasColumnName("debit");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.DueDate).HasColumnName("due_date");
            entity.Property(e => e.IsTick).HasColumnName("is_tick");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.ManualFloat1Extra1)
                .HasMaxLength(50)
                .HasColumnName("manual_float_1_extra_1");
            entity.Property(e => e.ManualFloat1Extra2)
                .HasMaxLength(50)
                .HasColumnName("manual_float_1_extra_2");
            entity.Property(e => e.ManualFloat1Extra3)
                .HasMaxLength(50)
                .HasColumnName("manual_float_1_extra_3");
            entity.Property(e => e.ManualFloat1Id).HasColumnName("manual_float_1_id");
            entity.Property(e => e.ManualFloat2Extra1)
                .HasMaxLength(50)
                .HasColumnName("manual_float_2_extra_1");
            entity.Property(e => e.ManualFloat2Extra2)
                .HasMaxLength(50)
                .HasColumnName("manual_float_2_extra_2");
            entity.Property(e => e.ManualFloat2Extra3)
                .HasMaxLength(50)
                .HasColumnName("manual_float_2_extra_3");
            entity.Property(e => e.ManualFloat2Id).HasColumnName("manual_float_2_id");
            entity.Property(e => e.ManualFloat3Extra1)
                .HasMaxLength(50)
                .HasColumnName("manual_float_3_extra_1");
            entity.Property(e => e.ManualFloat3Extra2)
                .HasMaxLength(50)
                .HasColumnName("manual_float_3_extra_2");
            entity.Property(e => e.ManualFloat3Extra3)
                .HasMaxLength(50)
                .HasColumnName("manual_float_3_extra_3");
            entity.Property(e => e.ManualFloat3Id).HasColumnName("manual_float_3_id");
            entity.Property(e => e.ManualFloat4Extra1)
                .HasMaxLength(50)
                .HasColumnName("manual_float_4_extra_1");
            entity.Property(e => e.ManualFloat4Extra2)
                .HasMaxLength(50)
                .HasColumnName("manual_float_4_extra_2");
            entity.Property(e => e.ManualFloat4Extra3)
                .HasMaxLength(50)
                .HasColumnName("manual_float_4_extra_3");
            entity.Property(e => e.ManualFloat4Id).HasColumnName("manual_float_4_id");
            entity.Property(e => e.ManualFloat5Extra1)
                .HasMaxLength(50)
                .HasColumnName("manual_float_5_extra_1");
            entity.Property(e => e.ManualFloat5Extra2)
                .HasMaxLength(50)
                .HasColumnName("manual_float_5_extra_2");
            entity.Property(e => e.ManualFloat5Extra3)
                .HasMaxLength(50)
                .HasColumnName("manual_float_5_extra_3");
            entity.Property(e => e.ManualFloat5Id).HasColumnName("manual_float_5_id");
            entity.Property(e => e.ManualFloat6Extra1)
                .HasMaxLength(50)
                .HasColumnName("manual_float_6_extra_1");
            entity.Property(e => e.ManualFloat6Extra2)
                .HasMaxLength(50)
                .HasColumnName("manual_float_6_extra_2");
            entity.Property(e => e.ManualFloat6Extra3)
                .HasMaxLength(50)
                .HasColumnName("manual_float_6_extra_3");
            entity.Property(e => e.ManualFloat6Id).HasColumnName("manual_float_6_id");
            entity.Property(e => e.ManualFloat7Extra1)
                .HasMaxLength(50)
                .HasColumnName("manual_float_7_extra_1");
            entity.Property(e => e.ManualFloat7Extra2)
                .HasMaxLength(50)
                .HasColumnName("manual_float_7_extra_2");
            entity.Property(e => e.ManualFloat7Extra3)
                .HasMaxLength(50)
                .HasColumnName("manual_float_7_extra_3");
            entity.Property(e => e.ManualFloat7Id).HasColumnName("manual_float_7_id");
            entity.Property(e => e.ManualFloat8Extra1)
                .HasMaxLength(50)
                .HasColumnName("manual_float_8_extra_1");
            entity.Property(e => e.ManualFloat8Extra2)
                .HasMaxLength(50)
                .HasColumnName("manual_float_8_extra_2");
            entity.Property(e => e.ManualFloat8Extra3)
                .HasMaxLength(50)
                .HasColumnName("manual_float_8_extra_3");
            entity.Property(e => e.ManualFloat8Id).HasColumnName("manual_float_8_id");
            entity.Property(e => e.MasterId).HasColumnName("master_id");
            entity.Property(e => e.PayableDocCheckNo)
                .HasMaxLength(30)
                .HasColumnName("payable_doc_check_no");
            entity.Property(e => e.PayableDocDate).HasColumnName("payable_doc_date");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.PersonId).HasColumnName("person_id");
            entity.Property(e => e.ProjectContractId).HasColumnName("project_contract_id");
            entity.Property(e => e.ProjectContractTypeId).HasColumnName("project_contract_type_id");
            entity.Property(e => e.ProjectDate).HasColumnName("project_date");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.ProjectReceipt).HasColumnName("project_receipt");
            entity.Property(e => e.ProjectStatusReport)
                .HasMaxLength(30)
                .HasColumnName("project_status_report");
            entity.Property(e => e.ReceivableDocCheckNo)
                .HasMaxLength(30)
                .HasColumnName("receivable_doc_check_no");
            entity.Property(e => e.ReceivableDocDate).HasColumnName("receivable_doc_date");
            entity.Property(e => e.ResourceAndExpenditureId).HasColumnName("resource_and_expenditure_id");
            entity.Property(e => e.SlaveId).HasColumnName("slave_id");
            entity.Property(e => e.StoreDocType)
                .HasMaxLength(20)
                .HasColumnName("store_doc_type");
            entity.Property(e => e.StoreGoodCode).HasColumnName("store_good_code");
            entity.Property(e => e.StoreGoodQuantity)
                .HasColumnType("numeric(16, 4)")
                .HasColumnName("store_good_quantity");
            entity.Property(e => e.StoreGoodUnitPrice)
                .HasColumnType("numeric(20, 6)")
                .HasColumnName("store_good_unit_price");
            entity.Property(e => e.StoreId).HasColumnName("store_id");

            entity.HasOne(d => d.Ledger).WithMany(p => p.BalanceRelatedAccountDetails)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("balance_related_account_details_ledger_id_1fcf3bc8_fk_ledgers_id");

            entity.HasOne(d => d.ManualFloat1).WithMany(p => p.BalanceRelatedAccountDetailManualFloat1s)
                .HasForeignKey(d => d.ManualFloat1Id)
                .HasConstraintName("balance_related_account_details_manual_float_1_id_3cf4e319_fk_manual_float_accounts_id");

            entity.HasOne(d => d.ManualFloat2).WithMany(p => p.BalanceRelatedAccountDetailManualFloat2s)
                .HasForeignKey(d => d.ManualFloat2Id)
                .HasConstraintName("balance_related_account_details_manual_float_2_id_79cca910_fk_manual_float_accounts_id");

            entity.HasOne(d => d.ManualFloat3).WithMany(p => p.BalanceRelatedAccountDetailManualFloat3s)
                .HasForeignKey(d => d.ManualFloat3Id)
                .HasConstraintName("balance_related_account_details_manual_float_3_id_c7afe8b7_fk_manual_float_accounts_id");

            entity.HasOne(d => d.ManualFloat4).WithMany(p => p.BalanceRelatedAccountDetailManualFloat4s)
                .HasForeignKey(d => d.ManualFloat4Id)
                .HasConstraintName("balance_related_account_details_manual_float_4_id_bba5925c_fk_manual_float_accounts_id");

            entity.HasOne(d => d.ManualFloat5).WithMany(p => p.BalanceRelatedAccountDetailManualFloat5s)
                .HasForeignKey(d => d.ManualFloat5Id)
                .HasConstraintName("balance_related_account_details_manual_float_5_id_2f0ad7f7_fk_manual_float_accounts_id");

            entity.HasOne(d => d.ManualFloat6).WithMany(p => p.BalanceRelatedAccountDetailManualFloat6s)
                .HasForeignKey(d => d.ManualFloat6Id)
                .HasConstraintName("balance_related_account_details_manual_float_6_id_eeaf3bf1_fk_manual_float_accounts_id");

            entity.HasOne(d => d.ManualFloat7).WithMany(p => p.BalanceRelatedAccountDetailManualFloat7s)
                .HasForeignKey(d => d.ManualFloat7Id)
                .HasConstraintName("balance_related_account_details_manual_float_7_id_c140028e_fk_manual_float_accounts_id");

            entity.HasOne(d => d.ManualFloat8).WithMany(p => p.BalanceRelatedAccountDetailManualFloat8s)
                .HasForeignKey(d => d.ManualFloat8Id)
                .HasConstraintName("balance_related_account_details_manual_float_8_id_68b0bdc0_fk_manual_float_accounts_id");

            entity.HasOne(d => d.Master).WithMany(p => p.BalanceRelatedAccountDetails)
                .HasForeignKey(d => d.MasterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("balance_related_account_details_master_id_f76438d4_fk_master_accounts_id");

            entity.HasOne(d => d.Period).WithMany(p => p.BalanceRelatedAccountDetails)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("balance_related_account_details_period_id_2b2d6794_fk_periods_id");

            entity.HasOne(d => d.ResourceAndExpenditure).WithMany(p => p.BalanceRelatedAccountDetails)
                .HasForeignKey(d => d.ResourceAndExpenditureId)
                .HasConstraintName("balance_related_account_details_resource_and_expenditure_id_78f2b804_fk_resource_and_expenditures_id");

            entity.HasOne(d => d.Slave).WithMany(p => p.BalanceRelatedAccountDetails)
                .HasForeignKey(d => d.SlaveId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("balance_related_account_details_slave_id_8bf18f14_fk_slave_accounts_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BalanceRelatedAccountDetail> entity);
    }
}
