// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class BankTemplateConfiguration : IEntityTypeConfiguration<BankTemplate>
    {
        public void Configure(EntityTypeBuilder<BankTemplate> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__bank_tem__3213E83FBE9F31D0");

            entity.ToTable("bank_templates", "accounting");

            entity.HasIndex(e => e.CompanyId, "bank_templates_company_id_2c793700");

            entity.HasIndex(e => e.CreatorId, "bank_templates_creator_id_3c99db7f");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ReportKey)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("report_key");
            entity.Property(e => e.Template)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("template");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BankTemplate> entity);
    }
}
