// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class ClosingPatternSlaveCompanyConfiguration : IEntityTypeConfiguration<ClosingPatternSlaveCompany>
    {
        public void Configure(EntityTypeBuilder<ClosingPatternSlaveCompany> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__closing___3213E83F69E4AA3B");

            entity.ToTable("closing_pattern_slave_companies", "accounting");

            entity.HasIndex(e => e.CompanyId, "closing_pattern_slave_companies_company_id_d40fc855");

            entity.HasIndex(e => new { e.CompanyId, e.LedgerId, e.PeriodId, e.SlaveCompanyId }, "closing_pattern_slave_companies_company_id_ledger_id_period_id_slave_company_id_772b00bd_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [ledger_id] IS NOT NULL AND [period_id] IS NOT NULL AND [slave_company_id] IS NOT NULL)");

            entity.HasIndex(e => e.DefaultCashierPeriodId, "closing_pattern_slave_companies_default_cashier_period_id_92a586f2");

            entity.HasIndex(e => e.DefaultCompanyUnitId, "closing_pattern_slave_companies_default_company_unit_id_2c7875df");

            entity.HasIndex(e => e.DefaultCurrencyId, "closing_pattern_slave_companies_default_currency_id_8d86bb77");

            entity.HasIndex(e => e.DefaultPersonId, "closing_pattern_slave_companies_default_person_id_94d4611e");

            entity.HasIndex(e => e.DefaultPettyCashierPeriodId, "closing_pattern_slave_companies_default_petty_cashier_period_id_6135e6e8");

            entity.HasIndex(e => e.DefaultProjectId, "closing_pattern_slave_companies_default_project_id_becc3a53");

            entity.HasIndex(e => e.DefaultResourceAndExpenditureId, "closing_pattern_slave_companies_default_resource_and_expenditure_id_d8808ca1");

            entity.HasIndex(e => e.DefaultStoreId, "closing_pattern_slave_companies_default_store_id_2b4de0c5");

            entity.HasIndex(e => e.LedgerId, "closing_pattern_slave_companies_ledger_id_b7344906");

            entity.HasIndex(e => e.PeriodId, "closing_pattern_slave_companies_period_id_7d4ec4d3");

            entity.HasIndex(e => e.SlaveCompanyId, "closing_pattern_slave_companies_slave_company_id_e971e36e");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.DefaultCashierPeriodId).HasColumnName("default_cashier_period_id");
            entity.Property(e => e.DefaultCompanyUnitId).HasColumnName("default_company_unit_id");
            entity.Property(e => e.DefaultCurrencyId).HasColumnName("default_currency_id");
            entity.Property(e => e.DefaultPersonId).HasColumnName("default_person_id");
            entity.Property(e => e.DefaultPettyCashierPeriodId).HasColumnName("default_petty_cashier_period_id");
            entity.Property(e => e.DefaultProjectId).HasColumnName("default_project_id");
            entity.Property(e => e.DefaultResourceAndExpenditureId).HasColumnName("default_resource_and_expenditure_id");
            entity.Property(e => e.DefaultStoreId).HasColumnName("default_store_id");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.SlaveCompanyId).HasColumnName("slave_company_id");

            entity.HasOne(d => d.DefaultResourceAndExpenditure).WithMany(p => p.ClosingPatternSlaveCompanies)
                .HasForeignKey(d => d.DefaultResourceAndExpenditureId)
                .HasConstraintName("closing_pattern_slave_companies_default_resource_and_expenditure_id_d8808ca1_fk_resource_and_expenditures_id");

            entity.HasOne(d => d.Ledger).WithMany(p => p.ClosingPatternSlaveCompanies)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("closing_pattern_slave_companies_ledger_id_b7344906_fk_ledgers_id");

            entity.HasOne(d => d.Period).WithMany(p => p.ClosingPatternSlaveCompanies)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("closing_pattern_slave_companies_period_id_7d4ec4d3_fk_periods_id");

            entity.HasOne(d => d.SlaveCompany).WithMany(p => p.ClosingPatternSlaveCompanies)
                .HasForeignKey(d => d.SlaveCompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("closing_pattern_slave_companies_slave_company_id_e971e36e_fk_slave_account_companies_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClosingPatternSlaveCompany> entity);
    }
}
