// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class ClosingPatternConfiguration : IEntityTypeConfiguration<ClosingPattern>
    {
        public void Configure(EntityTypeBuilder<ClosingPattern> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__closing___3213E83FF2309BF5");

            entity.ToTable("closing_patterns", "accounting");

            entity.HasIndex(e => e.CompanyId, "closing_patterns_company_id_9cd07d27");

            entity.HasIndex(e => new { e.CompanyId, e.LedgerId, e.PeriodId, e.FloatTypeSet }, "closing_patterns_company_id_ledger_id_period_id_float_type_set_70e51708_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [ledger_id] IS NOT NULL AND [period_id] IS NOT NULL AND [float_type_set] IS NOT NULL)");

            entity.HasIndex(e => e.DefaultCashierPeriodId, "closing_patterns_default_cashier_period_id_2116c839");

            entity.HasIndex(e => e.DefaultCompanyUnitId, "closing_patterns_default_company_unit_id_b57cd2d3");

            entity.HasIndex(e => e.DefaultCurrencyId, "closing_patterns_default_currency_id_efd08b2d");

            entity.HasIndex(e => e.DefaultPersonId, "closing_patterns_default_person_id_d1e830cb");

            entity.HasIndex(e => e.DefaultPettyCashierPeriodId, "closing_patterns_default_petty_cashier_period_id_8d44d43e");

            entity.HasIndex(e => e.DefaultProjectId, "closing_patterns_default_project_id_354a5095");

            entity.HasIndex(e => e.DefaultResourceAndExpenditureId, "closing_patterns_default_resource_and_expenditure_id_6ef35f22");

            entity.HasIndex(e => e.DefaultStoreId, "closing_patterns_default_store_id_0f67c8c0");

            entity.HasIndex(e => e.LedgerId, "closing_patterns_ledger_id_394ee754");

            entity.HasIndex(e => e.PeriodId, "closing_patterns_period_id_8a00d0d0");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.DefaultCashierPeriodId).HasColumnName("default_cashier_period_id");
            entity.Property(e => e.DefaultCompanyUnitId).HasColumnName("default_company_unit_id");
            entity.Property(e => e.DefaultCurrencyId).HasColumnName("default_currency_id");
            entity.Property(e => e.DefaultPersonId).HasColumnName("default_person_id");
            entity.Property(e => e.DefaultPettyCashierPeriodId).HasColumnName("default_petty_cashier_period_id");
            entity.Property(e => e.DefaultProjectId).HasColumnName("default_project_id");
            entity.Property(e => e.DefaultResourceAndExpenditureId).HasColumnName("default_resource_and_expenditure_id");
            entity.Property(e => e.DefaultStoreId).HasColumnName("default_store_id");
            entity.Property(e => e.FloatTypeSet)
                .IsRequired()
                .HasMaxLength(18)
                .HasColumnName("float_type_set");
            entity.Property(e => e.IsSet).HasColumnName("is_set");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");

            entity.HasOne(d => d.DefaultResourceAndExpenditure).WithMany(p => p.ClosingPatterns)
                .HasForeignKey(d => d.DefaultResourceAndExpenditureId)
                .HasConstraintName("closing_patterns_default_resource_and_expenditure_id_6ef35f22_fk_resource_and_expenditures_id");

            entity.HasOne(d => d.Ledger).WithMany(p => p.ClosingPatterns)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("closing_patterns_ledger_id_394ee754_fk_ledgers_id");

            entity.HasOne(d => d.Period).WithMany(p => p.ClosingPatterns)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("closing_patterns_period_id_8a00d0d0_fk_periods_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClosingPattern> entity);
    }
}
