// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class ClosingPatternTemporaryAccountConfiguration : IEntityTypeConfiguration<ClosingPatternTemporaryAccount>
    {
        public void Configure(EntityTypeBuilder<ClosingPatternTemporaryAccount> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__closing___3213E83F56719B0B");

            entity.ToTable("closing_pattern_temporary_accounts", "accounting");

            entity.HasIndex(e => e.CompanyId, "closing_pattern_temporary_accounts_company_id_952b9b60");

            entity.HasIndex(e => new { e.CompanyId, e.LedgerId, e.PeriodId, e.FloatTypeSet }, "closing_pattern_temporary_accounts_company_id_ledger_id_period_id_float_type_set_2bc966ac_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [ledger_id] IS NOT NULL AND [period_id] IS NOT NULL AND [float_type_set] IS NOT NULL)");

            entity.HasIndex(e => e.DefaultCashierPeriodId, "closing_pattern_temporary_accounts_default_cashier_period_id_d8091266");

            entity.HasIndex(e => e.DefaultCompanyUnitId, "closing_pattern_temporary_accounts_default_company_unit_id_086a631a");

            entity.HasIndex(e => e.DefaultCostCenterId, "closing_pattern_temporary_accounts_default_cost_center_id_76aab24b");

            entity.HasIndex(e => e.DefaultCurrencyId, "closing_pattern_temporary_accounts_default_currency_id_2f9de639");

            entity.HasIndex(e => e.DefaultPersonId, "closing_pattern_temporary_accounts_default_person_id_a4961ab4");

            entity.HasIndex(e => e.DefaultPettyCashierPeriodId, "closing_pattern_temporary_accounts_default_petty_cashier_period_id_4d49f688");

            entity.HasIndex(e => e.DefaultProjectId, "closing_pattern_temporary_accounts_default_project_id_bbbb80e7");

            entity.HasIndex(e => e.DefaultResourceAndExpenditureId, "closing_pattern_temporary_accounts_default_resource_and_expenditure_id_dcf3d48a");

            entity.HasIndex(e => e.DefaultStoreId, "closing_pattern_temporary_accounts_default_store_id_43427fea");

            entity.HasIndex(e => e.LedgerId, "closing_pattern_temporary_accounts_ledger_id_8d2baceb");

            entity.HasIndex(e => e.PeriodId, "closing_pattern_temporary_accounts_period_id_897435aa");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.DefaultCashierPeriodId).HasColumnName("default_cashier_period_id");
            entity.Property(e => e.DefaultCompanyUnitId).HasColumnName("default_company_unit_id");
            entity.Property(e => e.DefaultCostCenterId).HasColumnName("default_cost_center_id");
            entity.Property(e => e.DefaultCurrencyId).HasColumnName("default_currency_id");
            entity.Property(e => e.DefaultPersonId).HasColumnName("default_person_id");
            entity.Property(e => e.DefaultPettyCashierPeriodId).HasColumnName("default_petty_cashier_period_id");
            entity.Property(e => e.DefaultProjectId).HasColumnName("default_project_id");
            entity.Property(e => e.DefaultResourceAndExpenditureId).HasColumnName("default_resource_and_expenditure_id");
            entity.Property(e => e.DefaultStoreId).HasColumnName("default_store_id");
            entity.Property(e => e.FloatTypeSet)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("float_type_set");
            entity.Property(e => e.IsSet).HasColumnName("is_set");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");

            entity.HasOne(d => d.DefaultResourceAndExpenditure).WithMany(p => p.ClosingPatternTemporaryAccounts)
                .HasForeignKey(d => d.DefaultResourceAndExpenditureId)
                .HasConstraintName("closing_pattern_temporary_accounts_default_resource_and_expenditure_id_dcf3d48a_fk_resource_and_expenditures_id");

            entity.HasOne(d => d.Ledger).WithMany(p => p.ClosingPatternTemporaryAccounts)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("closing_pattern_temporary_accounts_ledger_id_8d2baceb_fk_ledgers_id");

            entity.HasOne(d => d.Period).WithMany(p => p.ClosingPatternTemporaryAccounts)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("closing_pattern_temporary_accounts_period_id_897435aa_fk_periods_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClosingPatternTemporaryAccount> entity);
    }
}
