// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class ContradictionConfiguration : IEntityTypeConfiguration<Contradiction>
    {
        public void Configure(EntityTypeBuilder<Contradiction> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__contradi__3213E83FC9BAF683");

            entity.ToTable("contradictions", "accounting");

            entity.HasIndex(e => e.BankAccountId, "contradictions_bank_account_id_e4432ed1");

            entity.HasIndex(e => e.CompanyId, "contradictions_company_id_f68c3f68");

            entity.HasIndex(e => e.CreatorId, "contradictions_creator_id_430d02a0");

            entity.HasIndex(e => e.DataImportId, "contradictions_data_import_id_65a4748b");

            entity.HasIndex(e => e.LedgerId, "contradictions_ledger_id_85776d2a");

            entity.HasIndex(e => e.PeriodId, "contradictions_period_id_538ee815");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.BankAccountId).HasColumnName("bank_account_id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.DataImportId).HasColumnName("data_import_id");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");

            entity.HasOne(d => d.DataImport).WithMany(p => p.Contradictions)
                .HasForeignKey(d => d.DataImportId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("contradictions_data_import_id_65a4748b_fk_data_imports_id");

            entity.HasOne(d => d.Ledger).WithMany(p => p.Contradictions)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("contradictions_ledger_id_85776d2a_fk_ledgers_id");

            entity.HasOne(d => d.Period).WithMany(p => p.Contradictions)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("contradictions_period_id_538ee815_fk_periods_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Contradiction> entity);
    }
}
