// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class ContradictionItemConfiguration : IEntityTypeConfiguration<ContradictionItem>
    {
        public void Configure(EntityTypeBuilder<ContradictionItem> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__contradi__3213E83F1C73FCF1");

            entity.ToTable("contradiction_items", "accounting");

            entity.HasIndex(e => e.ContradictionId, "contradiction_items_contradiction_id_1494f375");

            entity.HasIndex(e => e.CreatorId, "contradiction_items_creator_id_ee0be02e");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ContradictionId).HasColumnName("contradiction_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.Credit).HasColumnName("credit");
            entity.Property(e => e.Debit).HasColumnName("debit");
            entity.Property(e => e.DocDate).HasColumnName("doc_date");
            entity.Property(e => e.DocNo)
                .HasMaxLength(30)
                .HasColumnName("doc_no");
            entity.Property(e => e.IsTick).HasColumnName("is_tick");

            entity.HasOne(d => d.Contradiction).WithMany(p => p.ContradictionItems)
                .HasForeignKey(d => d.ContradictionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("contradiction_items_contradiction_id_1494f375_fk_contradictions_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContradictionItem> entity);
    }
}
