// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class LedgerConfiguration : IEntityTypeConfiguration<Ledger>
    {
        public void Configure(EntityTypeBuilder<Ledger> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__ledgers__3213E83F7B5B3C2B");

            entity.ToTable("ledgers", "accounting");

            entity.HasIndex(e => e.Code, "UQ__ledgers__357D4CF92E60519D").IsUnique();

            entity.HasIndex(e => e.Name, "UQ__ledgers__72E12F1B2CE796EF").IsUnique();

            entity.HasIndex(e => e.Name2, "UQ__ledgers__F0B628432B41C06C").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.IsLeading).HasColumnName("is_leading");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Name2)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name2");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Ledger> entity);
    }
}
