// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class LedgerPeriodConfiguration : IEntityTypeConfiguration<LedgerPeriod>
    {
        public void Configure(EntityTypeBuilder<LedgerPeriod> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__ledger_p__3213E83FCD7E44E8");

            entity.ToTable("ledger_periods", "accounting");

            entity.HasIndex(e => e.LedgerId, "ledger_periods_ledger_id_c70ff025");

            entity.HasIndex(e => new { e.LedgerId, e.PeriodId }, "ledger_periods_ledger_id_period_id_5d05e0eb_uniq")
                .IsUnique()
                .HasFilter("([ledger_id] IS NOT NULL AND [period_id] IS NOT NULL)");

            entity.HasIndex(e => e.PeriodId, "ledger_periods_period_id_2953e5ba");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");

            entity.HasOne(d => d.Ledger).WithMany(p => p.LedgerPeriods)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ledger_periods_ledger_id_c70ff025_fk_ledgers_id");

            entity.HasOne(d => d.Period).WithMany(p => p.LedgerPeriods)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ledger_periods_period_id_2953e5ba_fk_periods_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LedgerPeriod> entity);
    }
}
