// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class ManualFloatAccountConfiguration : IEntityTypeConfiguration<ManualFloatAccount>
    {
        public void Configure(EntityTypeBuilder<ManualFloatAccount> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__manual_f__3213E83F79B8ADA2");

            entity.ToTable("manual_float_accounts", "accounting");

            entity.HasIndex(e => e.CompanyId, "manual_float_accounts_company_id_c4223ce2");

            entity.HasIndex(e => new { e.CompanyId, e.FloatAccountTypeId, e.Code }, "manual_float_accounts_company_id_float_account_type_id_code_7e28c5e8_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [float_account_type_id] IS NOT NULL AND [code] IS NOT NULL)");

            entity.HasIndex(e => new { e.CompanyId, e.FloatAccountTypeId, e.Title2 }, "manual_float_accounts_company_id_float_account_type_id_title2_11d5aa07_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [float_account_type_id] IS NOT NULL AND [title2] IS NOT NULL)");

            entity.HasIndex(e => new { e.CompanyId, e.FloatAccountTypeId, e.Title }, "manual_float_accounts_company_id_float_account_type_id_title_ad80fe99_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [float_account_type_id] IS NOT NULL AND [title] IS NOT NULL)");

            entity.HasIndex(e => e.FloatAccountTypeId, "manual_float_accounts_float_account_type_id_b211d188");

            entity.HasIndex(e => e.ParentId, "manual_float_accounts_parent_id_4b9bca91");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AuthorizedUsers)
                .HasMaxLength(1000)
                .HasColumnName("authorized_users");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.Description)
                .HasMaxLength(200)
                .HasColumnName("description");
            entity.Property(e => e.FloatAccountTypeId).HasColumnName("float_account_type_id");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.ParentId).HasColumnName("parent_id");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("title");
            entity.Property(e => e.Title2)
                .HasMaxLength(100)
                .HasColumnName("title2");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.FloatAccountType).WithMany(p => p.ManualFloatAccounts)
                .HasForeignKey(d => d.FloatAccountTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("manual_float_accounts_float_account_type_id_b211d188_fk_float_account_types_id");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("manual_float_accounts_parent_id_4b9bca91_fk_manual_float_accounts_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ManualFloatAccount> entity);
    }
}
