// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class MasterAccountConfiguration : IEntityTypeConfiguration<MasterAccount>
    {
        public void Configure(EntityTypeBuilder<MasterAccount> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__master_a__3213E83FDB1E8845");

            entity.ToTable("master_accounts", "accounting");

            entity.HasIndex(e => e.LedgerId, "master_accounts_ledger_id_b94026a2");

            entity.HasIndex(e => new { e.LedgerId, e.Code }, "master_accounts_ledger_id_code_7b97c8b2_uniq")
                .IsUnique()
                .HasFilter("([ledger_id] IS NOT NULL AND [code] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AuthorizedUsers)
                .HasMaxLength(1000)
                .HasColumnName("authorized_users");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("title");
            entity.Property(e => e.Title2)
                .HasMaxLength(100)
                .HasColumnName("title2");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.Ledger).WithMany(p => p.MasterAccounts)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("master_accounts_ledger_id_b94026a2_fk_ledgers_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MasterAccount> entity);
    }
}
