// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class ResourceAndExpenditureConfiguration : IEntityTypeConfiguration<ResourceAndExpenditure>
    {
        public void Configure(EntityTypeBuilder<ResourceAndExpenditure> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__resource__3213E83FDA45EACF");

            entity.ToTable("resource_and_expenditures", "accounting");

            entity.HasIndex(e => e.CompanyId, "resource_and_expenditures_company_id_5d08b6e8");

            entity.HasIndex(e => new { e.CompanyId, e.Code }, "resource_and_expenditures_company_id_code_75192806_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [code] IS NOT NULL)");

            entity.HasIndex(e => new { e.CompanyId, e.Name }, "resource_and_expenditures_company_id_name_1605dd8e_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [name] IS NOT NULL)");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AuthorizedUsers)
                .HasMaxLength(1000)
                .HasColumnName("authorized_users");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(11)
                .HasColumnName("type");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ResourceAndExpenditure> entity);
    }
}
