// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class SlaveAccountCompanyConfiguration : IEntityTypeConfiguration<SlaveAccountCompany>
    {
        public void Configure(EntityTypeBuilder<SlaveAccountCompany> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__slave_ac__3213E83FA1D7EC62");

            entity.ToTable("slave_account_companies", "accounting");

            entity.HasIndex(e => e.CompanyId, "slave_account_companies_company_id_10f63c16");

            entity.HasIndex(e => e.FloatType1Id, "slave_account_companies_float_type_1_id_dcee560d");

            entity.HasIndex(e => e.FloatType2Id, "slave_account_companies_float_type_2_id_c218860a");

            entity.HasIndex(e => e.FloatType3Id, "slave_account_companies_float_type_3_id_653411c6");

            entity.HasIndex(e => e.FloatType4Id, "slave_account_companies_float_type_4_id_57254460");

            entity.HasIndex(e => e.FloatType5Id, "slave_account_companies_float_type_5_id_896ccdfc");

            entity.HasIndex(e => e.FloatType6Id, "slave_account_companies_float_type_6_id_a486a7f8");

            entity.HasIndex(e => e.FloatType7Id, "slave_account_companies_float_type_7_id_f5d8293e");

            entity.HasIndex(e => e.FloatType8Id, "slave_account_companies_float_type_8_id_ab2b63c8");

            entity.HasIndex(e => e.LedgerId, "slave_account_companies_ledger_id_b40ad4d0");

            entity.HasIndex(e => e.MasterId, "slave_account_companies_master_id_bacd3012");

            entity.HasIndex(e => new { e.SlaveId, e.CompanyId }, "slave_account_companies_slave_id_company_id_d7bc5f10_uniq")
                .IsUnique()
                .HasFilter("([slave_id] IS NOT NULL AND [company_id] IS NOT NULL)");

            entity.HasIndex(e => e.SlaveId, "slave_account_companies_slave_id_edd3dcf5");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AuthorizedUsers)
                .HasMaxLength(1000)
                .HasColumnName("authorized_users");
            entity.Property(e => e.Budget).HasColumnName("budget");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.DealType).HasColumnName("deal_type");
            entity.Property(e => e.DueDate).HasColumnName("due_date");
            entity.Property(e => e.FloatType1Id).HasColumnName("float_type_1_id");
            entity.Property(e => e.FloatType2Id).HasColumnName("float_type_2_id");
            entity.Property(e => e.FloatType3Id).HasColumnName("float_type_3_id");
            entity.Property(e => e.FloatType4Id).HasColumnName("float_type_4_id");
            entity.Property(e => e.FloatType5Id).HasColumnName("float_type_5_id");
            entity.Property(e => e.FloatType6Id).HasColumnName("float_type_6_id");
            entity.Property(e => e.FloatType7Id).HasColumnName("float_type_7_id");
            entity.Property(e => e.FloatType8Id).HasColumnName("float_type_8_id");
            entity.Property(e => e.FloatTypeSet)
                .HasMaxLength(100)
                .HasColumnName("float_type_set");
            entity.Property(e => e.FloatTypes)
                .HasMaxLength(100)
                .HasColumnName("float_types");
            entity.Property(e => e.HasAbsoluteDealType).HasColumnName("has_absolute_deal_type");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.MasterId).HasColumnName("master_id");
            entity.Property(e => e.NeedTtms).HasColumnName("need_ttms");
            entity.Property(e => e.SlaveId).HasColumnName("slave_id");
            entity.Property(e => e.Tag1)
                .HasMaxLength(15)
                .HasColumnName("tag1");
            entity.Property(e => e.Tag2)
                .HasMaxLength(15)
                .HasColumnName("tag2");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.FloatType1).WithMany(p => p.SlaveAccountCompanyFloatType1s)
                .HasForeignKey(d => d.FloatType1Id)
                .HasConstraintName("slave_account_companies_float_type_1_id_dcee560d_fk_float_account_types_id");

            entity.HasOne(d => d.FloatType2).WithMany(p => p.SlaveAccountCompanyFloatType2s)
                .HasForeignKey(d => d.FloatType2Id)
                .HasConstraintName("slave_account_companies_float_type_2_id_c218860a_fk_float_account_types_id");

            entity.HasOne(d => d.FloatType3).WithMany(p => p.SlaveAccountCompanyFloatType3s)
                .HasForeignKey(d => d.FloatType3Id)
                .HasConstraintName("slave_account_companies_float_type_3_id_653411c6_fk_float_account_types_id");

            entity.HasOne(d => d.FloatType4).WithMany(p => p.SlaveAccountCompanyFloatType4s)
                .HasForeignKey(d => d.FloatType4Id)
                .HasConstraintName("slave_account_companies_float_type_4_id_57254460_fk_float_account_types_id");

            entity.HasOne(d => d.FloatType5).WithMany(p => p.SlaveAccountCompanyFloatType5s)
                .HasForeignKey(d => d.FloatType5Id)
                .HasConstraintName("slave_account_companies_float_type_5_id_896ccdfc_fk_float_account_types_id");

            entity.HasOne(d => d.FloatType6).WithMany(p => p.SlaveAccountCompanyFloatType6s)
                .HasForeignKey(d => d.FloatType6Id)
                .HasConstraintName("slave_account_companies_float_type_6_id_a486a7f8_fk_float_account_types_id");

            entity.HasOne(d => d.FloatType7).WithMany(p => p.SlaveAccountCompanyFloatType7s)
                .HasForeignKey(d => d.FloatType7Id)
                .HasConstraintName("slave_account_companies_float_type_7_id_f5d8293e_fk_float_account_types_id");

            entity.HasOne(d => d.FloatType8).WithMany(p => p.SlaveAccountCompanyFloatType8s)
                .HasForeignKey(d => d.FloatType8Id)
                .HasConstraintName("slave_account_companies_float_type_8_id_ab2b63c8_fk_float_account_types_id");

            entity.HasOne(d => d.Ledger).WithMany(p => p.SlaveAccountCompanies)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("slave_account_companies_ledger_id_b40ad4d0_fk_ledgers_id");

            entity.HasOne(d => d.Master).WithMany(p => p.SlaveAccountCompanies)
                .HasForeignKey(d => d.MasterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("slave_account_companies_master_id_bacd3012_fk_master_accounts_id");

            entity.HasOne(d => d.Slave).WithMany(p => p.SlaveAccountCompanies)
                .HasForeignKey(d => d.SlaveId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("slave_account_companies_slave_id_edd3dcf5_fk_slave_accounts_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SlaveAccountCompany> entity);
    }
}
