// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class SlaveAccountConfiguration : IEntityTypeConfiguration<SlaveAccount>
    {
        public void Configure(EntityTypeBuilder<SlaveAccount> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__slave_ac__3213E83FA165931F");

            entity.ToTable("slave_accounts", "accounting");

            entity.HasIndex(e => e.CategoryId, "slave_accounts_category_id_79276cde");

            entity.HasIndex(e => new { e.CategoryId, e.GroupId, e.LedgerId, e.MasterId, e.Code, e.DetailedAccount1 }, "slave_accounts_category_id_group_id_ledger_id_master_id_code_detailed_account_1_2ebf0ffa_uniq")
                .IsUnique()
                .HasFilter("([category_id] IS NOT NULL AND [group_id] IS NOT NULL AND [ledger_id] IS NOT NULL AND [master_id] IS NOT NULL AND [code] IS NOT NULL AND [detailed_account_1] IS NOT NULL)");

            entity.HasIndex(e => new { e.CategoryId, e.GroupId, e.LedgerId, e.MasterId, e.Code, e.DetailedAccount1, e.DetailedAccount2 }, "slave_accounts_category_id_group_id_ledger_id_master_id_code_detailed_account_1_detailed_account_2_1409df48_uniq")
                .IsUnique()
                .HasFilter("([category_id] IS NOT NULL AND [group_id] IS NOT NULL AND [ledger_id] IS NOT NULL AND [master_id] IS NOT NULL AND [code] IS NOT NULL AND [detailed_account_1] IS NOT NULL AND [detailed_account_2] IS NOT NULL)");

            entity.HasIndex(e => e.FromCompanyIdId, "slave_accounts_from_company_id_id_be582ecc");

            entity.HasIndex(e => e.GroupId, "slave_accounts_group_id_d226c356");

            entity.HasIndex(e => e.LedgerId, "slave_accounts_ledger_id_e9bba48c");

            entity.HasIndex(e => e.MasterId, "slave_accounts_master_id_d8364647");

            entity.HasIndex(e => e.ParentId, "slave_accounts_parent_id_b5e3fe05");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.ClosingType)
                .IsRequired()
                .HasMaxLength(13)
                .HasColumnName("closing_type");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.DetailedAccount1).HasColumnName("detailed_account_1");
            entity.Property(e => e.DetailedAccount2).HasColumnName("detailed_account_2");
            entity.Property(e => e.FromCompanyIdId).HasColumnName("from_company_id_id");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.LastLevel).HasColumnName("last_level");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.Level).HasColumnName("level");
            entity.Property(e => e.MasterId).HasColumnName("master_id");
            entity.Property(e => e.Nature)
                .IsRequired()
                .HasMaxLength(8)
                .HasColumnName("nature");
            entity.Property(e => e.ParentId).HasColumnName("parent_id");
            entity.Property(e => e.SlaveCode).HasColumnName("slave_code");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("title");
            entity.Property(e => e.Title2)
                .HasMaxLength(100)
                .HasColumnName("title2");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(13)
                .HasColumnName("type");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.Category).WithMany(p => p.SlaveAccounts)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("slave_accounts_category_id_79276cde_fk_account_categories_id");

            entity.HasOne(d => d.Group).WithMany(p => p.SlaveAccounts)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("slave_accounts_group_id_d226c356_fk_account_groups_id");

            entity.HasOne(d => d.Ledger).WithMany(p => p.SlaveAccounts)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("slave_accounts_ledger_id_e9bba48c_fk_ledgers_id");

            entity.HasOne(d => d.Master).WithMany(p => p.SlaveAccounts)
                .HasForeignKey(d => d.MasterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("slave_accounts_master_id_d8364647_fk_master_accounts_id");

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("slave_accounts_parent_id_b5e3fe05_fk_slave_accounts_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SlaveAccount> entity);
    }
}
