// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class SlaveAccountStandardDescriptionConfiguration : IEntityTypeConfiguration<SlaveAccountStandardDescription>
    {
        public void Configure(EntityTypeBuilder<SlaveAccountStandardDescription> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__slave_ac__3213E83F626F9FCD");

            entity.ToTable("slave_account_standard_descriptions", "accounting");

            entity.HasIndex(e => e.CompanyId, "slave_account_standard_descriptions_company_id_a2d12c8c");

            entity.HasIndex(e => new { e.CompanyId, e.SlaveId, e.Description }, "slave_account_standard_descriptions_company_id_slave_id_description_fcd17f45_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [slave_id] IS NOT NULL AND [description] IS NOT NULL)");

            entity.HasIndex(e => e.SlaveId, "slave_account_standard_descriptions_slave_id_b64d916e");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.SlaveId).HasColumnName("slave_id");

            entity.HasOne(d => d.Slave).WithMany(p => p.SlaveAccountStandardDescriptions)
                .HasForeignKey(d => d.SlaveId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("slave_account_standard_descriptions_slave_id_b64d916e_fk_slave_accounts_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SlaveAccountStandardDescription> entity);
    }
}
