// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class TrashVoucherItemAttachConfiguration : IEntityTypeConfiguration<TrashVoucherItemAttach>
    {
        public void Configure(EntityTypeBuilder<TrashVoucherItemAttach> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__trash_vo__3213E83F0BB07B03");

            entity.ToTable("trash_voucher_item_attaches", "accounting");

            entity.HasIndex(e => e.TrashVoucherId, "trash_voucher_item_attaches_trash_voucher_id_aea53052");

            entity.HasIndex(e => e.TrashVoucherItemId, "trash_voucher_item_attaches_trash_voucher_item_id_f86212d2");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.File)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("file");
            entity.Property(e => e.TrashVoucherId).HasColumnName("trash_voucher_id");
            entity.Property(e => e.TrashVoucherItemId).HasColumnName("trash_voucher_item_id");

            entity.HasOne(d => d.TrashVoucher).WithMany(p => p.TrashVoucherItemAttaches)
                .HasForeignKey(d => d.TrashVoucherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("trash_voucher_item_attaches_trash_voucher_id_aea53052_fk_trash_vouchers_id");

            entity.HasOne(d => d.TrashVoucherItem).WithMany(p => p.TrashVoucherItemAttaches)
                .HasForeignKey(d => d.TrashVoucherItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("trash_voucher_item_attaches_trash_voucher_item_id_f86212d2_fk_trash_voucher_items_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TrashVoucherItemAttach> entity);
    }
}
