// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class TrashVoucherConfiguration : IEntityTypeConfiguration<TrashVoucher>
    {
        public void Configure(EntityTypeBuilder<TrashVoucher> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__trash_vo__3213E83F5C11B883");

            entity.ToTable("trash_vouchers", "accounting");

            entity.HasIndex(e => e.BranchId, "trash_vouchers_branch_id_4da4e4fa");

            entity.HasIndex(e => e.CompanyId, "trash_vouchers_company_id_01f6a6f1");

            entity.HasIndex(e => e.CreatorId, "trash_vouchers_creator_id_50cfb8a4");

            entity.HasIndex(e => e.LastModifierId, "trash_vouchers_last_modifier_id_35d033e0");

            entity.HasIndex(e => e.LedgerId, "trash_vouchers_ledger_id_e6d73246");

            entity.HasIndex(e => e.ModuleId, "trash_vouchers_module_id_3481836f");

            entity.HasIndex(e => e.PeriodId, "trash_vouchers_period_id_f1b414ea");

            entity.HasIndex(e => e.TypeId, "trash_vouchers_type_id_62c0b2ab");

            entity.HasIndex(e => e.VoucherIdInitial, "trash_vouchers_voucher_id_initial_f5cefa98");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.BranchId).HasColumnName("branch_id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.LastModifierId).HasColumnName("last_modifier_id");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.Number).HasColumnName("number");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.Serial).HasColumnName("serial");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(9)
                .HasColumnName("status");
            entity.Property(e => e.TypeId).HasColumnName("type_id");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");
            entity.Property(e => e.VoucherIdInitial).HasColumnName("voucher_id_initial");

            entity.HasOne(d => d.Ledger).WithMany(p => p.TrashVouchers)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("trash_vouchers_ledger_id_e6d73246_fk_ledgers_id");

            entity.HasOne(d => d.Period).WithMany(p => p.TrashVouchers)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("trash_vouchers_period_id_f1b414ea_fk_periods_id");

            entity.HasOne(d => d.Type).WithMany(p => p.TrashVouchers)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("trash_vouchers_type_id_62c0b2ab_fk_voucher_types_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TrashVoucher> entity);
    }
}
