// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class TtmsExportationConfiguration : IEntityTypeConfiguration<TtmsExportation>
    {
        public void Configure(EntityTypeBuilder<TtmsExportation> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__ttms_exp__3213E83F07EBF8D8");

            entity.ToTable("ttms_exportations", "accounting");

            entity.HasIndex(e => e.VoucherItemId, "UQ__ttms_exp__A2D3D11B14C08510").IsUnique();

            entity.HasIndex(e => e.ArzTypeId, "ttms_exportations_arz_type_id_a88c4e64");

            entity.HasIndex(e => e.CompanyId, "ttms_exportations_company_id_d4e9b554");

            entity.HasIndex(e => e.KalaTypeId, "ttms_exportations_kala_type_id_c8a03da3");

            entity.HasIndex(e => e.KharidarAddressId, "ttms_exportations_kharidar_address_id_b43af6ed");

            entity.HasIndex(e => e.KharidarCountryId, "ttms_exportations_kharidar_country_id_5b8e0edc");

            entity.HasIndex(e => e.KharidarId, "ttms_exportations_kharidar_id_f33336bf");

            entity.HasIndex(e => e.LedgerId, "ttms_exportations_ledger_id_b7fff67d");

            entity.HasIndex(e => e.PeriodId, "ttms_exportations_period_id_7c7cf71b");

            entity.HasIndex(e => e.VoucherId, "ttms_exportations_voucher_id_14d3710f");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ArzAvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("arz_avarez_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariAvarezArzeshAfzoodeh)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_avarez_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariMaliatArzeshAfzoodeh)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_maliat_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariMaliatMaksoore)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_maliat_maksoore");
            entity.Property(e => e.ArzBarabariPrice)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_price");
            entity.Property(e => e.ArzBarabariPriceParvane)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_price_parvane");
            entity.Property(e => e.ArzBarabariSayerAvarez)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_sayer_avarez");
            entity.Property(e => e.ArzBarabariTakhfifPrice)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_takhfif_price");
            entity.Property(e => e.ArzMaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("arz_maliat_arzesh_afzoodeh");
            entity.Property(e => e.ArzMaliatMaksoore)
                .HasMaxLength(23)
                .HasColumnName("arz_maliat_maksoore");
            entity.Property(e => e.ArzPrice)
                .HasMaxLength(23)
                .HasColumnName("arz_price");
            entity.Property(e => e.ArzPriceParvane)
                .HasMaxLength(23)
                .HasColumnName("arz_price_parvane");
            entity.Property(e => e.ArzSayerAvarez)
                .HasMaxLength(23)
                .HasColumnName("arz_sayer_avarez");
            entity.Property(e => e.ArzTakhfifPrice)
                .HasMaxLength(23)
                .HasColumnName("arz_takhfif_price");
            entity.Property(e => e.ArzTypeId).HasColumnName("arz_type_id");
            entity.Property(e => e.AvarezArzeshAfzoodeh)
                .IsRequired()
                .HasMaxLength(23)
                .HasColumnName("avarez_arzesh_afzoodeh");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.DealCurrency).HasColumnName("deal_currency");
            entity.Property(e => e.FactorDate)
                .HasMaxLength(10)
                .HasColumnName("factor_date");
            entity.Property(e => e.FactorNo)
                .HasMaxLength(50)
                .HasColumnName("factor_no");
            entity.Property(e => e.ForoushType).HasColumnName("foroush_type");
            entity.Property(e => e.GomrokArzyabi).HasColumnName("gomrok_arzyabi");
            entity.Property(e => e.GomrokKhoruj).HasColumnName("gomrok_khoruj");
            entity.Property(e => e.HcKharidarType1Code).HasColumnName("hc_kharidar_type_1_code");
            entity.Property(e => e.KalaCode)
                .HasColumnType("numeric(20, 0)")
                .HasColumnName("kala_code");
            entity.Property(e => e.KalaKhadamatName)
                .HasMaxLength(100)
                .HasColumnName("kala_khadamat_name");
            entity.Property(e => e.KalaTypeId)
                .HasMaxLength(10)
                .HasColumnName("kala_type_id");
            entity.Property(e => e.KharidarAddressId).HasColumnName("kharidar_address_id");
            entity.Property(e => e.KharidarCountryId).HasColumnName("kharidar_country_id");
            entity.Property(e => e.KharidarId).HasColumnName("kharidar_id");
            entity.Property(e => e.KotajDate)
                .HasMaxLength(10)
                .HasColumnName("kotaj_date");
            entity.Property(e => e.KotajNo).HasColumnName("kotaj_no");
            entity.Property(e => e.LcDate)
                .HasMaxLength(10)
                .HasColumnName("LC_date");
            entity.Property(e => e.LcNo)
                .HasMaxLength(19)
                .HasColumnName("LC_no");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.MaliatArzeshAfzoodeh)
                .IsRequired()
                .HasMaxLength(23)
                .HasColumnName("maliat_arzesh_afzoodeh");
            entity.Property(e => e.MaliatMaksoore)
                .HasMaxLength(23)
                .HasColumnName("maliat_maksoore");
            entity.Property(e => e.MoadelRialiAvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_avarez_arzesh_afzoodeh");
            entity.Property(e => e.MoadelRialiMaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_maliat_arzesh_afzoodeh");
            entity.Property(e => e.MoadelRialiMaliatMaksoore)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_maliat_maksoore");
            entity.Property(e => e.MoadelRialiPrice)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_price");
            entity.Property(e => e.MoadelRialiPriceParvane)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_price_parvane");
            entity.Property(e => e.MoadelRialiSayerAvarez)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_sayer_avarez");
            entity.Property(e => e.MoadelRialiTakhfifPrice)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_takhfif_price");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.Price)
                .IsRequired()
                .HasMaxLength(23)
                .HasColumnName("price");
            entity.Property(e => e.PriceParvane)
                .HasMaxLength(23)
                .HasColumnName("price_parvane");
            entity.Property(e => e.SayerAvarez)
                .IsRequired()
                .HasMaxLength(23)
                .HasColumnName("sayer_avarez");
            entity.Property(e => e.TakhfifPrice)
                .HasMaxLength(23)
                .HasColumnName("takhfif_price");
            entity.Property(e => e.Tozih)
                .HasMaxLength(255)
                .HasColumnName("tozih");
            entity.Property(e => e.VoucherId).HasColumnName("voucher_id");
            entity.Property(e => e.VoucherItemId).HasColumnName("voucher_item_id");

            entity.HasOne(d => d.KalaType).WithMany(p => p.TtmsExportations)
                .HasPrincipalKey(p => p.Code)
                .HasForeignKey(d => d.KalaTypeId)
                .HasConstraintName("ttms_exportations_kala_type_id_c8a03da3_fk_ttms_product_types_code");

            entity.HasOne(d => d.Ledger).WithMany(p => p.TtmsExportations)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_exportations_ledger_id_b7fff67d_fk_ledgers_id");

            entity.HasOne(d => d.Period).WithMany(p => p.TtmsExportations)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_exportations_period_id_7c7cf71b_fk_periods_id");

            entity.HasOne(d => d.Voucher).WithMany(p => p.TtmsExportations)
                .HasForeignKey(d => d.VoucherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_exportations_voucher_id_14d3710f_fk_vouchers_id");

            entity.HasOne(d => d.VoucherItem).WithOne(p => p.TtmsExportation)
                .HasForeignKey<TtmsExportation>(d => d.VoucherItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_exportations_voucher_item_id_0ac158de_fk_voucher_items_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TtmsExportation> entity);
    }
}
