// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class TtmsContractorInfoConfiguration : IEntityTypeConfiguration<TtmsContractorInfo>
    {
        public void Configure(EntityTypeBuilder<TtmsContractorInfo> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__ttms_con__3213E83FD517199C");

            entity.ToTable("ttms_contractor_infos", "accounting");

            entity.HasIndex(e => e.VoucherItemId, "UQ__ttms_con__A2D3D11BA8538DEB").IsUnique();

            entity.HasIndex(e => e.ArzTypeId, "ttms_contractor_infos_arz_type_id_2564bca6");

            entity.HasIndex(e => e.CompanyId, "ttms_contractor_infos_company_id_2e0427bc");

            entity.HasIndex(e => e.GharardadId, "ttms_contractor_infos_gharardad_id_46fdf4d6");

            entity.HasIndex(e => e.LedgerId, "ttms_contractor_infos_ledger_id_866da6c0");

            entity.HasIndex(e => e.PeriodId, "ttms_contractor_infos_period_id_0b3cc826");

            entity.HasIndex(e => e.PeymankarAddressId, "ttms_contractor_infos_peymankar_address_id_f058807c");

            entity.HasIndex(e => e.PeymankarId, "ttms_contractor_infos_peymankar_id_0c4a252f");

            entity.HasIndex(e => e.PeymankarPhoneId, "ttms_contractor_infos_peymankar_phone_id_aeeaee77");

            entity.HasIndex(e => e.VoucherId, "ttms_contractor_infos_voucher_id_4561f0d4");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ArzAvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("arz_avarez_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariAvarezArzeshAfzoodeh)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_avarez_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariKhales)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_khales");
            entity.Property(e => e.ArzBarabariMaliatArzeshAfzoodeh)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_maliat_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariMaliatMaksooreh)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_maliat_maksooreh");
            entity.Property(e => e.ArzBarabariNakhales)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_nakhales");
            entity.Property(e => e.ArzBarabariSayerAvarez)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_sayer_avarez");
            entity.Property(e => e.ArzKhales)
                .HasMaxLength(23)
                .HasColumnName("arz_khales");
            entity.Property(e => e.ArzMaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("arz_maliat_arzesh_afzoodeh");
            entity.Property(e => e.ArzMaliatMaksooreh)
                .HasMaxLength(23)
                .HasColumnName("arz_maliat_maksooreh");
            entity.Property(e => e.ArzNakhales)
                .HasMaxLength(23)
                .HasColumnName("arz_nakhales");
            entity.Property(e => e.ArzSayerAvarez)
                .HasMaxLength(23)
                .HasColumnName("arz_sayer_avarez");
            entity.Property(e => e.ArzTotalPrice)
                .HasMaxLength(23)
                .HasColumnName("arz_total_price");
            entity.Property(e => e.ArzTypeId).HasColumnName("arz_type_id");
            entity.Property(e => e.AvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("avarez_arzesh_afzoodeh");
            entity.Property(e => e.BargashtType).HasColumnName("bargasht_type");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.DealCurrency).HasColumnName("deal_currency");
            entity.Property(e => e.GharardadActivityTypeCode).HasColumnName("gharardad_activity_type_code");
            entity.Property(e => e.GharardadId).HasColumnName("gharardad_id");
            entity.Property(e => e.KhalesPrice)
                .HasMaxLength(23)
                .HasColumnName("khales_price");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.MaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("maliat_arzesh_afzoodeh");
            entity.Property(e => e.MaliatMaksooreh)
                .HasMaxLength(23)
                .HasColumnName("maliat_maksooreh");
            entity.Property(e => e.MoadelRialiAvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_avarez_arzesh_afzoodeh");
            entity.Property(e => e.MoadelRialiKhales)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_khales");
            entity.Property(e => e.MoadelRialiMaksooreh)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_maksooreh");
            entity.Property(e => e.MoadelRialiMaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_maliat_arzesh_afzoodeh");
            entity.Property(e => e.MoadelRialiNakhales)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_nakhales");
            entity.Property(e => e.MoadelRialiSayerAvarez)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_sayer_avarez");
            entity.Property(e => e.Nakhales)
                .HasMaxLength(23)
                .HasColumnName("nakhales");
            entity.Property(e => e.PardakhtDate)
                .HasMaxLength(10)
                .HasColumnName("pardakht_date");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.PeymankarAddressId).HasColumnName("peymankar_address_id");
            entity.Property(e => e.PeymankarId).HasColumnName("peymankar_id");
            entity.Property(e => e.PeymankarPhoneId).HasColumnName("peymankar_phone_id");
            entity.Property(e => e.SayerAvarez)
                .HasMaxLength(23)
                .HasColumnName("sayer_avarez");
            entity.Property(e => e.SuratVaziatDate)
                .HasMaxLength(10)
                .HasColumnName("surat_vaziat_date");
            entity.Property(e => e.SuratVaziatNumber)
                .HasMaxLength(50)
                .HasColumnName("surat_vaziat_number");
            entity.Property(e => e.TotalPrice)
                .HasMaxLength(23)
                .HasColumnName("total_price");
            entity.Property(e => e.VoucherId).HasColumnName("voucher_id");
            entity.Property(e => e.VoucherItemId).HasColumnName("voucher_item_id");

            entity.HasOne(d => d.Ledger).WithMany(p => p.TtmsContractorInfos)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_contractor_infos_ledger_id_866da6c0_fk_ledgers_id");

            entity.HasOne(d => d.Period).WithMany(p => p.TtmsContractorInfos)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_contractor_infos_period_id_0b3cc826_fk_periods_id");

            entity.HasOne(d => d.Voucher).WithMany(p => p.TtmsContractorInfos)
                .HasForeignKey(d => d.VoucherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_contractor_infos_voucher_id_4561f0d4_fk_vouchers_id");

            entity.HasOne(d => d.VoucherItem).WithOne(p => p.TtmsContractorInfo)
                .HasForeignKey<TtmsContractorInfo>(d => d.VoucherItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_contractor_infos_voucher_item_id_f0e62792_fk_voucher_items_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TtmsContractorInfo> entity);
    }
}
