// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class TtmsBuyConfiguration : IEntityTypeConfiguration<TtmsBuy>
    {
        public void Configure(EntityTypeBuilder<TtmsBuy> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__ttms_buy__3213E83FF4617A16");

            entity.ToTable("ttms_buys", "accounting");

            entity.HasIndex(e => e.VoucherItemId, "UQ__ttms_buy__A2D3D11B3AE62649").IsUnique();

            entity.HasIndex(e => e.ArzTypeId, "ttms_buys_arz_type_id_842752a5");

            entity.HasIndex(e => e.CompanyId, "ttms_buys_company_id_86d0df71");

            entity.HasIndex(e => e.ForoshandeAddressId, "ttms_buys_foroshande_address_id_f6676def");

            entity.HasIndex(e => e.ForoshandeId, "ttms_buys_foroshande_id_899255d3");

            entity.HasIndex(e => e.ForoshandePhoneId, "ttms_buys_foroshande_phone_id_85d73354");

            entity.HasIndex(e => e.KalaTypeId, "ttms_buys_kala_type_id_acc1c01e");

            entity.HasIndex(e => e.LedgerId, "ttms_buys_ledger_id_4592b702");

            entity.HasIndex(e => e.PeriodId, "ttms_buys_period_id_b172660c");

            entity.HasIndex(e => e.VoucherId, "ttms_buys_voucher_id_932f90cb");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ArzAvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("arz_avarez_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariAvarezArzeshAfzoodeh)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_avarez_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariMaliatArzeshAfzoodeh)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_maliat_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariMaliatMaksoore)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_maliat_maksoore");
            entity.Property(e => e.ArzBarabariPrice)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_price");
            entity.Property(e => e.ArzBarabariSayerAvarez)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_sayer_avarez");
            entity.Property(e => e.ArzBarabariTakhfifPrice)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_takhfif_price");
            entity.Property(e => e.ArzMaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("arz_maliat_arzesh_afzoodeh");
            entity.Property(e => e.ArzMaliatMaksoore)
                .HasMaxLength(23)
                .HasColumnName("arz_maliat_maksoore");
            entity.Property(e => e.ArzPrice)
                .HasMaxLength(23)
                .HasColumnName("arz_price");
            entity.Property(e => e.ArzSayerAvarez)
                .HasMaxLength(23)
                .HasColumnName("arz_sayer_avarez");
            entity.Property(e => e.ArzTakhfifPrice)
                .HasMaxLength(23)
                .HasColumnName("arz_takhfif_price");
            entity.Property(e => e.ArzTypeId).HasColumnName("arz_type_id");
            entity.Property(e => e.AvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("avarez_arzesh_afzoodeh");
            entity.Property(e => e.BargashtType).HasColumnName("bargasht_type");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.DealCurrency).HasColumnName("deal_currency");
            entity.Property(e => e.FactorDate)
                .HasMaxLength(10)
                .HasColumnName("factor_date");
            entity.Property(e => e.FactorNo)
                .HasMaxLength(50)
                .HasColumnName("factor_no");
            entity.Property(e => e.ForoshandeAddressId).HasColumnName("foroshande_address_id");
            entity.Property(e => e.ForoshandeId).HasColumnName("foroshande_id");
            entity.Property(e => e.ForoshandePhoneId).HasColumnName("foroshande_phone_id");
            entity.Property(e => e.IsHagholamalKari).HasColumnName("is_hagholamal_kari");
            entity.Property(e => e.KalaCode)
                .HasColumnType("numeric(20, 0)")
                .HasColumnName("kala_code");
            entity.Property(e => e.KalaKhadamatName)
                .HasMaxLength(100)
                .HasColumnName("kala_khadamat_name");
            entity.Property(e => e.KalaTypeId).HasColumnName("kala_type_id");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.MaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("maliat_arzesh_afzoodeh");
            entity.Property(e => e.MaliatMaksoore)
                .HasMaxLength(23)
                .HasColumnName("maliat_maksoore");
            entity.Property(e => e.MoadelRialiAvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_avarez_arzesh_afzoodeh");
            entity.Property(e => e.MoadelRialiMaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_maliat_arzesh_afzoodeh");
            entity.Property(e => e.MoadelRialiMaliatMaksoore)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_maliat_maksoore");
            entity.Property(e => e.MoadelRialiPrice)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_price");
            entity.Property(e => e.MoadelRialiSayerAvarez)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_sayer_avarez");
            entity.Property(e => e.MoadelRialiTakhfifPrice)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_takhfif_price");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.Price)
                .HasMaxLength(23)
                .HasColumnName("price");
            entity.Property(e => e.Sarjam).HasColumnName("sarjam");
            entity.Property(e => e.SayerAvarez)
                .HasMaxLength(23)
                .HasColumnName("sayer_avarez");
            entity.Property(e => e.TakhfifPrice)
                .HasMaxLength(23)
                .HasColumnName("takhfif_price");
            entity.Property(e => e.VoucherId).HasColumnName("voucher_id");
            entity.Property(e => e.VoucherItemId).HasColumnName("voucher_item_id");

            entity.HasOne(d => d.KalaType).WithMany(p => p.TtmsBuys)
                .HasForeignKey(d => d.KalaTypeId)
                .HasConstraintName("ttms_buys_kala_type_id_acc1c01e_fk_ttms_product_types_id");

            entity.HasOne(d => d.Ledger).WithMany(p => p.TtmsBuys)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_buys_ledger_id_4592b702_fk_ledgers_id");

            entity.HasOne(d => d.Period).WithMany(p => p.TtmsBuys)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_buys_period_id_b172660c_fk_periods_id");

            entity.HasOne(d => d.Voucher).WithMany(p => p.TtmsBuys)
                .HasForeignKey(d => d.VoucherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_buys_voucher_id_932f90cb_fk_vouchers_id");

            entity.HasOne(d => d.VoucherItem).WithOne(p => p.TtmsBuy)
                .HasForeignKey<TtmsBuy>(d => d.VoucherItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_buys_voucher_item_id_f176cf2a_fk_voucher_items_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TtmsBuy> entity);
    }
}
