// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class TtmsLeaseAgreementConfiguration : IEntityTypeConfiguration<TtmsLeaseAgreement>
    {
        public void Configure(EntityTypeBuilder<TtmsLeaseAgreement> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__ttms_lea__3213E83FCB177D07");

            entity.ToTable("ttms_lease_agreements", "accounting");

            entity.HasIndex(e => e.VoucherItemId, "UQ__ttms_lea__A2D3D11B4215A57D").IsUnique();

            entity.HasIndex(e => e.ArzTypeId, "ttms_lease_agreements_arz_type_id_eb4b0083");

            entity.HasIndex(e => e.CompanyId, "ttms_lease_agreements_company_id_fe87aa2f");

            entity.HasIndex(e => e.GharardadId, "ttms_lease_agreements_gharardad_id_9c794542");

            entity.HasIndex(e => e.LedgerId, "ttms_lease_agreements_ledger_id_fbcd73fe");

            entity.HasIndex(e => e.MelkCityId, "ttms_lease_agreements_melk_city_id_c6850824");

            entity.HasIndex(e => e.MelkStateId, "ttms_lease_agreements_melk_state_id_970e540d");

            entity.HasIndex(e => e.PeriodId, "ttms_lease_agreements_period_id_b7dd6e0b");

            entity.HasIndex(e => e.TarafeGharardadAddressId, "ttms_lease_agreements_tarafe_gharardad_address_id_cf429de4");

            entity.HasIndex(e => e.TarafeGharardadId, "ttms_lease_agreements_tarafe_gharardad_id_9d1d1f02");

            entity.HasIndex(e => e.TarafeGharardadPhoneId, "ttms_lease_agreements_tarafe_gharardad_phone_id_c4fefd27");

            entity.HasIndex(e => e.VoucherId, "ttms_lease_agreements_voucher_id_38801563");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ArzAvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("arz_avarez_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariAvarezArzeshAfzoodeh)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_avarez_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariMaliatArzeshAfzoodeh)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_maliat_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariMaliatMaksoore)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_maliat_maksoore");
            entity.Property(e => e.ArzBarabariNakhales)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_nakhales");
            entity.Property(e => e.ArzMaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("arz_maliat_arzesh_afzoodeh");
            entity.Property(e => e.ArzMaliatMaksoore)
                .HasMaxLength(23)
                .HasColumnName("arz_maliat_maksoore");
            entity.Property(e => e.ArzNakhales)
                .HasMaxLength(23)
                .HasColumnName("arz_nakhales");
            entity.Property(e => e.ArzTypeId).HasColumnName("arz_type_id");
            entity.Property(e => e.AvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("avarez_arzesh_afzoodeh");
            entity.Property(e => e.BakhshSabti)
                .HasMaxLength(25)
                .HasColumnName("bakhsh_sabti");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.DealCurrency).HasColumnName("deal_currency");
            entity.Property(e => e.EjariType).HasColumnName("ejari_type");
            entity.Property(e => e.GharardadId).HasColumnName("gharardad_id");
            entity.Property(e => e.GharardadTypeCode).HasColumnName("gharardad_type_code");
            entity.Property(e => e.KarbariType).HasColumnName("karbari_type");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.MaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("maliat_arzesh_afzoodeh");
            entity.Property(e => e.MaliatMaksoore)
                .HasMaxLength(23)
                .HasColumnName("maliat_maksoore");
            entity.Property(e => e.MelkAddress)
                .HasMaxLength(80)
                .HasColumnName("melk_address");
            entity.Property(e => e.MelkCityId).HasColumnName("melk_city_id");
            entity.Property(e => e.MelkPostCode)
                .HasMaxLength(10)
                .HasColumnName("melk_post_code");
            entity.Property(e => e.MelkStateId).HasColumnName("melk_state_id");
            entity.Property(e => e.MelkTell)
                .HasMaxLength(50)
                .HasColumnName("melk_tell");
            entity.Property(e => e.MelkTellPishCode)
                .HasMaxLength(10)
                .HasColumnName("melk_tell_pish_code");
            entity.Property(e => e.MoadelRialiAvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_avarez_arzesh_afzoodeh");
            entity.Property(e => e.MoadelRialiMaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_maliat_arzesh_afzoodeh");
            entity.Property(e => e.MoadelRialiMaliatMaksoore)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_maliat_maksoore");
            entity.Property(e => e.MoadelRialiNakhales)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_nakhales");
            entity.Property(e => e.MozuType).HasColumnName("mozu_type");
            entity.Property(e => e.Nakhales)
                .HasMaxLength(23)
                .HasColumnName("nakhales");
            entity.Property(e => e.PelakSabtiAsli)
                .HasMaxLength(25)
                .HasColumnName("pelak_sabti_asli");
            entity.Property(e => e.PelakSabtiFari)
                .HasMaxLength(25)
                .HasColumnName("pelak_sabti_fari");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.SanadDate)
                .HasMaxLength(10)
                .HasColumnName("sanad_date");
            entity.Property(e => e.SanadNo).HasColumnName("sanad_no");
            entity.Property(e => e.ShenaseMelk)
                .HasMaxLength(25)
                .HasColumnName("shenase_melk");
            entity.Property(e => e.TarafeGharardadAddressId).HasColumnName("tarafe_gharardad_address_id");
            entity.Property(e => e.TarafeGharardadId).HasColumnName("tarafe_gharardad_id");
            entity.Property(e => e.TarafeGharardadPhoneId).HasColumnName("tarafe_gharardad_phone_id");
            entity.Property(e => e.TarafeGharardadType).HasColumnName("tarafe_gharardad_type");
            entity.Property(e => e.TedadShoraka).HasColumnName("tedad_shoraka");
            entity.Property(e => e.Tozih)
                .HasMaxLength(255)
                .HasColumnName("tozih");
            entity.Property(e => e.Vasile).HasColumnName("vasile");
            entity.Property(e => e.VoucherId).HasColumnName("voucher_id");
            entity.Property(e => e.VoucherItemId).HasColumnName("voucher_item_id");

            entity.HasOne(d => d.Ledger).WithMany(p => p.TtmsLeaseAgreements)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_lease_agreements_ledger_id_fbcd73fe_fk_ledgers_id");

            entity.HasOne(d => d.Period).WithMany(p => p.TtmsLeaseAgreements)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_lease_agreements_period_id_b7dd6e0b_fk_periods_id");

            entity.HasOne(d => d.Voucher).WithMany(p => p.TtmsLeaseAgreements)
                .HasForeignKey(d => d.VoucherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_lease_agreements_voucher_id_38801563_fk_vouchers_id");

            entity.HasOne(d => d.VoucherItem).WithOne(p => p.TtmsLeaseAgreement)
                .HasForeignKey<TtmsLeaseAgreement>(d => d.VoucherItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_lease_agreements_voucher_item_id_580d9a03_fk_voucher_items_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TtmsLeaseAgreement> entity);
    }
}
