// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class TtmsProductTypeConfiguration : IEntityTypeConfiguration<TtmsProductType>
    {
        public void Configure(EntityTypeBuilder<TtmsProductType> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__ttms_pro__3213E83FDC489187");

            entity.ToTable("ttms_product_types", "accounting");

            entity.HasIndex(e => e.Code, "UQ__ttms_pro__357D4CF9F1A81110").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("code");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TtmsProductType> entity);
    }
}
