// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class TtmsEmployerInfoConfiguration : IEntityTypeConfiguration<TtmsEmployerInfo>
    {
        public void Configure(EntityTypeBuilder<TtmsEmployerInfo> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__ttms_emp__3213E83F8C522BC1");

            entity.ToTable("ttms_employer_infos", "accounting");

            entity.HasIndex(e => e.VoucherItemId, "UQ__ttms_emp__A2D3D11B5AB028CE").IsUnique();

            entity.HasIndex(e => e.ArzTypeId, "ttms_employer_infos_arz_type_id_64a2746a");

            entity.HasIndex(e => e.CompanyId, "ttms_employer_infos_company_id_f5ced1a0");

            entity.HasIndex(e => e.GharardadId, "ttms_employer_infos_gharardad_id_38dc7897");

            entity.HasIndex(e => e.KarfarmaAddressId, "ttms_employer_infos_karfarma_address_id_fbf74ad6");

            entity.HasIndex(e => e.KarfarmaId, "ttms_employer_infos_karfarma_id_e737c2aa");

            entity.HasIndex(e => e.KarfarmaPhoneId, "ttms_employer_infos_karfarma_phone_id_a109c622");

            entity.HasIndex(e => e.LedgerId, "ttms_employer_infos_ledger_id_4e6cb6c7");

            entity.HasIndex(e => e.PeriodId, "ttms_employer_infos_period_id_f2de7f69");

            entity.HasIndex(e => e.VoucherId, "ttms_employer_infos_voucher_id_c3d5dd84");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ArzAvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("arz_avarez_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariAvarezArzeshAfzoodeh)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_avarez_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariKhales)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_khales");
            entity.Property(e => e.ArzBarabariMaliatArzeshAfzoodeh)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_maliat_arzesh_afzoodeh");
            entity.Property(e => e.ArzBarabariMaliatMaksooreh)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_maliat_maksooreh");
            entity.Property(e => e.ArzBarabariNakhales)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_nakhales");
            entity.Property(e => e.ArzBarabariSayerAvarez)
                .HasColumnType("numeric(13, 5)")
                .HasColumnName("arz_barabari_sayer_avarez");
            entity.Property(e => e.ArzKhales)
                .HasMaxLength(23)
                .HasColumnName("arz_khales");
            entity.Property(e => e.ArzMaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("arz_maliat_arzesh_afzoodeh");
            entity.Property(e => e.ArzMaliatMaksooreh)
                .HasMaxLength(23)
                .HasColumnName("arz_maliat_maksooreh");
            entity.Property(e => e.ArzNakhales)
                .HasMaxLength(23)
                .HasColumnName("arz_nakhales");
            entity.Property(e => e.ArzSayerAvarez)
                .HasMaxLength(23)
                .HasColumnName("arz_sayer_avarez");
            entity.Property(e => e.ArzTotalPrice)
                .HasMaxLength(23)
                .HasColumnName("arz_total_price");
            entity.Property(e => e.ArzTypeId).HasColumnName("arz_type_id");
            entity.Property(e => e.AvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("avarez_arzesh_afzoodeh");
            entity.Property(e => e.BargashtType).HasColumnName("bargasht_type");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.DaryaftDate)
                .HasMaxLength(10)
                .HasColumnName("daryaft_date");
            entity.Property(e => e.DealCurrency).HasColumnName("deal_currency");
            entity.Property(e => e.GharardadActivityTypeCode).HasColumnName("gharardad_activity_type_code");
            entity.Property(e => e.GharardadId).HasColumnName("gharardad_id");
            entity.Property(e => e.KarfarmaAddressId).HasColumnName("karfarma_address_id");
            entity.Property(e => e.KarfarmaId).HasColumnName("karfarma_id");
            entity.Property(e => e.KarfarmaPhoneId).HasColumnName("karfarma_phone_id");
            entity.Property(e => e.KhalesPrice)
                .HasMaxLength(23)
                .HasColumnName("khales_price");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.MaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("maliat_arzesh_afzoodeh");
            entity.Property(e => e.MaliatMaksooreh)
                .HasMaxLength(23)
                .HasColumnName("maliat_maksooreh");
            entity.Property(e => e.MoadelRialiAvarezArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_avarez_arzesh_afzoodeh");
            entity.Property(e => e.MoadelRialiKhales)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_khales");
            entity.Property(e => e.MoadelRialiMaksooreh)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_maksooreh");
            entity.Property(e => e.MoadelRialiMaliatArzeshAfzoodeh)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_maliat_arzesh_afzoodeh");
            entity.Property(e => e.MoadelRialiNakhales)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_nakhales");
            entity.Property(e => e.MoadelRialiSayerAvarez)
                .HasMaxLength(23)
                .HasColumnName("moadel_riali_sayer_avarez");
            entity.Property(e => e.Nakhales)
                .HasMaxLength(23)
                .HasColumnName("nakhales");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.ReportType).HasColumnName("report_type");
            entity.Property(e => e.SayerAvarez)
                .HasMaxLength(23)
                .HasColumnName("sayer_avarez");
            entity.Property(e => e.SuratVaziatDate)
                .HasMaxLength(10)
                .HasColumnName("surat_vaziat_date");
            entity.Property(e => e.SuratVaziatNumber)
                .HasMaxLength(50)
                .HasColumnName("surat_vaziat_number");
            entity.Property(e => e.TotalPrice)
                .HasMaxLength(23)
                .HasColumnName("total_price");
            entity.Property(e => e.VoucherId).HasColumnName("voucher_id");
            entity.Property(e => e.VoucherItemId).HasColumnName("voucher_item_id");

            entity.HasOne(d => d.Ledger).WithMany(p => p.TtmsEmployerInfos)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_employer_infos_ledger_id_4e6cb6c7_fk_ledgers_id");

            entity.HasOne(d => d.Period).WithMany(p => p.TtmsEmployerInfos)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_employer_infos_period_id_f2de7f69_fk_periods_id");

            entity.HasOne(d => d.Voucher).WithMany(p => p.TtmsEmployerInfos)
                .HasForeignKey(d => d.VoucherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_employer_infos_voucher_id_c3d5dd84_fk_vouchers_id");

            entity.HasOne(d => d.VoucherItem).WithOne(p => p.TtmsEmployerInfo)
                .HasForeignKey<TtmsEmployerInfo>(d => d.VoucherItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ttms_employer_infos_voucher_item_id_1756b20f_fk_voucher_items_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TtmsEmployerInfo> entity);
    }
}
