// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class VoucherConfiguration : IEntityTypeConfiguration<Voucher>
    {
        public void Configure(EntityTypeBuilder<Voucher> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__vouchers__3213E83F37737C08");

            entity.ToTable("vouchers", "accounting");

            entity.HasIndex(e => e.BranchId, "vouchers_branch_id_f6f281ae");

            entity.HasIndex(e => e.CompanyId, "vouchers_company_id_87927ee9");

            entity.HasIndex(e => new { e.CompanyId, e.LedgerId, e.PeriodId, e.Number }, "vouchers_company_id_ledger_id_period_id_number_10cfc9fc_uniq")
                .IsUnique()
                .HasFilter("([company_id] IS NOT NULL AND [ledger_id] IS NOT NULL AND [period_id] IS NOT NULL AND [number] IS NOT NULL)");

            entity.HasIndex(e => e.CreatorId, "vouchers_creator_id_b7f0b4f8");

            entity.HasIndex(e => e.LastModifierId, "vouchers_last_modifier_id_61732409");

            entity.HasIndex(e => e.LedgerId, "vouchers_ledger_id_25e3f63d");

            entity.HasIndex(e => e.ModuleId, "vouchers_module_id_65b2cf76");

            entity.HasIndex(e => e.PeriodId, "vouchers_period_id_800ded6b");

            entity.HasIndex(e => e.TypeId, "vouchers_type_id_05bcc3a6");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.BranchId).HasColumnName("branch_id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatorId).HasColumnName("creator_id");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.IdInitial).HasColumnName("id_initial");
            entity.Property(e => e.LastModifierId).HasColumnName("last_modifier_id");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.Number).HasColumnName("number");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.Serial).HasColumnName("serial");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(9)
                .HasColumnName("status");
            entity.Property(e => e.TypeId).HasColumnName("type_id");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");

            entity.HasOne(d => d.Ledger).WithMany(p => p.Vouchers)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("vouchers_ledger_id_25e3f63d_fk_ledgers_id");

            entity.HasOne(d => d.Period).WithMany(p => p.Vouchers)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("vouchers_period_id_800ded6b_fk_periods_id");

            entity.HasOne(d => d.Type).WithMany(p => p.Vouchers)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("vouchers_type_id_05bcc3a6_fk_voucher_types_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Voucher> entity);
    }
}
