// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Accounting.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Accounting.Infrastructure.DataAccess.Configurations
{
    public partial class VoucherLogConfiguration : IEntityTypeConfiguration<VoucherLog>
    {
        public void Configure(EntityTypeBuilder<VoucherLog> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__voucher___3213E83FFDA3BE8A");

            entity.ToTable("voucher_logs", "accounting");

            entity.HasIndex(e => e.BranchId, "voucher_logs_branch_id_099c72df");

            entity.HasIndex(e => e.CompanyId, "voucher_logs_company_id_9a183a61");

            entity.HasIndex(e => e.LedgerId, "voucher_logs_ledger_id_b35b1cc4");

            entity.HasIndex(e => e.ModifierId, "voucher_logs_modifier_id_b948dfef");

            entity.HasIndex(e => e.OldBranchId, "voucher_logs_old_branch_id_fbd37c8c");

            entity.HasIndex(e => e.OldVoucherTypeId, "voucher_logs_old_voucher_type_id_e9551d26");

            entity.HasIndex(e => e.PeriodId, "voucher_logs_period_id_02857e11");

            entity.HasIndex(e => e.VoucherId, "voucher_logs_voucher_id_34970cb1");

            entity.HasIndex(e => e.VoucherIdInitial, "voucher_logs_voucher_id_initial_60e0fc0b");

            entity.HasIndex(e => e.VoucherTypeId, "voucher_logs_voucher_type_id_5ba5b90d");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Attaches)
                .HasMaxLength(500)
                .HasColumnName("attaches");
            entity.Property(e => e.BranchId).HasColumnName("branch_id");
            entity.Property(e => e.CompanyId).HasColumnName("company_id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.Data).HasColumnName("data");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.LedgerId).HasColumnName("ledger_id");
            entity.Property(e => e.ModifierId).HasColumnName("modifier_id");
            entity.Property(e => e.Number).HasColumnName("number");
            entity.Property(e => e.OldBranchId).HasColumnName("old_branch_id");
            entity.Property(e => e.OldDate).HasColumnName("old_date");
            entity.Property(e => e.OldDescription)
                .HasMaxLength(500)
                .HasColumnName("old_description");
            entity.Property(e => e.OldNumber).HasColumnName("old_number");
            entity.Property(e => e.OldStatus)
                .HasMaxLength(9)
                .HasColumnName("old_status");
            entity.Property(e => e.OldVoucherTypeId).HasColumnName("old_voucher_type_id");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.Reason)
                .HasMaxLength(500)
                .HasColumnName("reason");
            entity.Property(e => e.Serial).HasColumnName("serial");
            entity.Property(e => e.Status)
                .HasMaxLength(9)
                .HasColumnName("status");
            entity.Property(e => e.Typ)
                .IsRequired()
                .HasMaxLength(35)
                .HasColumnName("typ");
            entity.Property(e => e.VoucherId).HasColumnName("voucher_id");
            entity.Property(e => e.VoucherIdInitial).HasColumnName("voucher_id_initial");
            entity.Property(e => e.VoucherTypeId).HasColumnName("voucher_type_id");

            entity.HasOne(d => d.Ledger).WithMany(p => p.VoucherLogs)
                .HasForeignKey(d => d.LedgerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("voucher_logs_ledger_id_b35b1cc4_fk_ledgers_id");

            entity.HasOne(d => d.OldVoucherType).WithMany(p => p.VoucherLogOldVoucherTypes)
                .HasForeignKey(d => d.OldVoucherTypeId)
                .HasConstraintName("voucher_logs_old_voucher_type_id_e9551d26_fk_voucher_types_id");

            entity.HasOne(d => d.Period).WithMany(p => p.VoucherLogs)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("voucher_logs_period_id_02857e11_fk_periods_id");

            entity.HasOne(d => d.Voucher).WithMany(p => p.VoucherLogs)
                .HasForeignKey(d => d.VoucherId)
                .HasConstraintName("voucher_logs_voucher_id_34970cb1_fk_vouchers_id");

            entity.HasOne(d => d.VoucherType).WithMany(p => p.VoucherLogVoucherTypes)
                .HasForeignKey(d => d.VoucherTypeId)
                .HasConstraintName("voucher_logs_voucher_type_id_5ba5b90d_fk_voucher_types_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VoucherLog> entity);
    }
}
