// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HCM.Domain.Entities;
using HCM.Infrastructure.DataAccess.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

#nullable disable

namespace HCM.Infrastructure.DataAccess
{
    public partial class HCMDbContext : DbContext
    {
        public HCMDbContext(DbContextOptions<HCMDbContext> options)
            : base(options)
        {
        }

        public DbSet<Department> Departments { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("HCM");
            modelBuilder.UseCollation("Persian_100_CI_AI");

            modelBuilder.ApplyConfigurationsFromAssembly(typeof(HCMDbContext).Assembly);
        }

    }
}
